### PR TITLE
Correct sizeof for unsigned types. Fixes #328

### LINKED ISSUE #328: CUnsignedShort has wrong size
`sizeof[CUnsignedShort]` returns 8, whereas `sizeof(unsigned short)` returns 2 in C (x86_64, Linux).

### PR DESCRIPTION
**Pull request by ragnr**

### CODE REVIEW

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirCodeGen.scala [hunk 1]
```diff
@@ -1417,7 +1417,7 @@ abstract class NirCodeGen
       val ty  = genTypeSym(sym)
```
Comment (pbatko) [inline nscplugin/src/main/scala/scala/scalanative/nscplugin/NirCodeGen.scala]: `ty` seems to be not used anymore

**Comment by densh** [comment]
LGTM, thanks @ragnr !
