### PR TITLE
Fix #2280: Add Unix-only IPv6 TCP support to javalib

### LINKED ISSUE #2280: javalib socket code appears to not support IPv6.
There appear to be some references in the javalib code to IPv6, but there
is a glaring error `PlainSocketImpl.scala`:
```
  override def create(streaming: Boolean): Unit = {
    val sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
    if (sock < 0) throw new IOException("Couldn't create a socket")
    fd = new FileDescriptor(sock)
  }
```
This situation probably stems from Harmony code not having supported IPv6.

There is some code in `unit-tests/src/test/scala/java/net/URITest.scala` which
does some IPv6 testing.  On a quick pass, I did not see any testing of
actually sending and receiving from an IPv6 socket,

There may not be months of  developer cycles available to properly implement
IPv6.  To my thinking, the least acceptable solution is to, somewhere, detect
and error when presented with IPv6 and other known unsupported address
families.

### PR DESCRIPTION
**Pull request by LeeTibbert**
We add IPv6 TCP, a.k.a streaming, support to javalib net on Unix-like systems.

This allows Scala Native programs using javalib TCP sockets to use a more efficient
network protocol.

This capability will probably be most used by programs ported from JVM or ScalaJVM.
posixlib sockets offer much finer control with less internal overhead.

The "Java Standard Library" section of the ReadTheDocs Scala Native documentation
is updated in the PR and provides the best description of the new IPv6 support.

The TL;DR is that if a Scala Native JVM program is using IPv6 successfully, then
that program should work with this new IPv6 support.

 This work follows the two decade long precedent of the JVM in silently
enabling the use of IPv6 if any network interface, other than the loopback
interface, is configured for IPv6.  Programs can execute code to
disable that default enabling.   

This PR incorporates the changes from two network related PRs that
were merged in the 0.4.x stream.

It has benefited from review and discussion in WIP PR #2484, which
it supersedes.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
I believe that support for Windows could be provided by someone with knowledge.  I believe
there are three key intervention points where Windows does something different.   Of course,
there could be more. 

Over the course of the next few months, I hope to get a Windows development environment
set up and may take a run at providing Windows support.  The Unix code can be
exercised and provide value during that time, even though not "All at once".

**Comment by LeeTibbert** [comment]
I believe that support for Windows could be provided by someone with knowledge.  I believe
there are three key intervention points where Windows does something different.   Of course,
there could be more. 

Over the course of the next few months, I hope to get a Windows development environment
set up and may take a run at providing Windows support.  The Unix code can be
exercised and provide value during that time, even though IPv6 support is not "All at once".

File: unit-tests/shared/src/test/scala/javalib/net/SocketTest.scala [hunk 1]
```diff
@@ -138,19 +139,74 @@ class SocketTest {
...
-    )
-    val s = new Socket()
-    try {
-      s.setTrafficClass(0x28)
-      assertEquals(s.getTrafficClass, 0x28)
-    } finally {
-      s.close()
+
+    val prop = System.getProperty("java.net.preferIPv4Stack")
+    val useIPv4 = (prop != null) && (prop.toLowerCase() == "true")
```
Comment (WojciechMazur) [inline unit-tests/shared/src/test/scala/javalib/net/SocketTest.scala:168]: Not really important but we can use `sys.SystemProperties.preferIPv4Stack.value` here. This hint can be ignored here.

**Review by WojciechMazur — APPROVED** [review]

File: unit-tests/shared/src/test/scala/javalib/net/SocketTest.scala (hunk 1 above)
Comment (LeeTibbert) [reply unit-tests/shared/src/test/scala/javalib/net/SocketTest.scala:168]: I can retrace the sys.SystemProperties.preferIPv4Stack path again.  I usually like single points
of implementation.  Either I found the sys.systemProperties after I wrote this.   My memory
is that there is a subtlety about the time the (lazy?) val is evaluated. The present code
is pretty sure to evaluate when the first Socket is accessed.

Comment (LeeTibbert) [reply unit-tests/shared/src/test/scala/javalib/net/SocketTest.scala:168]: I like to do thing right the first time, but this whole initialization is subject to "appropriate precision". 
That is, it is almost certain that likely change will overwhelm & obliterate putting too fine a point on
this initialization in particular.

Thank you for the merge.

**Comment by LeeTibbert** [comment]
For future reference:  Lee: double-check when the Scala `sys.SystemProperties.preferIPv4Stack` gets evaluated
and how lazy that evaluation is.  The vague timing issue I have been trying to remember may hinge on the
fact that Scala Native needs to give an application time _after_ Scala has initialized, to set `java.net.preferMumble`.
Then the SN lazy val will return _that_ value.  I might be dreaming here,  or it might be subtle, so check carefully.
