### PR TITLE
Use opaque pointers in generated LLVM IR when possible

### LINKED ISSUE #3161: LLVM 15 breaks test-tools
LTO=thin, release-fast problems on macOS are, in some circles, well known to exist.
I report this again because the "opaque pointer removal" issue seems to be bigger than a breadbox.
Especially since "eh.cpp" comes from an external source.

Here I was seeing if the problems in year old Issue #2212 still exists in order to see if I 
could make progress on it/them and/or other Issues.

This particular run is on SN 0.5.0-SNAPSHOT, macOS (latest, 16?), M1 hardware , LTO=thin, release-fast.

I have seen this before. This time I was able to capture it.

Starting at LLVM V13.0, that group has been moving to deprecate and then disable opaque pointers.
LLVM 15.0 gives this error.  I thnk -opaque-pointers mode goes away with LLVM 16.0.

I have not seen this error using either LLVM 15 or 16 with test-runtime or test-scripted.

```
[info] Compiling to native code (2520 ms)
[error] ThinLTO: /Volumes/AngelGSdd1/lee49/DevoSdd1/ScalaNative/WorkSpace_1/2023/study_macos_testToolsFailure_I2212_2023-02-11T1820-0500/test-interface/.3/target/scala-3.2.1/native-test/native-code-nativelib_native0.5.0-SNAPSHOT_3-0.5.0-SNAPSHOT-0/scala-native/eh.cpp.o17: error: 
Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.7' Reader: 'LLVM 15.0.7')
[error] LLVM ERROR: Can't load module, abort.
```
###### Background information

test-runtime executes to completion  but the test harness does not display if LTO & releaseFast are
actually being used. Terse to the point of useless.

Note: CharSetTest fails with extra "default" Charset reported by system.

test-scripted fails in a different way, just to try my patience.  I believe the failure is because of
the Java version I am using (Java 19). When/If I recover my humor, I might try Java 8.

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #3161 

This PR adds changes to our code gen allowing for emitting opaque types. This should simplify our llvm it allowing for a bit faster compilation. Detection of the capability to use opaque pointers instead of their typed version is based on the detect version of clang. 

Removal of typed pointers and required for them bitcasts in `call`/`load`/`store`/`getelemptr` ops allows to reduce total number of bitcasts ops from 12k to ~250 when compiling sandbox project.

### CODE REVIEW

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 1]
```diff
@@ -195,14 +200,82 @@ object Discover {
...
+            System.err.println(
+              "Failed to detect version of clang, assuming opaque-pointers are not supported"
+            )
+            Unavilable
+        }
+      }
+
+    sealed trait FeatureSupport {
+      def isAvailable: Boolean = this match {
+        case Unavilable => false
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:239]:
```suggestion
        case Unavailable => false
```

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 2]
```diff
@@ -195,14 +200,82 @@ object Discover {
...
+
+  private[scalanative] object features {
+    import FeatureSupport._
+
+    def opaquePointers(implicit config: NativeConfig): FeatureSupport =
+      cache("opaque-pointers") { _ =>
+        try {
+          val version = clangInfo.majorVersion
+          if (version <= 13) Unavilable
+          // if version == 13 EnabledWithFalg("--force-opaque-pointers"): works on Unix and probably on Homebew Clang; on Apple Clang missing or exists with different name
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:225]:
```suggestion
          // if version == 13 EnabledWithFlag("--force-opaque-pointers"): works on Unix and probably on Homebrew Clang; on Apple Clang missing or exists with different name
```

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 3]
```diff
@@ -195,14 +200,82 @@ object Discover {
...
+        case Unavilable => false
+        case _          => true
+      }
+      def requiredFlag: Option[String] = this match {
+        case EnabledWithFlag(flag) => Some(flag)
+        case _                     => None
+      }
+    }
+    object FeatureSupport {
+      case object Unavilable extends FeatureSupport
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:248]:
```suggestion
      case object Unavailable extends FeatureSupport
```

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala [hunk 4]
```diff
@@ -192,8 +192,8 @@ object NativeConfig {
   /** Default empty config object where all of the fields are left blank. */
   def empty: NativeConfig =
     Impl(
-      clang = Paths.get(""),
-      clangPP = Paths.get(""),
+      clang = Paths.get("clang"),
+      clangPP = Paths.get("clang++"),
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/NativeConfig.scala:196]: These seem ok. Just wondering the reasoning.

**Review by ekrich — CHANGES_REQUESTED** [review]
Just a few things I saw.

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 5]
```diff
@@ -221,8 +221,8 @@ object Discover {
       cache("opaque-pointers") { _ =>
         try {
           val version = clangInfo.majorVersion
-          if (version < 13) Unavilable
-          else if (version == 13) EnabledWithFlag("--force-opaque-pointers")
+          if (version <= 13) Unavilable
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:224]:
```suggestion
          if (version <= 13) Unavailable
```
Missed this one.

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala (hunk 4 above)
Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala:196]: When testing this PR I've observed some failures, when detecting clang version. That happened due to some quite unexpected reasons caused by an unset clang setting. Because of that, I've gotten an error when trying to run "/home/<path-to-project>/2.13" which is a directory. It look quite strange to me, so instead I've decided to set clang on path by default. 
However, current setting is incorrect - when using clang we would try to get absolute path, which in that case would be evaluated to `currentDirectory/clang` which also is bad. I would revert this change because of that.
