### PR TITLE
Fix #1530: NIO Files.find should respect FOLLOW_LINKS option

### LINKED ISSUE #1530: NIO Files.find() should respect the value of FileVisitOption.FOLLOW_LINKS
While creating a soon to be submitted PR for Issue #1354 "NIO File Walker fails on broken links"" I discovered what I think is exactly the same issue in Files.find.

#1354 describes the presenting problem as "fails on broken links'.  That is the most
apparent manifestation of the underlying issue of File Walker, in that case, and find()
in this issue, not utilizing the value of FVO.FOLLOW_LINKS passed in.  They
always follow links, hence throwing an exception on broken links. 

The fix for Files.find is, I believe, exactly the same fix as in #1354, a simple cut & paste.
The time consuming part is creating unit-tests to show that find() can follow valis symlinks,
when the FVO option is set and not follow links when not set. 

A second test is then needed to try both cases with a broken linki. 

I did not want to clutter my PR #1354 with a lot of changes not directly on topic.

Note to future devos:  There is a bit of trickery involved in that the sense and defaults
of FVO.FOLLOW_LINKS and LinkOptions.NO_FOLLOWLINKS are inverted. The former is
used in some places while the latter is used in others.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* I am marking this one as draft until after #1531 is merged. Both PRs touch the 
    same two files. They should merge cleanly, in either order but I want to prevent
    causing extra work for others and save myself the embarrassment of merge
    failures.  Other than that and removing this note, it is ready to go. 

   * Issue #1530 reported a problem with NIO Files.find which was
    identical to the problem originally reported in Issue $1354 for
    Files.walkFileTree().  #1530 was discovered whilst fixing #1354.

    #1530 is not fixed. Code examination shows that there should
    be no other places in Files.scala with the identical defect.

    I _will_ be creating an Issue for a possible related problem,
    Files.find() with broken symlinks to files, not directories.
    I do not have enough evidence to indict there.

  * Two unit tests was added to FilesSuite.scala to exercise the
    2x2 case square of FileVisitOption.FOLLOW_LINKS present & absent each with
    valid and broken directory symlinks.

  * Almost all of this PR parallels PR #1351. That parallelism
    might draw a reviewer to expect a try/catch in Files.find() to call
    visitor.visitFileFailed(). Files.find() does not use a visitor
    so no try/catch is needed.

Documentation:

    None needed other than the title in the change log.

Testing:

  * Built and tested ("test-all") on X86_64 using sbt 1.2.6 in
    debug mode. All tests expected to pass do so.

### CODE REVIEW

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 1]
```diff
@@ -921,6 +921,114 @@ object FilesSuite extends tests.Suite {
...
+        Files.find(d1, 10, predicate, FileVisitOption.FOLLOW_LINKS).iterator
+
+      assert(itFollowGood.hasNext,
+             s"Should have found a Path when following symlinks")
+
+      // We want soughtName _exactly_ so do not use endsWith(),
+      // which would report true for, say, Foo${soughtName}.
+      val foundPath      = itFollowGood.next
+      val foundNameCount = foundPath.getNameCount
+      val foundName      = foundPath.getName(foundNameCount - 1).toString
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I think this could be `foundPath.getFileName.toString`

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 2]
```diff
@@ -921,6 +921,114 @@ object FilesSuite extends tests.Suite {
...
+      val itNoFollowGood = Files.find(d1, 10, predicate).iterator
+
+      assert(itNoFollowGood.hasNext == false,
+             s"Should not have found anything when not following symlinks")
+    }
+  }
+
+  // Issue #1530
+
+  test("Files.find respects FileVisitOption.FOLLOW_LINKS, broken symlinks") {
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: This is a good test to have.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 1 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Good suggestion.  Thank you. At that point there is at least one element to the Path, so I do not have to worry about
getFileName() returning NULL.  I'll implement as soon as I can steal the cycles.

Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Edited as you suggested. Thank you for the detailed review.

The change allowed me to simplify by dropping a now unnecessary comment
and the foundNameCount.

**Comment by densh** [comment]
Needs a pass of scalafmt to unblock the ci.

**Comment by LeeTibbert** [comment]
Rats! Fixed now, all green. Sorry for wasting your time with the bad scalafmt.

This is the final vote for my wiring my "git add" so that it runs scalafmt before _every_ commit
of a .scala file, arrgh.  I think git has hooks to do that or something similar.
