### PR TITLE
Sbt nativeLink command should fail in case of clang failure

### LINKED ISSUE #2363: Sbt should fails when scala native can't link anything
When I run `nativeLink` and it fails, the `sbt` says it success and haven't return non zero code:
```
[error] ld: symbol(s) not found for architecture x86_64
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[info] Linking native code (immix gc, thin lto) (17631 ms)
[info] Total (48158 ms)
[success] Total time: 81 s (01:21), completed Sep 9, 2021 1:24:18 PM
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
This PR fixes #2363, now in case of clang failure when compiling or linking it would throw appropriate BuildException.

### CODE REVIEW

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala [hunk 1]
```diff
@@ -131,9 +131,11 @@ private[scalanative] object LLVM {
       s"Linking native code (${config.gc.name} gc, ${config.LTO.name} lto)"
     ) {
       config.logger.running(compile)
-      Process(compile, config.workdir.toFile) ! Logger.toProcessLogger(
-        config.logger
-      )
+      val result = Process(compile, config.workdir.toFile) ! Logger
+        .toProcessLogger(config.logger)
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/build/LLVM.scala:135]: This reads very weirdly. Can you convince scalafmt to format it as
```suggestion
      val result = Process(compile, config.workdir.toFile) !
        Logger.toProcessLogger(config.logger)
```
?

**Review by sjrd — APPROVED** [review]

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala (hunk 1 above)
Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/build/LLVM.scala]: Yes, that's passible. Fixed
