### PR TITLE
Fix #3076: Compilation Support for native Windows toolchain

### LINKED ISSUE #3076: Windows fails to link sandbox, Visual Studio 2022
This is a placeholder issue. It would be nice to nice easy instructions to install Windows tools.

Previous working setup is described in the Scala Native docs using Visual Studio Community 2019 and LLVM vendored version 12.0.1.

Current library setup is Visual Studio Build Tools 2022, version 17.4.3

Scala Native HEAD checked out.

Details:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎5/‎26/‎2022
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

Windows installed Clang/LLVM
```shell
> clang --version
clang version 15.0.1
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\bin
```
```scala
[info] Checking intermediate code (475 ms)
[info] Dumping intermediate code (linked) (1301 ms)
[info] Discovered 627 classes and 4191 methods
[info] Optimizing (debug mode) (2267 ms)
[info] Checking intermediate code (109 ms)
[info] Dumping intermediate code (optimized) (550 ms)
[info] Dumping intermediate code (lowered) (834 ms)
[info] Generating intermediate code (3338 ms)
[info] Produced 36 files
[info] Compiling to native code (59069 ms)
[info] channels.ll.o : error LNK2019: unresolved external symbol _WriteFile referenced in function __SM33java.nio.channels.FileChannelImplD5writeLAb_iiuEO
[info]   Hint on symbols that are defined and could potentially match:
[info]     _WriteFile@20
[info] file.ll.o : error LNK2019: unresolved external symbol _GetLastError referenced in function __SM31java.nio.file.WindowsException$D6onPathL16java.lang.StringL19java.io.IOExceptionEO
[info]   Hint on symbols that are defined and could potentially match:
[info]     _GetLastError@0
[info] windows.ll.o : error LNK2019: unresolved external symbol _GetStdHandle referenced in function __SM40scala.scalanative.windows.ConsoleApiExt$D5stdInL28scala.scalanative.unsafe.PtrEO
[info]   Hint on symbols that are defined and could potentially match:
[info]     _GetStdHandle@4
[info] windows.ll.o : error LNK2019: unresolved external symbol _FormatMessageW referenced in function __SM46scala.scalanative.windows.ErrorHandlingApiOps$D23$anonfun$errorMessage$1L31scala.scalanative.unsigned.UIntL29scala.scalanative.unsafe.ZoneL16java.lang.StringEPT46scala.scalanative.windows.ErrorHandlingApiOps$
[info] C:\Users\ekr32456\workspace\scala-native\sandbox\.2.12\target\scala-2.12\sandbox.exe : fatal error LNK1120: 4 unresolved externals
[error] clang++: error: linker command failed with exit code 1120 (use -v to see invocation)
[error] Failed to link C:\Users\<me>\workspace\scala-native\sandbox\.2.12\target\scala-2.12\sandbox.exe
[error] (sandbox2_12 / Compile / nativeLink) Failed to link C:\Users\<me>\workspace\scala-native\sandbox\.2.12\target\scala-2.12\sandbox.exe
[error] Total time: 327 s (05:27), completed Jan 6, 2023, 8:53:01 PM
```

### PR DESCRIPTION
**Pull request by ekrich**
Default using MSVC tools compiles for `i686-pc-windows-msvc` (32 bit) so calling convention is important.

- [X] Fix compilation [WINAPI](https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170)
- [ ] Fix link symbols [Linker Options](https://learn.microsoft.com/en-us/cpp/build/reference/linker-options?view=msvc-170)

Fix for https://github.com/scala-native/scala-native/issues/3076

Setup - Visual Studio 2022 Community Edition:
```sh
> where clang
> c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang

> clang --version
clang version 17.0.3
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang
```

Potential for Github action [windows-2022](https://github.com/actions/runner-images/issues/3949)

### CODE REVIEW

File: nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h [hunk 1]
```diff
@@ -12,12 +12,13 @@
 #pragma comment(lib, "kernel32.lib")
 #include <windows.h>
 typedef DWORD ThreadRoutineReturnType;
+typedef ThreadRoutineReturnType(WINAPI *ThreadStartRoutine)(void *);
 #else
 #include <pthread.h>
 typedef void *ThreadRoutineReturnType;
+typedef ThreadRoutineReturnType (*ThreadStartRoutine)(void *);
```
Comment (WojciechMazur) [inline nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h:19]: I think we can define a no-op `WINAPI` when not using Windows and then use a single definition for easier maintenance in the future. Seems like we might need more of them in the glue layer anyway.

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h:19]: Let me check because I think this is only needed for Windows 32-bit which is the default when using the MSVC toolchain.

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h:19]: It seems that the Visual Studio 2022 compiler defaults to 32 bit which requires this extra `WINAPI` thing or it won't compile. 64 bit ignores the `WINAPI`. I still haven't managed to get the native toolchain to link but I don't think this is a terrible change as at least the code compiles. There is just 2 branches, one for Windows and one for the rest so I am not sure about what you are asking above.

I really think we should be able to compile via the Windows tools but I haven't been able to decipher the linking issue yet - lack of time and knowledge at this point.

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h]: @WojciechMazur I made an attempt to fix this like you suggested but I am not sure what type to make the typedef or perhaps `#define` might work. I will experiment on macOS to see if I can figure it out there (works on WIndows). Any suggestions appreciated.

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h]: Ok, the latest may not be 100% bulletproof but is at least workable.

Comment (WojciechMazur) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h]: Sorry for no reply previously. I was referring to `WINAPI` defined using `#define` which on non-Windows machines would be simply `#define WINAPI`. 
I believe any solution should be fine. The question is can we test it somehow? On the current GitHub Actions setup there was no issue with that so far, but I guess these error exists in local environments

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/shared/ScalaNativeGC.h]: Sure I can try that - originally I did a typedef which wouldn't work. This is just a compile error - maybe we can set up to test Windows using built in clang. Let me try some things. The main problem is the second checkbox above - the linking issues.

**Comment by ekrich** [comment]
@WojciechMazur Since this solves the compilation issue I think the way you were asking, maybe we can at least add this small change. I can then work on the link part later. Everything still works with LLVM vendored clang.

**Comment by ekrich** [comment]
Note: the Visual Studio vendored clang > 17.0.0 (protected by static assert) will compile to x86-64. Use the setting:

``` scala
nativeConfig ~= { c =>
  c.withTargetTriple("x86-64-pc-windows-msvc")
}
```

**Review by WojciechMazur — APPROVED** [review]
