### PR TITLE
Fix #1590: Correct j.i.DataInputStream EOF handling & skipBytes

### LINKED ISSUE #1590: j.i.DataInputStream has a number of correctness & performance issues
PR #1582 contains edits to java.io.DataInputStream (DIS). While preparing that
PR, I noticed a number of issues in other places in that file.

To keep #1582 focused and easy to review, I did attempt a comprehensive
fix of all subsidiary issues I encountered. Rather, I am creating this issue
so that I do not forget now that I need to do a context switch to more pending
issues.

I believe that DIS could stand a through sweep through looking for first Java API
conformance and then opportunities for improvement.

* PR #1578 created a DataInputStreamSuite.scala  unit test suite which
  covered only the two variants of readFully(). Using a mild version of
  Test Driven Design. this suite could be extended to cover all the other
   DIS methods, focusing on NullPointer & EOF exceptions, as well as correct
   successful behavior.

* I have evidence readByte() does not properly report end-of file.  I suspect other methods
  may have the same issue.

* I believe there is room for  a performance improvement by allocating a class instance
  private Array[Byte] sized 8. I have not done sandbox code here or sketched out
  an implementation, but it looked in passing as though a number of object allocations
  could be avoided on performance critical paths, for little cost in memory.

* Running & timing an improved DIS Suite before and after performance changes
  might show if guesses about performance improvement indeed improve the
  performance, if only by milliseconds.   The overhead and jitter in those files
  might overwhelm any performance benefit. Then again...

  The Java API says that these routines are not thead safe and that it is up to
  the _caller_ to synchronize. Short of a straw person implementation looks
  like an instance static buffer would not be a problem.

* PR #1578 created a DataInputStreamSuite.scala  unit test suite which
  covered only the two variants of readFully()

### PR DESCRIPTION
**Pull request by LeeTibbert**
We make a number of corrections to DataInputStream (DIS):

1) The  DIS read methods described in the Java 8 API as throwing an
   EOFException when End-of-File on the stream is detected now do so.

2) A workaround in testinterface/NativeRPC.c for the previous non-standard
   behavior of DIS#readInt is removed.

3) To make it clear that the intended read method is actually being called,
   several methods were modified to use the underlying FilterInputStream#read
   method.  To establish/maintain consistency, DIS#skipBytes was
   modified to use the underlying FilterInputStream method.

   An unintended but beneficial consequence of this change is that
   a previously unknown off-by-one error in DIS#skipBytes was fixed.

4)  A number of performance pessimizations vanished as a natural
      consequence of the changes to have  a single-point-of-truth for `EOFException` handling.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
@WojciechMazur  This PR touches some of "your" code in `testsuite/NativeRPC.scala`. May I ask
for your review of that section if you can find/create some cycles?  I think I got it right and it 
passes CI, but I always like to check with the original author, if available.

This PR deals with correctness issues.  If/when it gets merged, I hope to what I have not measured
but am pretty sure are performance issues.  This code is likely to be heavily used by people
writing applications in Scala Native.  

My networking background made me itch to fix the obvious
inefficiency of reading a series of bytes rather than 2 or 4 at once, as needed.  I deferred that work
to a subsequent PR to keep clarity of purpose for this one.  I mention this because anyone
is that code is bound to detect the pessimizations.  Since I have now touched this, I want 
folks to know that I also twigged to them, but forebeared.

Thank you for any time you are able to spend on this.

File: test-interface/src/main/scala/scala/scalanative/testinterface/NativeRPC.scala [hunk 1]
```diff
@@ -21,28 +21,23 @@ private[testinterface] class NativeRPC(clientSocket: Socket) extends RPCCore {
...
-        val msg = Array.fill(msgLength)(inStream.readChar).mkString
-        handleMessage(msg)
-        scalanative.runtime.loop()
-        false
+    val msgLength =
+      try {
+        inStream.readInt()
+      } catch {
+        case _: EOFException => 0 // leave loop
+        case throwable: Throwable =>
```
Comment (WojciechMazur) [inline test-interface/src/main/scala/scala/scalanative/testinterface/NativeRPC.scala:29]: Would it be possible to throw anything other then `EOFException` in new implementation?

**Review by WojciechMazur — APPROVED** [review]
LGTM, I'm curious about try-catch block in `NativeRPC`, maybe it can be simplified.

File: test-interface/src/main/scala/scala/scalanative/testinterface/NativeRPC.scala (hunk 1 above)
Comment (LeeTibbert) [reply test-interface/src/main/scala/scala/scalanative/testinterface/NativeRPC.scala:29]: Thank you for looking a this and your discussion/suggestions.

I have been taught that I/O can always throw some evil, and to be
prepared.

**Comment by LeeTibbert** [comment]
General note:  The first and second generations of the NativeRPC#loop code could return a -1
in some situations.  I think this may have been the cause for some unexplained and
some undecipherable "code 255" errors I was getting in some places.

**Comment by LeeTibbert** [comment]
Do we have any idea where the NativeRPC#loop() code came from?  It looks like it was
written for Scala Native, perhaps in the Summer of 2020?

**Comment by WojciechMazur** [comment]
> Do we have any idea where the NativeRPC#loop() code came from? It looks like it was
> written for Scala Native, perhaps in the Summer of 2020?

Testing interace was ported then from Scala.js. NativeRPC#loop() probably comes from one of Scala.js `XEnv`.

**Comment by LeeTibbert** [comment]
NativeRPC#loop() is offered as a "better than what went before" rather than as an example
of crystalline perfection.   I tried to do the best I could do within the constraints of prior art
and the extremely limited time I have available now.

1) The normal and expected case of End-of-File should not be handled by Exception.
    

2) Reporting all errors by Exception is sub-optimal (rant deleted).

3) The -1 that was being bubbled up to TestMain, which reported it to the shell was causing 
     a incomprehensible error message being displayed in sbt.  That is, a clean and comprehensible
     error was not being transmitted up the call chain to an end user trying to figure out what went 
     wrong.  Always reporting 0 is a hack, but a hack that gets one through the night.

4) The code ` val msg = Array.fill(msgLength)(inStream.readChar).mkString` 
    is functional but can potentially cause a __large__ number of I/O calls.
    (rant deleted).  There are known techniques for doing doing a 
    smaller number of reads and building up the desired string in a
    StringBuilder (which can be allocated to the known end size).   

    This code is frequently executed by developers and is also
     executed on every CI.  IMHO, it is worth spending a few
     hours making it more efficient. Functional code can
     have good performance.

**Comment by sjrd** [comment]
Scala.js uses the native JavaScript event loop. It doesn't have any explicit `loop()` like this. `NativeRPC` is very different from the corresponding [`JSRPC`](https://github.com/scala-js/scala-js/blob/v1.4.0/test-bridge/src/main/scala/org/scalajs/testing/bridge/JSRPC.scala).
