### PR TITLE
UnixProcessGen1: monitor in GenericProcessWatcher

### LINKED ISSUE #4560: javalib UnixProcessGen1 ProcessMonitor may now be a candidate for removal
Prolegomena:

1. I am looking at committed Git code.  There may be a plan in process to remove it.

2. UnixProcessGen1 bears the seal of the Curse of the Mummy. That seal has recently
    been broken by a bold adventurer. We might as well go for it.

Concern:

It looks to me like `UnixProcesGen1` now involves both its original `ProcessMonitor`
and the `GenericProcessWatcher` from recent work, starting with PR #4478.

This may be an artifact of "Sorting through too much cruft, haven't gotten to that 
simplification yet".

When the dust settles, it looks to me like the `ProcessMonitor` code could be 
bypassed in favor of `GenericProcessWatcher. If that works out, both the Scala and
the C code could be removed after a decent interval.   

That `ProcessMonitor` code has been well behaved, jinx, for the past year or more
but historically it has been problematic.

### PR DESCRIPTION
**Pull request by kitbellew**
Since Gen1 doesn't support pidfd_open, we can either use the heavier `waitpid()` (on specific pid) directly, or repeat what process_monitor does (i.e., `waitpid()` for any child process).

Let's add the option of reaping any children in process watcher and remove process_monitor.

Fixes #4560.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Bold.  Bravo!

I believe that `waitpid(-1, mumble)` introduces a problem.  The TL;DR is that
POSIX has had `waitid()` since at least 2004.

I believe that `waitpid(-1, mumble)` will transitively await the children of children: i.e 
grandchildren and on down the line.  

If true, as a thought experiment, consider the case where a child expects to be able to obtain
 the exit value of its own child.  The grandchild exits, GPW detects that and reaps the grandchild's
exit value.  I believe that exit value & asssociated info is no longer obtainable (on Linux, perhaps
it is available on the more generous macOS) by the child.  I seem remember spending way more
time that I liked either then or now chasing "No such process" errnos when a process tried to
`waitFor` a reaped process.

There may be a solution, albeit ugly.  I hope to change GPW to be event driven once this
series settles, so ugly may be useful in the short to medium run.

I have not implemented it but `waitid()` may be available.  The difficulty is that not only
the function needs to be available, but it must accept the `WNOWAIT` flag.


 Within the bounds of a few minutes of Googling, POSIX seems to be silent about
that flag.  I can search more once I have surfaced this idea.
`#define _XOPEN_SOURCE_EXTENDED 1`

Linux since the horizon seems to have it, as do FreeBSD and IBM (not supported
by SN). ChatGPT thinks macOS since the horizon has that flag, take with shaker of salt.
I have not checked my macOS system.  


HACK ALERT! sensitive & sensible developers may want to divert their eyes.

The idea would be to `waitid()` for any child using the WNOWAIT or'ed into existing flags.
 When that wait completes, see if the pid in the mumbleInfo block is in the hash table
(i.e. one we are watching).  If not, ignore it and loop again. If yes, call the current name
for the method formerly known as `checkIfExited()` (or such).

The former case will leave the hypothetical grandchild exit info available to, say,
a child  either a simultaneous  or later `waitFor()`.  
I'd have to think through if such  `waitFor()`s would get notified. I would expect the
latter to work, would need to do a scratch study for the former.

In the `can not get object monitor` case, GPW may need to `signal(SIGCHILD)` the
child directly. GPW should have the pid at hand, it was just the hash table key.

Complicated & bug prone enough?  Perhaps my description of ugly can prompt
you to a better solution, or at least supply the pig with lipstick & a pretty bow.

<hr ...\>
IIRC, our current `ProcessHandle` does not track transitive children.  No ready solution there.

<hr>
It could well be that the long standing UnixProcessGen1 ProcessMonitor has the same issue.

File: javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+  def register(handle: GenericProcessHandle): Unit =
+    processes.put(handle.pid(), handle)
+
+  def get(pid: Long): Option[GenericProcessHandle] = Option(processes.get(pid))
+
+  def completed(pid: Long): Unit =
+    processes.remove(pid)
+
+  def claimCompleted(pid: Long): Unit =
```
Comment (LeeTibbert) [inline javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: `GenericProcessRegistry` seems like a good clean idea.

Later: OK, I see now that line 31 in `GenericProcessRegistry` removes the key

~~~
The 'computeIfPresent' action can not, per JDK, modify the map.  It appears that 'UnixProcessWatcher' never
calls a '.remove' method.

How does the key eventually get removed from the map?
~~~

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: i thought that if computeIfPresent returns null, the key must be removed. no?

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: yes, that's what it says: https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfPresent-K-java.util.function.BiFunction-

**Comment by LeeTibbert** [comment]
A concept to put on the back burner, when you run out of today's joys. It might be stale by
the time I finish writing it down. The again, you may well discard the approach, no harm here.

I'll use the term "GenericProcessMonitor" or GPW because that is what was operative when
I was working this out.  I see that names and implementations have changed today. 

The overall objective is to ensure that GPW never blocks  because another thread is holding the 
object synchronization monitor.  This means that any hard blocking has to be in the thread
being monitored.  I think that isolates hangs.

The idea would be to make the current `synchronized` blocks use a common, proper 
`ReentrantReadWriteLock`.  ~~The major benefit is that it would remove my fingerprints on that 
code and replace them with yours.~~  

Then (the current name of) `checkIfExited` would change to use `ReentrantReadWriteLock.WriteLock.tryLock()`
as its middle term (perhaps the middle and last term can become, with proper precedence parentheses) an &&
so the second Future look only happens if the lock is obtained).

The try() is non-blocking.  
  * If the lock is obtained, then a current `waitfor` path can be executed (yes,
   that path should change in a better Evolution, but for the sake of discussion, lets keep it as-is for now).

  * If the lock can not be obtained, that means that some other thread is already in a `waitfor`.

The corresponding change is each current `waitFor` synchronized block to use newly introduced
common lock. 

From some earlier private design sketches, I believe the `waitFor(pid, timeout)` method goes easier
if the lock is not obtained until the method which does the os wait (askZombiesMumble??
someday, that method could probably be renamed to 'reapProcess' or such.)

I'd have to think it through and probably do a trial implementation, but  I think the 'tryLock()`
analysis holds here also.  If some other thread holds the lock, no sense blocking, let it
finish the job.  

I believe the JVM descriptions allow some latency between when the `waitFor()`
completes and when the exitValue is available.  A first implementation could do
a hard block to avoid that messiness, and then attempt the 'tryLock()'.  That is
complete Calculus 1 before attempting Calculus 2.

My goal is to reduce the number of ways and likelihood of the remaining ways
that GPW can hose us.

File: javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: JDK [ConcurrentHashMap] (https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html#computeIfPresent(K,java.util.function.BiFunction]

Especially the line `The remapping function must not modify this map during computation.`

Yes, the JDK 8 example clearly removes the key.

I can write a sandbox program to see what JDK 8 & 25
actually do. 

I can also check what SN `ConcurrentHashMap` code
actually does. IIRC, that code is ported from Doug Lea et al. Oswego JSR-166 code.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: It looks like the JSR-166 SN `ConcurrentHashMap`
_does_ remove the key.  

I did not write a trial program. I recently ported the Doug Lea JSR-166 unit-test for that class. My next step is to see if this path is tested. 

I suggest a one line comment stating that the key
will be removed on null.  

Agreed, not necessary, but it will warn off people like
me to read and believe current JDK documentation.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]:
```
grep -i "compute" *MapTest*
...
ConcurrentHashMapTest_JSR166.scala:  @Test def testReentrantComputeIfAbsent(): Unit 
```

No `computeIfPresent()` test there.  As ancillary work
I could take a run at adding such to increase confidence
that something on which we are relying actually works.

I think I have written such a `computeIfPresent()` test before. I'm off to find it.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: And you wonder why I have guarded confidence in the 
SN unit-test ensemble ;-)

It is getting better every day, but I follow the old
Russian advice: Trust but verify.

Especially when I am 20 levels deep in gnarly code.

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: > Especially the line `The remapping function must not modify this map during computation.`

it should not directly modify the map but it can return null so that the map can modify itself 🙂

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/GenericProcessRegistry.scala]: Turns out the the SN suite is more comprehensive
in this case than the JSR test.  I'm astonished and
owe the SN suite an apology.

It is not evident, but on tracing the long standing
`ConcurrentHashMapTest.scala` extends  the
`javalib.util.MapTest` derived from Scala.js. `MapTest`
does have a case for `computeIfPresent` & that case
exercised key deletion.

Final result:  it should be safe to rely upon CHM removing
                    the key (but still deserves a comment).

**Comment by ekrich** [comment]
What is the history of `UnixProcessGen1` and `UnixProcessGen2`? 

Are these planning to be one at some point or do they exist because of the runtime threading modes?

**Comment by LeeTibbert** [comment]
I believe they exist because reasonably recent, at the time of implementation of Gen2, versions 
of macOS and Linux had operating system functions implemented which did away with the the
vastly expensive & problematic `ProcessMonitor`. 

Like building a new bridge across the bay aside the old bridge so that people can continue
to use the old bridge whilst the new bridge is built and qualified, I cloned Gen1 into Gen2. 
That gave me  some freedom to make large scale edits in Gen2.  

I am reasonably confident in my work before I submit it as a PR, but I always
hate the idea of breaking existing users.  Introduce a feature or improvement and then let
people opt in and put some mileage on it. Is kilometerage a word?

Some of the ~~cruft~~ questionable implementation detail got cleaned up in Gen2
over several iterations.  Limits on time & available effort means that a lot got left behind.
Unfortunately, like cleaning up the Augean stables, clean up the top few layers and they are many more 
underneath. Then along came multi-threading and many  hasty attempts to 'fix' code that was never designed
to be multi-threaded.

I believe that at some point WindowsProcess was created based on one or the other
of Gen1 or Gen1.  I really can not speak to the Windows code.

The current work is less hesitant that I was to make major changes in Gen1.  It unifies
several code paths.  IMO, by the end of the series the code should be much more maintainable.
One will no longer need to triple glove before venturing into that code.

There is still some `waitFor` unification I want to do in Gen2, but not while the wheels are still
in motion.  

Now that UnixMonitor is provisionally split off, it will be easier to make that event driven.
The ppoll and kqueue code in the Gen2 waitFor provides a template.  That should be
good for a thousand or so processes monitored at one time.  Down the line, we will probably
need to implement multiple monitors, where each handles a thousand or so processes and
exits when it has no more processes to monitor.  That approach suffers from some problems
similar to garbage collection, where one long running process keeps a monitor thread alive for days.

The benefit is that it uses far fewer of the limited number of fds (os file descriptors) than the
alternative of having each Process be its own watcher.  The exit completion handler requirement
introduced in JDK9 did us no favors.

I believe the current state of this PR is getting a believable and reliable ProcessMonitor
implementation.  It seems that because of a particular programming style enabled by
JDK9, we can not economically eliminate such a Monitor/Watcher.

The original motivation was, I think to address some hard to trace but 
frequent Windows hangs. Then came a period when the X86 32 bit CI run was hanging.
Not easy days but, I think, still a work in progress.  The way we learn is by trying things out.

The recent work to get `os-lib` `SubProcess` tests to work, first at all and then reliably also introduced
a series of changes.

Bon courage, @kitbellew

PS: @ekrich I seem to remember that at some point you were involved with fixing/rescuing
      ProcessMonitor (cpp?) code.

File: posixlib/src/main/resources/scala-native/sys/select.c [hunk 2]
```diff
@@ -29,7 +29,7 @@ typedef long int suseconds_t;
 // Being robust to such a change is well worth the code smell of this
 // large block comment. Miserere mei peccatoris.
 //
-#error("Probable size mismatch with static fd_set type in select.scala ")
+#error ("Probable size mismatch with static fd_set type in select.scala ")
```
Comment (LeeTibbert) [inline posixlib/src/main/resources/scala-native/sys/select.c]: Another catch of a 6 year old defect. It is good to have eyes on this code.

I believe contemporary usage would be to drop the
parentheses altogether and have `#error "<existing text>".

Not the highest priority, but as long as the code is
changing.

I think that there have been no compiler complaints
over that period because FD_SETSIZE has always been
<= 1024, so that block never got entered.

Based on this detection, I did a due diligence search of the SN codebase .c, .h, .cpp, & .hpp files and this was
the only place I made that error.

Comment (kitbellew) [reply posixlib/src/main/resources/scala-native/sys/select.c]: that was not me but clangfmt which, apparently, works differently depending on version. i can't figure out how to format the new C code so that github actions clangfmt doesn't complain :(

Comment (LeeTibbert) [reply posixlib/src/main/resources/scala-native/sys/select.c]: re: clangfmt

Now that is aggravation you probably do not need, on  a Monday or ever.

I consulted my local LLM and it suggested that for a Draft PR with more pressing issues
needing attention you could comment out that in `scripts/check-lint.sh`.  Of course I replied
"What an abominable, despicable  hack!" 

I believe that CI is using clang-14 on Ubuntu linux.  An rough-and-ready alternative might be 
to hack `check-lint` `scripts/clangfmt --test`  to `scripts/clangfmt` and let it do what it wants to do.

That might help you focus on the main chance.

@ekrich  You tend to be, for the better, the game warden of proper formatting.

Any objection to my/our permanently modifying `check-lint` to use a more current 
clang-fmt?  Of course, there is probably somewhere where we document minimum
required clang version.  I think that is now something like clang-17.

Thanks, gotta run, obligations today.

**Comment by ekrich** [comment]
I think the github action pulls a particular version of `clang-format`. This was set to update some weird code in the script to check if it make changes since the older version didn't do that. We try and have some minimum `clang` version so we don't want the formatting all over the place since it usually comes with the version.

https://github.com/scala-native/scala-native/pull/2589

Apparently the newer versions changed some thing so maybe this should be bumped to the version that made the offending change.

**Comment by LeeTibbert** [comment]
Thanks for the rapid & helpful reply. I suspect that the clangformat-14 came from that being
what was batteries-included in the Ubuntu (20-mumble?) at that time. The Ubuntu
version changed to 22.mumble awhile back.

I'll try to sort this out tonight or tomorrow morning.  If kitbellew tripped over it,
somebody else will too (and I don't have the spare patience for it to be me).

**Comment by kitbellew** [comment]
> Apparently the newer versions changed some thing so maybe this should be bumped to the version that made the offending change.

Oh those annoying opinionated-formatter perfectionists, keep fidding with stuff for no good reason :)

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala [hunk 3]
```diff
@@ -1,11 +1,12 @@
 package java.lang.process
 
-import java.io.FileDescriptor
+import java.io.{FileDescriptor, IOException}
 
-import scala.scalanative.libc.{signal => sig}
+import scala.scalanative.libc.{signal => libcig}
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/process/UnixProcess.scala]: These might be better as `csignal` and `psignal`

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala]: will do. for now, i am still trying to get it not to fail.

**Comment by LeeTibbert** [comment]
> for now, i am still trying to get it not to fail.

Reminds me fondly of many a long night in University. Especially while taking the "Building a Compiler"
course.  I think that is where I learned about unit testing and gained a keen appreciation for its value.

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala (hunk 3 above)
Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala]: done in #4584.

**Comment by LeeTibbert** [comment]
Congratulations, you got this working.  Probably been a long two days for you.

From a quick look at the code, it looks like it works because it is implemented
and not because tests were bypassed.

File: .github/workflows/run-tests-macos.yml [hunk 4]
```diff
@@ -31,7 +31,7 @@ jobs:
       - name: Prepare for GC tests
         run: brew install bdw-gc
       - name: Test GC compilation
-        timeout-minutes: 30
+        timeout-minutes: 45
```
Comment (LeeTibbert) [inline .github/workflows/run-tests-macos.yml:34]: At least one of your yesterday/today PR seem to 
work better with the increased timeout.  To my thinking
that means that the issue has more to do with macOS
runs slowing down on GitHub, possibly because of some
cost related changes there.

The increased timeout-minutes costs us little until it is spent. It has the potential to save developer time & frustration. I know that I have spent time over the past
several days looking at macOS run log files that timed-out.

I call this out to make the hypothesized cause of the 
change clearer to other reviewers.

File: javalib/src/main/scala/java/lang/process/UnixProcessGen1.scala [hunk 5]
```diff
@@ -2,91 +2,56 @@ package java.lang.process
...
-       * currently does, that could easily change with future maintenance
-       * make it no longer compliant, leading to shrapnel & wasted
-       * developer time.
-       */
+    UnixProcessGen2.forkChild(builder)(new UnixProcessHandleGen1(_, _))
+  }
 
-      ProcessMonitor.notifyMonitor()
+  def waitpidAny(): Boolean = {
+    // no choice but to reap a child, whether it's ours or not
```
Comment (LeeTibbert) [inline javalib/src/main/scala/java/lang/process/UnixProcessGen1.scala:62]: I believe this is what I called "reaping a grandchild 
so that its exitValue is not available to its parent"

From your comment in the base issue, it seems that
this is long standing behavior from the replaced 'process_monitor.c'.

I suggest expanding the comment just a tad to
add the something like:
```
Preserve long standing prior behavior of potentially 
reaping a granchild or other descendent early and making
its exitValue unavailable to anyone.
```

You may be able to come up with better wording.

The advantage of this change would be that it clearly
describes the defect and the `No choice`.  It lets you 
shed any onus. 

To the best of my knowledge, no one has ever reported
tripping over the `grandchild` problem, but that does
not mean that it has not been encountered.

Probably neither of us want to invest much time in Gen1
code, so leaving a clue to our future selves when somebody does trip over the limitation after all these
years may pay off.

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/UnixProcessGen1.scala:62]: added scaladoc

**Comment by kitbellew** [comment]
> What is the history of `UnixProcessGen1` and `UnixProcessGen2`?
> 
> Are these planning to be one at some point or do they exist because of the runtime threading modes?

@LeeTibbert I'm asking myself the same question. in gen2, instead of waitpid, the code does ppoll/kevent on a single pid, followed by waitpid. i would understand it if the poll was on many pids, but it isn't. how's this better than just a waitpid on a pid? which is what gen1 can do as well...

**Comment by LeeTibbert** [comment]
@kitbellew @ekrich 

I'll try to be shorter and not my usual loquacious self
when it come to detailed topics. I mean no offense.

We and this code have been thru a lot of change in the past two months. Change
probably but not yet proven to be for the better.  We/it has transformed from point 
A -> B -> C -> ... -> L -> M -> N.  It makes entirely good sense to begin asking the 
question: given where we are at point M and what we can learn in economic time,
what is a good  set of possible paths ahead and what are our selection/decision criteria.

I'll give you my take/suggestion.  I am not against such a merge eventually, where 
eventually is a small number of months.  I do concur that it is time to see what
the view from point L offers.   A precipitous change tonight or, given the magnitude
of the effort, tomorrow night would, IMO, lead to regrets. 

I am suggesting pacing for an ultra-marathon, not interminable delay.

1. Let the the 'no synchronized blocks' PR merge and settle.

2. Let this PR merge and settle, reasonably as is.

3. Stress test the above. Yes, a tedious and inglorious phase, but one which
    helps developers using SN to stay happy with it.

    All of these projects are known to have revealed defects in SN.
    Yes, any defects revealed are, hopefully, not in this code or evolutions of this code.

    1. Run the `os-lib` `Subprocess` stress tests for 5 K or so iterations.

    2. Run a scratch `scalafmt` snapshot test 
      1. once
      2. with dueling formatters, for 100 iterations or above

    3. There is an Issue with `kyo` tucked away at the bottom of
        an old `kyo` SN Issue.  I have asked that a formal Issue
        be created so that we can track that issue.  The raw report
       is of a hang using SN. If timely investigation proves it to be an SN
       defect that gives us a data point. If the `kyo` code in question
       no longer hangs with this SNAPSHOT, that increases our confidence.

      `kyo` exercises large parts of `zio`.  At a first pass, that leaves
      the Typelevel projects as not pre-qualified.

      I am somewhat describing/dreaming_of a manual Community Build.
      Yes, such work could be done with some thought of how such could
       be automated but that should not delay the current work or cause
       yak shaving.
   
4. Possibly in parallel with step 2, do a sandbox design study 
    of making the GenericProcessWatcher event driven (more
    about event driven in another reply. I think this step is
    critical to allowing an eventual merge.

   1. My rough guestimate is that this probably takes three long
       days to implement and a week to prove out to alpha quality.    

    2. I suspect that the number of threads actually being Watched
        can be drastically reduced, at least on the Gen2 path.

5. __After__ a Watcher is event driven do a sandbox design study
   to see if Gen1 & Gen2 it makes sense to unify Gen1 & Gen2.

   There has been enough change that I suspect it makes sense
   to at least do a trial implementation after an event driven Watcher.

6. Whilst all of the above is in a strong beta test do some benchmarking
    looking for hot spots.
  
    1. I know that the `completion` `Future` is a signature
        and defining feature of the current work. I also suspect that 'hot' 
        parts of it can be replaced by something which does not require
        frequent thread context switches; say an AtomicMumble. 
    
   3. I also suspect that experience will show that the 3(?) 'close I/O' threads
       can be collapsed into at most one.  They seem to be working now, so
      let them be until we and those who use SN get some experience & confidence
      in the current checkpoint.

I'll let this question rest on my back brain whilst I complete some promises I have
made.

**Comment by LeeTibbert** [comment]
By my understanding, there is a basic difference between the Gen1 and Gen2 models.

Gen1 is polling/Watcher driven, possibly strongly influenced by the Java doc
about polling and skipping the part about "urging subclasses to do a more efficient implementation".
Implementation cycles were limited at that time, there was a lot of framework to establish.

Gen2 is event driven. We were having a hellacious  time with the, then C++ code jamming up.
A lot of development time when into chasing and never quite finding those hangs. Event driven
was/is not a panacea but there are many cases where it is more efficient than polling.

The JDK 9 `Process` `onExit` changes seem to have introduced the need for some form of 
polling.  

As mentioned before,  Gen2 was cloned (yeah, a code smell, like driving past the St. Pete landfill)
and altered to take advantage of being event driven and of some os features which made that efficient
while also not breaking Gen1.  

one shot 'ppoll()` and `kqueue()` allowed doing a fast,  near real time responsive,  os-interruptable event driven 
wait with timeout where the os handled signal exclusion and timeouts.  I thought & think that the os can do a 
better job with those than I could/can. 

An event driven Watcher could and, indeed, should ppoll/kqueue on multiple pids/kevents.  Achieving that
means that I will have to notify my local electric utility that my usage will be going down so they will have
more power for AI.

In designing & sandboxing, I believe we can implement early evolutions using a single Watcher.
As mentioned in other places, I do think that the at least rough design should not preclude a
later multiple Watchers. Get the 1K scale working and a glimmer of what a 4 or 10K design
would look like working before investing too much time in the 4K complexity.  I have also 
mentioned that I suspect that there may be a way to reduce the number of threads watched
in the `Gen2` case, where "Can/should I/we unify Gen1 and Gen2" is kept as a background
design consideration.

I suspect that early evolutions of an event driven Watcher will succeed earlier if they do not remove
the current on-shot ppoll/kqueue paths in Gen2.  A later evolution may well be able to remove
that restriction.  Will it be more efficient, especially at scale, to have a Watcher which handles
all the child-exited events and sets a completion which the replacement code checks, I do not
know.  Time comes, we need to develop more evidence.   

I believe that another PR introduces a persistent instance level kq and possibly kevent.  There 
already is such for Linux pidfd.  Given those changes, the cost of 'onshot` ppoll/kevent goes
down.  I suspect, but do not yet know, that timeout handling and being able to reduce the
overall number of processes watched will lead to a probably altered 'one shot' scheme
being retained.  That is why I do and advocate for rapid prototype design studies and,
given learnings from them asking: What are my decision criteria and how do these
learnings transit that  decision tree?  What are I/we gaining? losing? How can I/we
leave bread crumbs for the next generation (or ourselves in 6 months).

It is good to have at least a community-mental sketch of at least the next
two steps in the relay.  With enough people, it is always nice to have at
least one doing preliminary design & rapid prototyping of each of those
steps.  

Given available resources, I think that being able to present the current 'reach'
set of PR to users of SN and being able to say: Look, we can not say that we
introduced no defects, but we did a due diligence pass and here are the applications
which seem to work. 

Have I said yet that the Watcher should be event driven?

**Comment by LeeTibbert** [comment]
Thank you for the 'grandchildren' & 'no worst than prior practice' (my words, not the kinder actual ones)
notes.

**Comment by LeeTibbert** [comment]
I think there is a 6 hour max timeout somewhere in the build. 

Still the 45 minute cap is an improvement. If they do not complete in that
time we know we are hosed.

FYI:

On one or both of the multiarch tests, I think the linux_arm64, used to take slightly more
than an hour.  Last run in this PR took 21ish minutes.   The X86 variant has gotten
two minutes or so faster.

Some of the variance may be do to CI load variance.  I do think however that the 
vastly improved execution times of the multiarch tests is not a co-incidence or fluke.
I think it is happening in spite of baseline CI taking longer.

**Comment by kitbellew** [comment]
@WojciechMazur this one is finally ready to go.

**Comment by WojciechMazur** [comment]
> I think there is a 6 hour max timeout somewhere in the build. 

The 6h is the default GH Actions timeout AFAIR 

> Still the 45 minute cap is an improvement. If they do not complete in that
time we know we are hosed. 

Last time I've checked the logs with enabled timestamps there was no logs done in the last 20 minutes of the build before timeout, so I'm not sure it would help us anyone, but let's try.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
@ekrich @kitbellew 

PR #4576 is no longer draft.  GitHub seeks to think you have requested changes.  
Is that request still active?  Did it get addressed or did the request go dangling
because of read-only permissions?

Reason that I ask is that I suspect that request is no longer valid but is
holding up merging.  Then again, the request may still be valid and
GitHub is doing its job.

Thanks,

**Comment by kitbellew** [comment]
> @ekrich @kitbellew
> 
> PR #4576 is no longer draft. GitHub seeks to think you have requested changes. Is that request still active? Did it get addressed or did the request go dangling because of read-only permissions?

The change @ekrich requested was merged in #4584 (naming of the two signal imports, one from libc and other from posix). There are no more outstanding blockers.

**Comment by LeeTibbert** [comment]
Congratulations on getting this merged.  

It was a lot of work but ended up with, IMO, a much better product.
