### PR TITLE
Fix #314

### LINKED ISSUE #314: Code gen emits invalid LLVM IR
Following code

```
object Main {
  def main(args: Array[String]): Unit = {
    try {
      5 / 0
    } catch {
      case err: Throwable =>
        println("catched")
    }
  }
}
```

Emits invalid LLVM IR:

```
[info] Compiling 1 Scala source to /Users/Denys/.src/native/sandbox/target/scala-2.11/classes...
/Users/Denys/.src/native/sandbox/target/scala-2.11/sandbox-out.ll:2927:30: error: use of undefined value '%src.10'
  %src.5 = phi i8* [%src.11, %src.10], [bitcast (%"class.module.scala.scalanative.runtime.BoxedUnit$"* @"scala.scalanative.runtime.BoxedUnit$" to i8*), %src.6]
                             ^
```

As reported by @andreaTP in https://github.com/scala-native/scala-native/issues/273

### PR DESCRIPTION
**Pull request by densh**
As per @pbatko suggestion. Doing another DCE late in
the pipeline is enough to clean up unused code that
produces control-flow information that LLVM doesn't like.

### CODE REVIEW

File: unit-tests/src/main/scala/scala/scalanative/issues/_314.scala [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package scala.scalanative.issues
+
+object _314 extends tests.Suite {
+  test("github.com/scala-native/scala-native/issues/314") {
+    // Division by zero is undefined behavior in production mode.
+    // Optimizer can assume it never happens and remove unused result.
```
Comment (densh) [inline unit-tests/src/main/scala/scala/scalanative/issues/_314.scala]: The plan is to have two modes: one that does all the checks (development) and one that doesn't (production). You as user will be able to choose which one works better for you. https://github.com/scala-native/scala-native/issues/14
