### PR TITLE
Fix #1830: Mangle identifiers starting with digits in way that is injective

### LINKED ISSUE #1830: Can't compile when call a function that used an identifier that starts from a digit
I'm trying to use scala-native to build a software that contains a bit greek symbols inside scala code. Why? Because it is a math and to stay with original article I've used it :)

Unfortunately when I've tried compile it, everything was fine on stage of producing NIR and publishing an artifacts.

But when I've tired to compile a native binary, compiling is crashed with stack trace bellow.

To achieve that I need to call a function that is using (inside) something with unicode identifier.

At my case it was easy to fix, but if some 3rd party library would like to do so, it will be painful.

I'm using scala-native 0.4.0-M2.

BTW scalac and scala-js, both, supports it without any error.

```
[error] java.lang.StringIndexOutOfBoundsException: begin 3, end 45, length 35
[error] 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3720)
[error] 	at java.base/java.lang.String.substring(String.java:1909)
[error] 	at scala.scalanative.nir.Unmangle$Impl.readIdent(Unmangle.scala:145)
[error] 	at scala.scalanative.nir.Unmangle$Impl.readUnmangledSig(Unmangle.scala:28)
[error] 	at scala.scalanative.nir.Unmangle$.unmangleSig(Unmangle.scala:7)
[error] 	at scala.scalanative.nir.Sig.unmangled(Sig.scala:26)
[error] 	at scala.scalanative.nir.Sig.toProxy(Sig.scala:9)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachAllocation$8(Reach.scala:266)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] 	at scala.scalanative.linker.Reach.reachAllocation(Reach.scala:264)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachOp$3(Reach.scala:532)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachOp$3$adapted(Reach.scala:532)
[error] 	at scala.Option.foreach(Option.scala:407)
[error] 	at scala.scalanative.linker.Reach.reachOp(Reach.scala:532)
[error] 	at scala.scalanative.linker.Reach.reachInst(Reach.scala:474)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachInsts$1(Reach.scala:468)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachInsts$1$adapted(Reach.scala:468)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.scalanative.linker.Reach.reachInsts(Reach.scala:468)
[error] 	at scala.scalanative.linker.Reach.reachDefine(Reach.scala:397)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:113)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachDefn$2(Reach.scala:94)
[error] 	at scala.scalanative.linker.Reach.$anonfun$reachDefn$2$adapted(Reach.scala:90)
[error] 	at scala.Option.fold(Option.scala:251)
[error] 	at scala.scalanative.linker.Reach.reachDefn(Reach.scala:90)
[error] 	at scala.scalanative.linker.Reach.process(Reach.scala:82)
[error] 	at scala.scalanative.linker.Reach$.apply(Reach.scala:673)
[error] 	at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error] 	at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error] 	at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error] 	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error] 	at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error] 	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:53)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$11(ScalaNativePluginInternal.scala:145)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:220)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:145)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (cliNative / Compile / nativeLink) java.lang.StringIndexOutOfBoundsException: begin 3, end 45, length 35
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1830 
Partially imported fix for mangling identifers starting with digit from ScalaJs fix https://github.com/gzm0/scala-js/commit/2bed3a2fd7c10da7978453c0b4c2aec7a403e6ba

When identifiers starts with digit or `-` it's mangled identifier name is prepended with `-`

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Wojciech.  Nice to see another contributor to Scala Native.  

I believe that the proposed change should trigger a change to the NIR version.
I believe the proper change is to change the NIR major version (a different name
is used in the code). That causes problems with existing libraries and should probably
not be done until just before 0.4.0-M3 or the next release.

 It might be possible to get away with changing only the
minor ident by arguing that '$' is reserved to compiler
generated code so no user code before this PR should have
ever validly used an identifier starting with '$".  I believe that
it is known that the SN compiler never historically generated
such, there will never be a valid case which should have
triggered a major ident mismatch.  Twisted logic, but saves
the use of existing 0.4.0-M2 libraries.

I think I am correct, but you might want to wait for an umpire's call
before sinking time into a change.

I believe that the six or so week old Reflection PR by @errikos is a 
working example of changing the minor ident.  That is, it gives the 
file involved.  I think the change here is much simpler, just a one or two
character text edit. If such a bump to the minor ident is recommended by a knowledgeable reviewer and
you do not feel like diving deeper into the NIR internals, I can send you or post here the suggested edit.
I am not trying to make the review process onerous.

**Comment by LeeTibbert** [comment]
I've been studying Issue #1830 for a while now. I did not suggest the 
fix of this PR because I believe that #1830 reveals much larger
problems with both the content and length of backquoted identifiers.

This PR should make progress while the larger issues are addressed.

**Comment by LeeTibbert** [comment]
I am grateful & heartened that there are test cases for this change at all.

Adding test cases for ``$`` or ``$3foo`` so that both branches of the `or` in the mangle/unmangle code
are exercised would be an improvement.

File: nir/src/main/scala/scala/scalanative/nir/Mangle.scala [hunk 1]
```diff
@@ -127,6 +127,7 @@ object Mangle {
 
     def mangleIdent(id: String): Unit = {
       str(id.length)
+      if (id.head.isDigit || id.head == '$') str('$')
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/Mangle.scala:130]: So concretely, the problem was that the mangling for something like `id = "3foo"` was `43foo`, which was interpreted as a length of `43` and then not enough characters afterwards. Another way to say it is that the encoding was not injective.

Clearly the solution proposed here solves this issue in isolation, but I agree with @LeeTibbert's concerns over backward compat of the IR. I don't think we need to bump the minor IR version *once more*, since we have not released a public version (against which libraries would then be compiled and published) since the last bump. However, we should make sure that we can still read IR that was built by 0.4.0-M2.

`$` is too common a character; it is generated by the compiler for special characters, so an identifier like `+` is already mangled as `$plus`. We could however use another character that is never emitted by scalac under any circumstance. I suggest to use the character `-` for this purpose. Indeed, if an identifier contains a `-` in user-space, scalac encodes it as `$minus`, so at this point in the pipeline, `id` never contains a `-`. And `-` is a nice separation character: it would produce `4-3foo` for the example above.

If you try `-`, either it works and we're happy, or it crashes later because `-` would not be a valid ident for LLVM somewhere inside. In that case we'll have to think more.

Comment (WojciechMazur) [reply nir/src/main/scala/scala/scalanative/nir/Mangle.scala]: It works out well with `-` symbol instead of `$`. 
One thing I've noticed there was NIR file generated with name `DigitIdentifiersSuite$1Test$$minus1.nir` for ``` sealed trait `-1` {...}```. I'm not sure can it cause some problems in future.
