### PR TITLE
Fix #2750: 0.4.x two javalib entities now throw expected Exceptions

### LINKED ISSUE #2750: Write-opening a read-only file doesn't throw an exception
I added a test for this in https://github.com/scala-native/scala-native/commit/0847cfa75241272bd3d6917ee44340bbce6ebd9d. It passes on JVM and fails on Native.

### PR DESCRIPTION
**Pull request by LeeTibbert**
##### Administration
This PR is submitted for the 0.4.x train.  

It is applicable to 0.5.0. Do I need to do a separate PR for 0.5.0, or will
0.4.x get merged into 0.5.0 administratively?  Please advise.
##### Description
Two entities in javalib now throw Exceptions comparable to Scala JVM & Java itself.
Both were previously silent when attempting, and failing, to open a read-only file
for writing.

The constructors for `RandomAccessFile` now throw `FileNotFound` .
`FileChannel#open` now throws `AccessDeniedException`.

##### Authors
This work is the joint effort of  Arman Bilge and Lee Tibbert.  Arman reported
the original issue and provided a small reproducer.  With his permission,
that reproducer was folded into `FileChannelTest.scala`. 

##### Due diligence

Where there are two bugs, there may be more.  I searched `java.io` and `java.nio`
for places where files were opened.  Something could be hiding in the weeds,
but there appear to be no more cases of opening read-only files for write.

* `java.io.FileOutputStream#fileDescriptor` reports `FileNotFoundException`.
 On the unix path it gives the exceedingly helpful but unconventional errno string.
 The convention is to give the file name (and abandon the useful error details to the bit bucket).
 The Windows path uses the convention.

* `java.nio.file.Files#readAllBytes` opens a file without checking the error return.
  The file is opened `fcntl.O_RDONLY` so it does not have this bug, but it is
   still a bug.  See Issue #2755.

### CODE REVIEW

File: javalib/src/main/scala/java/nio/channels/FileChannel.scala [hunk 1]
```diff
@@ -113,24 +124,30 @@ object FileChannel {
...
+        deleteFileOnClose =
+          options.contains(StandardOpenOption.DELETE_ON_CLOSE),
+        openForReading = true,
+        openForWriting = writing
+      )
+    } catch {
+      case e: Throwable =>
+        raf.close()
+        throw e
+    }
```
Comment (ekrich) [inline javalib/src/main/scala/java/nio/channels/FileChannel.scala:150]: I think you should probably `close()` in a `finally` block unless I am missing something. Either way I think you need to swallow the exception from `close()`. Unless this is the callers obligation to catch the exception and `close()`. I think if the exception is thrown and nothing reasonably can be done then attempting to `close()` the resource is ok but not 100% sure that is the APIs responsibility.

```scala
finally {
  try {
    if (raf != null) {
        raf.close();
   } catch { case _: Throwable => } // I think this is the way to do it
}
```

Comment (ekrich) [reply javalib/src/main/scala/java/nio/channels/FileChannel.scala:150]: Like a `closeAndSwallow(c: Closeable)` utility method?

Comment (LeeTibbert) [reply javalib/src/main/scala/java/nio/channels/FileChannel.scala:150]: Eric,  Thank you for your review & your suggestions.
The code you mentioned is at the end of 
```
 def open(
      path: Path,
      options: Set[_ <: OpenOption],
      attrs: Array[FileAttribute[_]]
  ): FileChannel 
```
On success, it returns an __open__ FileChannel.  That means that the underlying 
`raf` should only be closed on error. If should be closed so that we do not lose
OS file descriptors (fd's).  

Putting the close in `finally` block would pass back
a `FileChannel` with a closed underlying file descriptor.  My first mental drafts
went that way before I went "Oops!".

RandomAccessFile#close is documented as possibly returning an IOException.
That should be exceedingly rare, but if it _does_ happen, somebody almost
certainly wants to know about it.      

I have seen code in other places where a (unix) unconditional close(fd) is done
and the return value ignored.  This is usually in (poor) code where the fd may or
may not be open to begin with (or may be broken underneath).

In the code you identified, the `try` will only be entered if the RandomAccessFile
is open. The strongly presumed state in the `catch` block is that the file is open.
Again, any error is probably something someone wants to know about.  Something
in that World is not right (and probably leaking fds all over the place).

`FileChannel#open` is documented in Java 8 docs as `throws IOException`.
By my understanding of the contract, it is the responsibility of the caller to
decide what to do with an IOException and the responsibility of the 
executing method to reliably bubble up any Exceptions encountered.

Do you concur?  

Can you suggest a minimal comment or two that I could put in the code 
to capture/explain the intent?  The next person in the code is likely to 
be either of us, and I am not sure I could trace this again. (notice no emoticon)

**Comment by LeeTibbert** [comment]
The Linux failures are the known "NIR" "@volatile".  That precludes 
running the Linux runtime tests.  

Those tests execute correctly on my local Linux system and on macOS here
in CI.  They should succeed once the NIR problem no longer exists.

I must say that I have lived an exceedingly __long__ life when all of
the macOS, Windows, and multiarch tests pass and the Linux test
fails.  Never thought I would see that day!

This PR is ready for merge once Eric's  concerns are resolved.

File: javalib/src/main/scala/java/nio/channels/FileChannel.scala (hunk 1 above)
Comment (ekrich) [reply javalib/src/main/scala/java/nio/channels/FileChannel.scala:150]: Line 148 is unsafe (no null check and calling `close()` without a `catch`) and should be similar to the `try` `catch` I provided without the `finally`. That is why I mentioned my hesitation about the `finally` because I was unsure without looking at the bigger picture.

File: javalib/src/main/scala/java/nio/channels/FileChannel.scala [hunk 2]
```diff
@@ -113,24 +124,30 @@ object FileChannel {
...
+        raf.getFD(),
+        Some(path.toFile()),
+        deleteFileOnClose =
+          options.contains(StandardOpenOption.DELETE_ON_CLOSE),
+        openForReading = true,
+        openForWriting = writing
+      )
+    } catch {
+      case e: Throwable =>
+        raf.close()
```
[the remark this answers is not in the document]
Comment (LeeTibbert) [reply javalib/src/main/scala/java/nio/channels/FileChannel.scala:148]: I see your point that `e` is probably what people want to know about and that any
exception from raf.close() should be swallowed.  

Thank you, have a fix on the way (has to pass my local testing before I submit).

This is javalib code, so by my understanding I can not use `scala.util.Try`
and must do it the long, explicit way.

There is no need to check if raf is null because the try block related
to the catch block containing that code is only entered if raf was
non-null at that point.  `tryRandomAccessFile` would have thrown
an Exception if anything there had failed.  

re: close()
We need to close the underlying RAF file on failure (only)
because it is unlikely that anyone will be doing a `FileChannel.close()` after
a `FileChannel.open()` failure.  Implementation details should not be exposed
and Implementations should do a best effort to clean themselves up after errors.

**Comment by LeeTibbert** [comment]
What to do with a fault while already on a fault path is always tricky.
Your review made the case here better. I hope that no one ever
goes down that code path.

File: javalib/src/main/scala/java/nio/channels/FileChannel.scala (hunk 1 above)
Comment (ekrich) [reply javalib/src/main/scala/java/nio/channels/FileChannel.scala]: I really shouldn't be trying to review this if I can't dedicate enough time to do it properly - sorry.
