### PR TITLE
Fix #3006: Add nowarn annotation for long term deprecation

### LINKED ISSUE #3006: Deprecation warning in ThreadTest.scala, probably macOS specific
macOS, 12.6, M1  Scala Native 3.2.1

New-to-me deprecation warning.   I do not remember seeing this on Intel Linux.

I am off on not one but two snark hunts right now and can not take the interrupt
but want to capture it for later; like a lioness saving a kill to be enjoyed at leisure.

```
/unit-tests/native/.3/target/scala-3.2.1/test-classes ...
[warn] -- Deprecation Warning: /Users/lee49/Devo/ScalaNative/WorkSpace_A1/study_j_l_InetAddressWrongException_I3005_2022-11-21T1032-0500/unit-tests/shared/src/test/scala/javalib/lang/ThreadTest.scala:43:38 
[warn] 43 |    assertTrue(Thread.currentThread().getId > 0)
[warn]    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |method getId in class Thread is deprecated since : see corresponding Javadoc for more information.
```

### PR DESCRIPTION
**Pull request by ekrich**
Fix for https://github.com/scala-native/scala-native/issues/3006

### CODE REVIEW

File: test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala [hunk 1]
```diff
@@ -101,6 +102,7 @@ final class TestAdapter(config: TestAdapter.Config) {
     runs -= runID
   }
 
+  @nowarn("msg=getId in class Thread is deprecated")
   private[adapter] def getRunnerForThread(): ManagedRunner = {
     val threadId = Thread.currentThread().getId
```
Comment (armanbilge) [inline test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala:107]: We can scope the `@nowarn` more precisely. Not sure if `cat=deprecation` works for JDK deprecations, but if it does it should be robust to any changes in the message. If not the `msg=...` is good 👍 

```suggestion
  private[adapter] def getRunnerForThread(): ManagedRunner = {
    val threadId = Thread.currentThread().getId: @nowarn("cat=deprecation")
```

**Review by armanbilge — COMMENTED** [review]
Thanks! Just nitpick

File: test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala (hunk 1 above)
Comment (ekrich) [reply test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala:107]: I tried to add both `cat` and `msg` but it didn't work. I didn't see the deprecation again but was not sure if I had to do something other than clean because the deprecation happens on sbt load.

Comment (ekrich) [reply test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala:107]: Bloop is telling me this - do we have to use `msg`?
```
Invalid message filter:
unknown filter: cat:deprecation
```

Comment (ekrich) [reply test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala:107]: Oops:
```
[info] compiling 1 Scala source to /Users/eric/workspace/scala-native/project/target/scala-2.12/sbt-1.0/classes ...
[error] /Users/eric/workspace/scala-native/test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala:106:51: Invalid message filter:
[error] unknown filter: cat:deprecation
[error]     val threadId = Thread.currentThread().getId: @nowarn("cat:deprecation")
```

Comment (ekrich) [reply test-runner/src/main/scala/scala/scalanative/testinterface/adapter/TestAdapter.scala]: Yes, should have been `cat=deprecation`.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
Eric, thank you for nailing this.

**Review by WojciechMazur — APPROVED** [review]
