### PR TITLE
Fix #1849: Streamline clang version detection

### LINKED ISSUE #1849: Streamline clang version detection
Current there are several clang related checks in the tools API in `Discovery`.

1. First it looks for `CLANG_PATH` or `CLANGPP_PATH`. I believe this is to override the first version on your path perhaps for a developer wishing to test multiple versions
2. If this is not found it enumerates the list on `clang/clang++` in the list calling `which clang-8` for example to get the path.
3. It errors out if neither 1 or 2 succeed.
4. Next, it runs `clang` preprocessor to get defined values and looks for "__DECIMAL_DIG__ __LDBL_DECIMAL_DIG__" to check if clang is ok.

Proposal
1. Still support 1 above to get a env defined `CLANG_PATH` but document it in the developer section
2. Do not have a list of enumerated version but only a minimum version
3. If 1. is not the option use `which clang` to get the path otherwise append `clang` to the path
4. Run fullpath to clang to get the version 
```
$ /usr/local/opt/llvm@8/bin/clang
clang-8: error: no input files
$ echo $?
1
```
Not found example for number 1. above in case there is no `clang` at `CLANG_PATH`
```
$ /no/path/to/clang
-bash: /no/path/to/clang: No such file or directory
$ echo $?
127
```
5. Check against minimum version and reject if needed.
6. Check clang for the preprocessor defines and reject if needed
7. Use `clang`

This way people can use a new version if it works. The minimum version could probably be dropped if we just wanted to go with the preprocessor defines as the minimum. This would also probably simplify the current code and means we don't need a PR every time there is a new version of `clang`.

### PR DESCRIPTION
**Pull request by ekrich**

### CODE REVIEW

**Comment by ekrich** [comment]
I am actually really surprised this doesn't work - I will look into the configuration. On macOS, looking a `brew` install where links are set, you find `clang-n`, `clang`, and `clang++` all linked to `clang`. I also had difficulty using a non-symlinked `brew link` version of clang because the platform `ld` was found in the path and did not work correctly.

**Comment by ekrich** [comment]
The previous detection did a `which` with all the listed versions and plain `clang` and `clang++` and grabbed the latest version so it would pickup `clang-6.0` for example. I think is is reasonable to have a `clang` on the path if one is installed but I don't think Ubuntu agrees so either a path needs to be added or the `CLANG_PATH` and `CLANGPP_PATH` needs to be added at least to CI.

https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/clang-6.0_6.0-1ubuntu2_amd64.deb.html

**Comment by ekrich** [comment]
Ready for review.

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 1]
```diff
@@ -80,90 +80,111 @@ object Discover {
...
-    def maybePath(p: Path) = p match {
-      case path if Files.exists(path) => Some(path.abs)
-      case none                       => None
-    }
 
-    def definesBuiltIn(
-        pathToClangBinary: Option[String]): Option[Seq[String]] = {
+    // this could be obsolete with our current minimum version
+    def checkDefinesBuiltIn(clang: String): Unit = {
+      val defineStrs = "__DECIMAL_DIG__ __LDBL_DECIMAL_DIG__"
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:92]: Inded it might be obsolete check.`__DECIMAL_DIG__` preprocessor definition exists since clang 3.7
https://github.com/llvm/llvm-project/commit/4992099b42e9bb6faceb61ed093155bf2ebe7157

Probably we can remove this

**Review by WojciechMazur — CHANGES_REQUESTED** [review]
In overall it looks good to me, we can probably only remove obsolete check and make passing env variable more explicit.

File: tools/src/main/scala/scala/scalanative/build/Discover.scala (hunk 1 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/Discover.scala:92]: Ok, I just removed that in the first commit.

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 2]
```diff
@@ -27,16 +27,16 @@ object Discover {
   def GC(): GC =
     getenv("SCALANATIVE_GC").map(build.GC(_)).getOrElse(build.GC.default)
 
-  /** Find the newest compatible clang binary. */
+  /** Use the clang binary on the path or via CLANG_PATH env var. */
   def clang(): Path = {
-    val path = discover("clang", clangVersions)
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/build/Discover.scala:32]: So should I just call it like this and remove all the internal code to simplify things?
```scala
val path = discover("clang", "CLANG_PATH")
// and
val path = discover("clang++", "CLANGPP_PATH")
```

File: tools/src/main/scala/scala/scalanative/build/Discover.scala [hunk 3]
```diff
@@ -80,90 +80,111 @@ object Discover {
...
 
+  /** Link to setup documentation */
+  private[scalanative] val docSetup =
+    "http://www.scala-native.org/en/latest/user/setup.html"
+
+  /** Discover the binary path using environment
+   *  variables or the command from the path.
+   */
+  private[scalanative] def discover(binaryName: String): Path = {
     val envName =
```
[the remark this answers is not in the document]
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/Discover.scala:143]: So should I just call it like this and remove all the internal code to simplify things?
```scala
val path = discover("clang", "CLANG_PATH")
// and
val path = discover("clang++", "CLANGPP_PATH")
```

[the remark this answers is not in the document]
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/Discover.scala]: Ok, I think that looks much better.

File: tools/src/main/scala/scala/scalanative/build/Discover.scala (hunk 1 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/Discover.scala]: Thanks for checking. I thought we didn't need it but I also didn't know anything about it.

**Review by WojciechMazur — APPROVED** [review]

**Review by sjrd — APPROVED** [review]
