### PR TITLE
Lower memory usage in CodeGen

### LINKED ISSUE #1976: Tests do not compile with releaseFull mode
When trying to run tests with mode `releaseFull` build fails in Interflow when merging two States.
Problem occurred in build with commit sha `c375b432fe8e600f7ad3a201f6c516892e7b681b` for Scala 2.12

Top of stack trace:
```
java.util.NoSuchElementException: key not found: 110001
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
	at scala.scalanative.interflow.State.$anonfun$inherit$1(State.scala:136)
	at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.scalanative.interflow.State.inherit(State.scala:135)
	at scala.scalanative.interflow.Inline.$anonfun$inline$1(Inline.scala:204)
	at scala.scalanative.interflow.Log.in(Log.scala:15)
	at scala.scalanative.interflow.Log.in$(Log.scala:8)
	at scala.scalanative.interflow.Interflow.in(Interflow.scala:10)
	at scala.scalanative.interflow.Inline.inline(Inline.scala:134)
	at scala.scalanative.interflow.Inline.inline$(Inline.scala:131)
	at scala.scalanative.interflow.Interflow.inline(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.nonIntrinsic$1(Eval.scala:144)
	at scala.scalanative.interflow.Eval.eval(Eval.scala:158)
	at scala.scalanative.interflow.Eval.eval$(Eval.scala:102)
	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.run(Eval.scala:29)
	at scala.scalanative.interflow.Eval.run$(Eval.scala:11)
	at scala.scalanative.interflow.Interflow.run(Interflow.scala:10)
	at scala.scalanative.interflow.MergeProcessor.visit(MergeProcessor.scala:365)
	at scala.scalanative.interflow.MergeProcessor.advance(MergeProcessor.scala:382)
	at scala.scalanative.interflow.Opt.process(Opt.scala:120)
	at scala.scalanative.interflow.Opt.process$(Opt.scala:107)
	at scala.scalanative.interflow.Interflow.process(Interflow.scala:10)
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
This PR is one of the steps in order to resolve #1976. It changes the way the `.ll` files are generated. 
The previous implementation had problems with large files, eg. unit tests in release full mode,  where the body of the generated LLVM code was of size ~900MB. This caused multiple OutOfMemory errors. 

The new implementation uses another strategy. It generates the body in a separate file and concatenates it with headers generated afterward. Thanks to writing directly to the file instead of using StringBuilder and keeping all the data in memory we're able to significantly lower memory usage in CodeGen.

### CODE REVIEW

File: util/src/main/scala/scala/scalanative/util/ShowBuilder.scala [hunk 1]
```diff
@@ -31,14 +31,26 @@ final class ShowBuilder {
     indentation -= n
 
   def newline(): Unit = {
-    sb.append("\n")
-    sb.append("  " * indentation)
+    out.append("\n")
+    out.append("  " * indentation)
   }
 
   def clear(): Unit = {
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/ShowBuilder.scala:38]: This method does not make sense on `ShowBuilder` anymore, since it cannot be correctly implemented in `FileShowBuilder`. If it is necessary, it should be moved to `InMemoryShowBuilder` only.

File: util/src/main/scala/scala/scalanative/io/VirtualDirectory.scala [hunk 2]
```diff
@@ -86,11 +92,36 @@ object VirtualDirectory {
...
       finally channel.close
     }
+
+    override def merge(sources: Seq[Path], target: Path): Unit = {
+      if (sources.nonEmpty) {
+        val output = FileChannel.open(resolve(target),
+                                      StandardOpenOption.CREATE,
+                                      StandardOpenOption.WRITE,
+                                      StandardOpenOption.APPEND)
+        try sources.foreach { path =>
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/io/VirtualDirectory.scala:115]: This is weird formatting, IMO. Consider:
```suggestion
        try {
          sources.foreach { path =>
```

File: util/src/main/scala/scala/scalanative/io/VirtualDirectory.scala [hunk 3]
```diff
@@ -86,11 +92,36 @@ object VirtualDirectory {
...
+    }
+
     override def write(path: Path, buffer: ByteBuffer): Unit = {
       val channel = open(resolve(path))
       try channel.write(buffer)
       finally channel.close
     }
+
+    override def merge(sources: Seq[Path], target: Path): Unit = {
+      if (sources.nonEmpty) {
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/io/VirtualDirectory.scala:110]: Why this condition? IMO if the `sources` is empty, we should actually create the output file, and leave it empty. This condition prevents that.

File: util/src/main/scala/scala/scalanative/util/ShowBuilder.scala [hunk 4]
```diff
@@ -3,12 +3,12 @@ package util
 
 import scala.language.implicitConversions
 
-final class ShowBuilder {
-  private var sb          = new java.lang.StringBuilder
+sealed trait ShowBuilder {
+  def out: Appendable
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/ShowBuilder.scala:7]: `out` should be `protected`, including its implementations in the subclasses. Users of `ShowBuilder` should not have access to it.

File: tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala [hunk 5]
```diff
@@ -92,26 +87,32 @@ object CodeGen {
...
-      genDeps()
-      val prelude = builder.toString.getBytes("UTF-8")
-      val buffer  = ByteBuffer.allocate(prelude.length + body.length)
-      buffer.put(prelude)
-      buffer.put(body)
-    }
-
-    def genDeps() = deps.foreach { n =>
+
+    def gen(id: Option[Int], dir: VirtualDirectory): Unit = {
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:91]: Consider making `id` a `String` instead, and pass either `id.toString()` or `"out"` at call site.

File: tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala [hunk 6]
```diff
@@ -92,26 +87,32 @@ object CodeGen {
...
+      val body = dir.write(
+        Paths.get(s"${id.getOrElse("out")}-body.ll"),
+        writer => {
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:94]:
```suggestion
        { writer =>
```

File: tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala [hunk 7]
```diff
@@ -92,26 +87,32 @@ object CodeGen {
...
+          genDefns(defns)(new FileShowBuilder(writer))
+        }
+      )
+
+      val headers = dir.write(
+        Paths.get(s"${id.getOrElse("out")}.ll"),
+        writer => {
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:101]:
```suggestion
        { writer =>
```

**Review by sjrd — CHANGES_REQUESTED** [review]
Looks good overall. Only a few suggestions.

File: util/src/main/scala/scala/scalanative/util/ShowBuilder.scala (hunk 1 above)
Comment (WojciechMazur) [reply util/src/main/scala/scala/scalanative/util/ShowBuilder.scala:38]: Actually `clear` is no longer needed now, so I've removed it. Thanks for tracking me on this.

File: tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala (hunk 6 above)
Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:94]: I've applied it partially, because scalafmt enforces it we be in the same line with `Paths.get()`

**Comment by sjrd** [comment]
Did you forget to actually push changes? You marked the comments as Resolved but it seems you did not push the resolutions.

File: tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala (hunk 6 above)
Comment (sjrd) [reply tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala]: Ah yes. That makes sense. But in fact we could make this even better by declaring `write` using curried argument lists, so that we can call it with
```scala
val body = dir.write(Paths.get(s"${id.getOrElse("out")}-body.ll")) { writer =>
  ...
}
```

**Review by sjrd — APPROVED** [review]
