### PR TITLE
Fix #2049: Use natural ordering for Arrays#sort with null comparator

### LINKED ISSUE #2049: Arrays.sort() with null compator thows NPE
I am about to submit a PR to fix an issue I encountered whilst porting ListTest.scala
to validate my JavaDefaultMethod changes.

ListTest does its job well. One of its exhaustive tests calls Arrays.sort() with a null
comparator  (second arg).  Currently Scala Native throws a NullPoiniterException.
This bug was recently fixed in Scala.js so that both JVM and Scala.js have the
documented behavior of using the Natural Comparator.

### PR DESCRIPTION
**Pull request by LeeTibbert**
We re-port Arrays.scala from Scala.js to pick up the title fix.
An added benefit is that the various sorts are now stable, as
as described in the Java 8 documentation.

The implementation of the deepToString method is retained on a
"first do no harm" basis.  The Scala.js origin uses JavaScript
dynamic arrays. ArrayDeque is an obvious replacement but that
might cause a performance regression.

ArraysTest.scala is ported to exercise the title fix. In addition,
the ported ArraysTest gives much better code coverage throughout.

### CODE REVIEW

File: javalib/src/main/scala/java/util/Arrays.scala [hunk 1]
```diff
@@ -73,18 +75,16 @@ object Arrays {
   @noinline def sort(a: Array[AnyRef], fromIndex: Int, toIndex: Int): Unit =
     sortRangeAnyRefImpl(a, fromIndex, toIndex)
 
-  @noinline
-  def sort[T <: AnyRef](array: Array[T],
-                        comparator: Comparator[_ >: T]): Unit = {
+  @noinline def sort[T <: AnyRef](array: Array[T],
+                                  comparator: Comparator[_ >: T]): Unit = {
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/Arrays.scala:79]: This is a spurious change, as are many other diffs where `@noinline` was put in front on `def` instead of above it. It makes sense for signatures that can stay entirely on one line. But if the signature spans several lines (sometimes *because* of it), then we should not do that, and we should keep `@noinline` above.

File: unit-tests/src/test/scala/java/util/ArraysTest.scala [hunk 2]
```diff
@@ -1,18 +1,1177 @@
...
 
+import java.util.{Arrays, Comparator}
+
+import scala.reflect.ClassTag
+
+object ArraysTest extends ArraysTest
+
+/** This is also used in the typedarray package to test scala.Arrays backed
+ *  by TypedArrays
+ */
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/util/ArraysTest.scala:23]: This comment doesn't make sense in Scala Native. We should probably remove it.

File: unit-tests/src/test/scala/java/util/ArraysTest.scala [hunk 3]
```diff
@@ -1,18 +1,1177 @@
...
 class ArraysTest {
+  // To invoke org.junit.Assert.assertArrayEquals on Array[T]
+  implicit def array2erasedArray[T](arr: Array[T]): Array[AnyRef] =
+    arr.map(_.asInstanceOf[AnyRef])
+
+  /** Overridden by typedarray tests */
+  def Array[T: ClassTag](v: T*): scala.Array[T] = scala.Array(v: _*)
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/util/ArraysTest.scala:30]: This can also be removed.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: javalib/src/main/scala/java/util/Arrays.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/util/Arrays.scala]: Thank you for the timely review.

I concur about annotations being on the line above and am changing this PR.

The  `@noinline` on the same line in the sort methods is exactly
the way it appears in the Scala.js source today.  As part of
personal process improvement, I like to figure out how I 
introduce changes which waste reviewer time. I will be
aware of the `annotations above` principal as I continue
to port.

File: unit-tests/src/test/scala/java/util/ArraysTest.scala [hunk 4]
```diff
@@ -1,18 +1,1173 @@
...
+import scala.reflect.ClassTag
+
+object ArraysTest extends ArraysTest
 
 class ArraysTest {
+  // To invoke org.junit.Assert.assertArrayEquals on Array[T]
+  implicit def array2erasedArray[T](arr: Array[T]): Array[AnyRef] =
+    arr.map(_.asInstanceOf[AnyRef])
+
+  def Array[T: ClassTag](v: T*): scala.Array[T] = scala.Array(v: _*)
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/util/ArraysTest.scala:26]: Here I actually meant to remove the `def Array`, not just the comment. Then all the `Array(...)`s in the test will directly go to `scala.Array(...)` instead of this indirection (which was necessary in Scala.js but not in Native).

File: javalib/src/main/scala/java/util/Arrays.scala [hunk 5]
```diff
@@ -391,110 +326,102 @@ object Arrays {
   @noinline def binarySearch(a: Array[Long], key: Long): Int =
     binarySearchImpl[Long](a, 0, a.length, key, _ < _)
 
-  @noinline
-  def binarySearch(a: Array[Long],
-                   startIndex: Int,
-                   endIndex: Int,
-                   key: Long): Int = {
-    checkRangeIndices(a.length, startIndex, endIndex)
+  @noinline def binarySearch(a: Array[Long],
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/Arrays.scala:329]: There are still a bunch of spurious changes due to `@inline` starting from here. It's not a *big* deal, but for `git blame` purposes it would be nice not to change lines that don't need changing.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: unit-tests/src/test/scala/java/util/ArraysTest.scala (hunk 4 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/util/ArraysTest.scala]: Done. Review by a knowledgeable person does make the code better. Thank you.

File: javalib/src/main/scala/java/util/Arrays.scala (hunk 5 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/util/Arrays.scala]: I believe I have eliminated the spurious changes and understand the decision rule.
I have poured over the log files several times & hope I did not miss anything.

**Review by sjrd — APPROVED** [review]
Thank you :) This is perfect.
