### PR TITLE
Fix #1354: NIO Files.walkFileTree should respect FOLLOW_LINKS option

### LINKED ISSUE #1354: NIO File Walker fails on broken links
[Gitter Log](https://gitter.im/scala-native/scala-native?at=5b9eaafb0cfe7f30f1a350f7)

When using the NIO walker and visiting files, if a broken link is encountered, i.e. `/foo/bar/link -> /baz/foo/does_not_exist`, then the walker will fail (even before visitFile is called in the specified visitor).

Full stack trace:

```
java.nio.file.NoSuchFileException: : /home/soren/.config/fish/functions/fish_prompt.fish
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.nio.fs.UnixException$.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.scala$scalanative$nio$fs$NativePosixFileAttributeView$$throwIOException(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.scala$scalanative$nio$fs$NativePosixFileAttributeView$$getStat(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anonfun$1.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anonfun$1.apply(Unknown Source)
        at scala.scalanative.native.Zone$.apply(Unknown Source)
        at scala.scalanative.nio.fs.NativePosixFileAttributeView.attributes(Unknown Source)
        at java.nio.file.Files$$anonfun$_walkFileTree$1.apply(Unknown Source)
        at java.nio.file.Files$.$underscore$walkFileTree(Unknown Source)
        at java.nio.file.Files$.walkFileTree(Unknown Source)
        at tf.bug.dot.Main$.dissolveLinks(Unknown Source)
        at tf.bug.dot.Main$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

### PR DESCRIPTION
**Pull request by LeeTibbert**
* Issue #1354 reported that the behavior of Files.walkFileTree in SN
    differed from that of Scala JVM "NIO File Walker fails on broken links".

    Upon exploration of the issue, the underlying problem was found
    to be that walkFileTree should alter its behavior depending
    upon the presence or absence of FileVisitOptions.FOLLOW_LINKS in the
    options argument passed in.

    That issue is now fixed.

  * A unit test was added to FilesSuite.scala to exercise both the
    path were FVO.FOLLOW_LINKS is present and when it is not, the
    presenting issue.

  * @eatkins recommended a solution (Thank you!) which turned out
    not to be the final resolution but which did reveal the defect
    that visitor.visitFileFailed() was not being called when
    walkFileTree with LinkOption.NOFOLLOW_LINKS clear (meaning
    follow links.) encountered a broken link.

    Note to the reader: FileVisitOption and LinkOption are distinct but
    related. One needs to invert the former to get the latter which
    is passed to lower routines.

    This second defect is now fixed. It has no unit test for the
    case where a visitor overrides visitFileFailed. That case should
    work but be exceedingly rare.

  * Studies of the presenting problem revealed that Files.find() has
    the same flaw.  I created issue #1530 to track that defect.

    My plan is to create a second PR after this one has been merged.
    Each PR would focus on a single issue, rather than related issues
    being intertwined. This should make review easier.

Documentation:

   * None needed other than the title in the change log.

Testing:

  * Built and tested ("test-all") on X86_64 using sbt 1.2.6 in
    debug mode. All tests expected to pass do so.

### CODE REVIEW

File: javalib/src/main/scala/java/nio/file/Files.scala [hunk 1]
```diff
@@ -627,36 +628,56 @@ object Files {
...
       else {
-        val attributes = getFileAttributeView(p,
-                                              classOf[BasicFileAttributeView],
-                                              Array.empty).readAttributes()
-        while (openDirs.nonEmpty && !parent.startsWith(openDirs.head)) {
-          visitor.postVisitDirectory(openDirs.pop(), null)
-        }
+        try {
+
+          // The sense of how LinkOption follows links or not is somewhat
```
Comment (eatkins) [inline javalib/src/main/scala/java/nio/file/Files.scala]: This is a good explanation. I would really like to know what they were thinking when they introduced `LinkOption.NOFOLLOW_LINKS` and `FileVisitOption.FOLLOW_LINKS` instead of having just one or the other option in each class.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 2]
```diff
@@ -891,6 +894,64 @@ object FilesSuite extends tests.Suite {
...
+      Files.createFile(missingTarget)
+
+      assert(
+        Files.exists(missingTarget) &&
+          Files.isRegularFile(missingTarget))
+
+      // Create valid symbolic link from brokenLink to missingTarget,
+      // then remove missingTarget to break link.
+
+      Files.createSymbolicLink(brokenLink, missingTarget)
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Is it necessary to create the missingTarget to create the symbolicLink? I was under the impression that the api allows one to create broken symbolic links.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 3]
```diff
@@ -891,6 +894,64 @@ object FilesSuite extends tests.Suite {
     }
   }
 
+  // This test was inspired by Issue #1354
+  // "NIO File Walker fails on broken links."
+  test("Files.walkFileTree respects FileVisitOption.FOLLOW_LINKS") {
+    withTemporaryDirectory { dirFile =>
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Outside of the scope of this PR, but it feels like there should be a nio TestHelpers that provides a `withTemporaryDirectory` method that provides a `Path` rather than a `File` so that we don't have a mismatch of io and nio apis in the test suites.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 4]
```diff
@@ -891,6 +894,64 @@ object FilesSuite extends tests.Suite {
...
+
+      val visitor = new QueueingVisitor()
+
+      // will not follow links, so broken link does not throw exception.
+      Files.walkFileTree(dir, visitor)
+
+      val result   = visitor.length
+      val expected = 4
+
+      assert(result == expected, s"result: $result != expected: $expected")
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: It would be better if you actually tested that the expected files were returned rather than just the length.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala [hunk 5]
```diff
@@ -891,6 +894,64 @@ object FilesSuite extends tests.Suite {
...
+
+      // Now follow the broken link and throw exception.
+      val visitor_2 = new QueueingVisitor()
```
Comment (eatkins) [inline unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Not a fan of `_` in variable names in scala.

Comment (eatkins) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: The use of the `_2` also implies that perhaps this should be a separate test. It would make debugging easier if there is a future regression.

File: javalib/src/main/scala/java/nio/file/Files.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/nio/file/Files.scala]: Thank you.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 2 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: This is probably superstition and/or lack of knowledge on my part. I was trying to 
take the same steps as would probably be taken in Real Life and as reported
in the original issue.

I can change it if you like or think it is misdirection that would mislead others or
myself six months down the line.

Please advise.

Comment (eatkins) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I don't really care.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 3 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I can take a run at creating the helper you describe.  It would make things easier for folks,
including myself, to follow in the future.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 4 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: Agreed. Good catch.  I must have written that at the end of a sprint...

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 5 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: re: underscore.  
    I can change that to conform to Scala practice, or, better yet the entire variable name.
I find that my poor eyes miss the terminal digit in `visitor2`.  

re: separate test. 

    I will do that. I'll probably create a method to do the setup for the two tests in common, then get down
to the intent of the test:  Isolate the setup.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 2 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I left it the way it was.  Superstition on my part. File systems have a way of merging
operations or converting them to no-ops underneath.  
Thank you.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 5 above)
Comment (densh) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I agree that we should split it into 2 or more tests. Underscores in variable names are also generally frowned upon.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 3 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I took the first step towards following the suggestion for a TestHelpers.scala by
creating and using a method withTemporaryDirectoryPath().   I hope that 
method captures the concept. At the least, I provides an implementation for 
review and continuous improvement.

I used the new method in the code I was adding only and did not do sweeping 
changes to many other places which used withTemporaryDirectory().

If/when useTemporaryDirectoryPath() passes review, I can create an Issue to
factor withTemporaryDirectory(), withTemporaryDirectory(), and the core routine
they both use, into a separate file.  That probably means changing the imports
for several other nio Suites which currently use withTemporaryDirectory().

?? Should the new file be called withTemporary.scala so that future devos can
easily find the file containing the methods?  I guess that a grep of TestHelpers.scala
would work also.

Thoughts?

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 4 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I changed the code as you suggested.  I now check that the set of files actually visited
matches the set of files expected.  I skip the pre and post-visit directory as that is not
useful.

From what I could find out, the order of visiting sub-directories is unspecified.  I could
find nothing, in limited time, that specified the order of files visited. I take it to be unspecified.
In practice, the order on SN appears to be reverse alphabetical.  I  created and compared
Sets to avoid relying upon any particular order of visitation.

File: unit-tests/src/test/scala/java/nio/file/FilesSuite.scala (hunk 5 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/nio/file/FilesSuite.scala]: I followed the sense of the meeting and split the test into two.  I have each of the
tests calling a common setup method to keep them in synch. 

I do have to admit that the new code looks better, at least to me.

Also, here are now no  underscores in variable names.  I will avoid them in Scala in 
the future.

**Comment by LeeTibbert** [comment]
Addressed first round of review comments. Travis is all green.
