### PR TITLE
Fix #870: Improve scope handling in the sbtplugin

### LINKED ISSUE #870: Performance regression in 0.3.0
Below code snippet shows 2.5 times performance regression on 0.3.0 in comparison with 0.2.0.

By the way, scala-native is 3-10 times slower than Java8. Is that intended?

build.sbt:
    enablePlugins(ScalaNativePlugin)
    scalaVersion := "2.11.11"
    nativeMode := "release"

Code:

    object Main {
      def main(args: Array[String]): Unit = {
        println("Hello, world!")
        println(Seq(1, 2, 3))
        var t = System.nanoTime
        var n = 0
        var k = 0
        while (true) {
          val seq = Seq(1, 2, 3)
          seq.foreach(k += _)
          n += 1
          if (System.nanoTime - t > 1000 * 1e6) {
            println(n)
            n = 0
            t = System.nanoTime
          }
        }
      }
    }

### PR DESCRIPTION
**Pull request by densh**

### CODE REVIEW

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 1]
```diff
@@ -167,48 +118,33 @@ object ScalaNativePluginInternal {
...
+    nativeWarnOldJVM := {
+      val logger = nativeLogger.value
+      Try(Class.forName("java.util.function.Function")).toOption match {
+        case None =>
+          logger.warn("Scala Native is only supported on Java 8 or newer.")
+        case Some(_) =>
+          ()
+      }
+    },
+    nativeLogger := streams.value.log,
```
Comment (sjrd) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: This `nativeLogger` is bullshit. You must directly use `streams.value.log` in tasks that require a logger. Otherwise `last` will not work for those tasks.

`streams` is magical: it gives you a task-specific `Logger` depending on which task requests it. Right now you are bypassing that mechanism, and all logs are associated with the `nativeLogger` task instead of the relevant tasks.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 2]
```diff
@@ -167,48 +118,33 @@ object ScalaNativePluginInternal {
...
-              (tf,
-               new ScalaNativeFramework(f, id, logger, testBinary, envVars))
-          }
-        },
-        definedTests := (definedTests in Test).value
-      )
-
-  lazy val scopedSettings = Seq(
+  lazy val scalaNativeConfigSettings: Seq[Setting[_]] = Seq(
+    nativeWarnOldJVM := {
```
Comment (sjrd) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: I would keep this one in the base settings. Better, I would put it in `globalSettings` (which ends up being `in Global`).

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 3]
```diff
@@ -125,39 +81,34 @@ object ScalaNativePluginInternal {
...
+  lazy val scalaNativeBaseSettings: Seq[Setting[_]] = Seq(
+    crossVersion := ScalaNativeCrossVersion.binary,
+    crossPlatform := NativePlatform,
     nativeClang := {
       val clang = discover("clang", clangVersions)
       checkThatClangIsRecentEnough(clang)
       clang
     },
+    nativeClang in Compile := nativeClang.value,
+    nativeClang in Test := nativeClang.value,
```
Comment (densh) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: It's true that those aliases are useless for `Test` and `Config` but we still need some of them for `NativeTest` to work.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala (hunk 2 above)
Comment (densh) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: Fixed.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala (hunk 1 above)
Comment (densh) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: Fixed.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala (hunk 3 above)
Comment (sjrd) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: Are you sure? `NativeTest` extends `Test`, so it should receive those for free.

Comment (densh) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala]: Yeah, I double checked just now. It's really strange.
