### PR TITLE
fix [javalib]: `java.nio.file.Files.copy` handling for symbolic links

### LINKED ISSUE #3912: javalib: `java.nio.file.Files.copy(Path, Path)` should handle symbolic links
Currently trying to copy symbolic link will result in `IOException(s"Unsupported operation: copy symbolic link...")` 
Javadoc stats that: `If symbolic links are supported, and the file is a symbolic link, then the final target of the link is copied.`  

Also under `NOFOLLOW_LINKS`: 
```
Symbolic links are not followed. If the file is a symbolic link, then the symbolic link itself, not the target of the link, is copied. 
It is implementation specific if file attributes can be copied to the new link. 
In other words, the COPY_ATTRIBUTES option may be ignored when copying a symbolic link.
``` 

Blocker for https://github.com/com-lihaoyi/os-lib/pull/257

### PR DESCRIPTION
**Pull request by WojciechMazur**
* Allow to copy symbolic links, Fixes #3912 
* Fix bug found when creating test - `Files.readSymbolicLink` should recursively resolve target until it's no longer a symbolic link

### CODE REVIEW

File: javalib/src/main/scala/java/nio/file/Files.scala [hunk 1]
```diff
@@ -92,17 +92,16 @@ object Files {
...
-
     val targetExists = exists(target, linkOpts)
     if (targetExists && !options.contains(REPLACE_EXISTING))
       throw new FileAlreadyExistsException(target.toString)
 
     if (isDirectory(source, Array.empty)) {
       createDirectory(target, Array.empty)
+    } else if (attrs.isSymbolicLink() &&
+        options.contains(LinkOption.NOFOLLOW_LINKS)) {
+      if (targetExists) Files.delete(target)
```
Comment (LeeTibbert) [inline javalib/src/main/scala/java/nio/file/Files.scala:103]: Sorry to worry & run.

The unconditional `delete()` here seems suspicious.  I know that
it is in the code being replaced.  It is also probably a "OK on unix but needed on Windows kind of thing".

Seems like the delete should be guarded by the option REPLACE_EXISTING as is done several lines below.

Comment (WojciechMazur) [reply javalib/src/main/scala/java/nio/file/Files.scala:103]: We can enter the `if (targetExists) Files.delete(target)` only if `REPLACE_EXISTING` is passed and it actually exists, so we don't really need to check it one more time. Otherwise it was already validated - if it exists and there is not `REPLACE_EXISTING` then we would throw exception before reaching this line

Comment (LeeTibbert) [reply javalib/src/main/scala/java/nio/file/Files.scala:103]: Thank you for explaining.

Now that you point it out, I now see the code on lines 96 & 97.
```
    if (targetExists && !options.contains(REPLACE_EXISTING))
      throw new FileAlreadyExistsException(target.toString)
```
I also traced through why the ` if (targetExists) Files.delete(target)` is necessary.

I need to ask Ariadne for more string or I will never make it out of this maze.

**Comment by LeeTibbert** [comment]
Wojciech,

For my sins, I am actively working on `Files` `walkFileTree`, `walk` and `find`. I believe they contain a number of defects &
just plain ugliness, particularly around symlinks and `FileSystemLoopException` detection.  I mention that in case
you either review that code or attempt to use it to verify your symlink changes.  You may encounter
the same, or additional defects.  

If you want to do a recursive edit to fix all those, I can pause my work: you have more expertise.  
Otherwise, I suggest that you whistle as you quickly walk by.
