### PR TITLE
Fix Build crashes in releaseFull mode

### LINKED ISSUE #1976: Tests do not compile with releaseFull mode
When trying to run tests with mode `releaseFull` build fails in Interflow when merging two States.
Problem occurred in build with commit sha `c375b432fe8e600f7ad3a201f6c516892e7b681b` for Scala 2.12

Top of stack trace:
```
java.util.NoSuchElementException: key not found: 110001
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
	at scala.scalanative.interflow.State.$anonfun$inherit$1(State.scala:136)
	at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.scalanative.interflow.State.inherit(State.scala:135)
	at scala.scalanative.interflow.Inline.$anonfun$inline$1(Inline.scala:204)
	at scala.scalanative.interflow.Log.in(Log.scala:15)
	at scala.scalanative.interflow.Log.in$(Log.scala:8)
	at scala.scalanative.interflow.Interflow.in(Interflow.scala:10)
	at scala.scalanative.interflow.Inline.inline(Inline.scala:134)
	at scala.scalanative.interflow.Inline.inline$(Inline.scala:131)
	at scala.scalanative.interflow.Interflow.inline(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.nonIntrinsic$1(Eval.scala:144)
	at scala.scalanative.interflow.Eval.eval(Eval.scala:158)
	at scala.scalanative.interflow.Eval.eval$(Eval.scala:102)
	at scala.scalanative.interflow.Interflow.eval(Interflow.scala:10)
	at scala.scalanative.interflow.Eval.run(Eval.scala:29)
	at scala.scalanative.interflow.Eval.run$(Eval.scala:11)
	at scala.scalanative.interflow.Interflow.run(Interflow.scala:10)
	at scala.scalanative.interflow.MergeProcessor.visit(MergeProcessor.scala:365)
	at scala.scalanative.interflow.MergeProcessor.advance(MergeProcessor.scala:382)
	at scala.scalanative.interflow.Opt.process(Opt.scala:120)
	at scala.scalanative.interflow.Opt.process$(Opt.scala:107)
	at scala.scalanative.interflow.Interflow.process(Interflow.scala:10)
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1976 
As described in the linked issue SN was crashing in tests when releaseFull mode was used. 
The combination of this PR and #1979 allows fixing this problem.
One of the root problems was the wrong calculation of the expected type when using Sub.lub methods. This PR allows passing bound as an optional argument to the mentioned method. Also in most of the usages of this method, we make sure to pass bound type basing on the current context. 

To be noted, in one of the recent tests I've discovered that the current Xmx setting of 5G is not sufficient in release full mode - it throws OutOfMemoryError when dumping lowered Defns (the content of all methods is stored in memory, sorted, and then written to file). It's recommended to disable the default nativeDump setting in `MyScalaNativePlugin` or increase Xmx (build passed with Xmx 15G, not tested with the lower value). This problem <del>should be addressed in later PR.</del> was fixed in #1982 

Interflow optimization in release full mode took for unit-tests took 51 minutes. Additional ~30 minutes are needed for compilation using clang.

### CODE REVIEW

File: tools/src/main/scala/scala/scalanative/interflow/Opt.scala [hunk 1]
```diff
@@ -38,6 +38,11 @@ trait Opt { self: Interflow =>
     val fresh = Fresh(0)
     val state = new State(Local(0))
 
+    // Interflow usually infers better types on our erased type system
+    // than scalac, yet we live it a benefit of the doubt and make sure
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/interflow/Opt.scala:42]: Maybe: `yet we leave it as a benefit`?

Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/interflow/Opt.scala:42]: I've not seen this type when copy-pasting. Consider it fixed. Thanks for spotting this one!

File: tools/src/main/scala/scala/scalanative/interflow/MergeProcessor.scala [hunk 2]
```diff
@@ -75,7 +75,7 @@ final class MergeProcessor(insts: Array[Inst],
         val mergeEmitted = mutable.Map.empty[Op, Val]
         val newEscapes   = mutable.Set.empty[Addr]
 
-        def mergePhi(values: Seq[Val]): Val = {
+        def mergePhi(values: Seq[Val], bound: Option[Type] = None): Val = {
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/interflow/MergeProcessor.scala:78]: Consider removing the default value, so that it's painfully obvious at call site when we use `None` (which is the dangerous value, so it should be visible):
```suggestion
        def mergePhi(values: Seq[Val], bound: Option[Type]): Val = {
```

File: tools/src/main/scala/scala/scalanative/linker/Sub.scala [hunk 3]
```diff
@@ -61,7 +61,8 @@ object Sub {
     }
   }
 
-  def lub(tys: Seq[Type], bound: Type)(implicit linked: linker.Result): Type = {
+  def lub(tys: Seq[Type], bound: Option[Type] = None)(
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/linker/Sub.scala:64]: Same here:
```suggestion
  def lub(tys: Seq[Type], bound: Option[Type])(
```

**Review by sjrd — CHANGES_REQUESTED** [review]
Basically looks good. I only suggest to remove the default values.

**Review by sjrd — APPROVED** [review]
