### PR TITLE
Fix #1770: Fix __scala_== with ScalaNumbers.

### LINKED ISSUE #1770: __scala_.== is borked with BigInt & BigInteger, almost certainly both BigDecimal
On scala JVM, code similar to rough & dirty code in the next block returns true for ==, as
expected.

ScalaNative returns false for both scala BigInt and java BigInteger.  The first hints of this defect came from getting the ZIO TestFramework specifications (tests or Specs) to work. 

This issue is bigger than a breadbox but, I hope, smaller than a barn.   A number of
unit-tests will need to be created.

```
From scastie, scala 2.11.8 and various others
Code:
    val token = 2047L
    val bi1 = BigInt(token)
    val bi2 = BigInt(token)

    printf(s"\n")
    printf(s"study_BigIntEquality - bi1 == bi2: ${bi1 == bi2}\n")
    printf(s"study_BigIntEquality - bi1.equals(bi2): ${bi1.equals(bi2)}\n")
    printf(s"study_BigIntEquality - bi1.eq(bi2): ${bi1.eq(bi2)}\n")
    printf(s"study_BigIntEquality - bi1.compare(bi2): ${bi1.compare(bi2)}\n")
    printf(s"\n")

    val jbi1: java.math.BigInteger = java.math.BigInteger.valueOf(token)
    val jbi2: java.math.BigInteger = java.math.BigInteger.valueOf(token)

    printf(s"\n")
    printf(
      s"study_BigIntegerEquality - jbi1 == jbi2: ${jbi1 == jbi2}\n")
    printf(
      s"study_BigIntegerEquality - jbi1.equals(bi2): ${jbi1.equals(jbi2)}\n")
    printf(
      s"study_BigIntegerEquality - jbi1.eq(bi2): ${jbi1.eq(jbi2)}\n")
    printf(s"study_BigIntEquality - jbi1.compareTo(jbi2): ${jbi1.compareTo(jbi2)}\n")
    printf(s"\n")

Output:
study_BigIntEquality - bi1 == bi2: true
study_BigIntEquality - bi1.equals(bi2): true
study_BigIntEquality - bi1.eq(bi2): false
study_BigIntEquality - bi1.compare(bi2): 0
study_BigIntegerEquality - jbi1 == jbi2: true
study_BigIntegerEquality - jbi1.equals(bi2): true
study_BigIntegerEquality - jbi1.eq(bi2): false
study_BigIntEquality - jbi1.compareTo(jbi2): 0
```

I did not run test cases, but I _strongly_ suspect that both Scala & Java BigDecimal have
the same or similar defect.

I have located code in two places which needs fixing for the BigI* cases.  It looks to me that a number of other places might need to be fixed (i.e. add Big* support to primitives).  I have
working proof-of-concept code for the simple BigI* cases.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This PR was motivated by Issue #1770:
    "__scala_== is borked with BigInt & BigInteger, both BigDecimal".

    That issue is now resolved.

 *  This PR needs review from experts in Scala & Java equality. It affects a key and widely used
    piece of Scala Native. 

 *  The presenting problem was that some tests used to test Zio compiled
    with Scala native. reported failures not seen in JVM or Scala.js
    variants.  Examination showed that the reported failures were because
    two Scala BigInts compared false using '==' while comparing true
    using .equals().  They should have compared true in the former case
    and did not.

    Later studies for issue #1770 showed that comparison of two
    Scala BigDecimal instances which should have compared '=='
    as true compared as false.

    The edit to javalib/...java/lang/Number.scala addresses this problem.
    ScalaNumber extends Number.

  * I scanned the entire code base for similar problems.  The family
    of Atomic*Number objects were examined more closely and found not
    to bear this flaw.

  * Unit tests were created to exercise the proposed changes.  They
    failed before this PR and pass as of this PR.

#### Documentation:

  * This PR deserves a prominent change note under a "Bugs" fixed
    section.

###### Safety

  * Built ("rebuild")and tested ("test-all") in debug mode using sbt 1.3.10
    & Java 8 on X86_64 only . All tests pass.

###### Efficacy

  * Specially crafted unit-tests provided in this PR  fail before the PR and pass after it.

### CODE REVIEW

File: unit-tests/src/test/scala/java/lang/ScalaNumberSuite.scala [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+    assert(sbd1 == sbd2)
+  }
+
+  test("BigDecimal.equals(BigDecimal)") {
+    val token                       = 2046.5
+    val sbd1: scala.math.BigDecimal = scala.math.BigDecimal(token)
+    val sbd2: scala.math.BigDecimal = scala.math.BigDecimal(token)
+
+    assert(sbd1.equals(sbd2))
+  }
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/lang/ScalaNumberSuite.scala:43]: Please also add tests for equality mixing `BigInt` and `Int`, and `BigDecimal` and `Double`, in both directions. If they have the same value, they should compare equal in all directions.

File: javalib/src/main/scala/java/math/BigDecimal.scala [hunk 2]
```diff
@@ -1284,6 +1284,10 @@ class BigDecimal() extends Number with Comparable[BigDecimal] {
     }
   }
 
+  @inline override def __scala_==(other: _Object): scala.Boolean = {
+    this.equals(other)
+  }
```
Comment (sjrd) [inline javalib/src/main/scala/java/math/BigDecimal.scala:1289]: This should not be here. The codegen is supposed to automatically add this in the vtable because `BigDecimal` overrides `equals`, as explained by the comment at
https://github.com/scala-native/scala-native/blob/b49e74efe7079bdf415b5724da4acb87c5567210/nativelib/src/main/scala/java/lang/Object.scala#L39-L44
If that's not the case, that's a problem in the codegen; not in the library.

In general, user space classes should *never* implement `__scala_==`, since that is an implementation detail of Scala Native.

File: javalib/src/main/scala/java/math/BigInteger.scala [hunk 3]
```diff
@@ -462,6 +462,10 @@ class BigInteger extends Number with Comparable[BigInteger] {
   override def doubleValue(): Double =
     java.lang.Double.parseDouble(this.toString)
 
+  @inline override def __scala_==(other: _Object): scala.Boolean = {
+    this.equals(other)
+  }
+
```
Comment (sjrd) [inline javalib/src/main/scala/java/math/BigInteger.scala:468]: Same as the comment in `BigDecimal` above.

File: javalib/src/main/scala/java/lang/Number.scala [hunk 4]
```diff
@@ -11,7 +11,9 @@ abstract class Number extends java.lang._Object with java.io.Serializable {
   def doubleValue(): scala.Double
 
   @inline override def __scala_==(other: _Object): scala.Boolean = {
-    if (other.isInstanceOf[ScalaNumber] && !this.isInstanceOf[ScalaNumber]) {
+    if (this.isInstanceOf[ScalaNumber]) {
+      this.equals(other)
+    } else if (other.isInstanceOf[ScalaNumber]) {
       other.equals(this)
     } else {
       super.__scala_==(other)
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Number.scala:19]: I don't think this is the appropriate fix. The previous code *should* have been correct, if `java.lang.Object.__scala_==` had a reasonable implementation. The reasonable implementation should be:
```scala
  @inline def __scala_==(that: _Object): scala.Boolean =
    this.equals(that)
```
Instead, it's
https://github.com/scala-native/scala-native/blob/b49e74efe7079bdf415b5724da4acb87c5567210/nativelib/src/main/scala/java/lang/Object.scala#L39-L44
as an optimization based on some vtable hackery.

Unfortunately the vtable hackery doesn't patch up `super.__scala_==` calls. That means we can never do `super.__scala_==`, and instead we should inline the correct, reasonable implementation that is written nowhere.

So the correct implementation of `Number.__scala_==` should be:
```scala
  @inline override def __scala_==(other: _Object): scala.Boolean = {
    if (other.isInstanceOf[ScalaNumber] && !this.isInstanceOf[ScalaNumber]) {
      other.equals(this)
    } else {
      this.equals(other)
    }
  }
```

**Comment by sjrd** [comment]
Also, could you rebase on the latest master? It seems some changes are scalafmt applied to otherwise untouched files, which shouldn't happen if the PR is up-to-date with master.

File: javalib/src/main/scala/java/math/BigDecimal.scala (hunk 2 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/math/BigDecimal.scala]: Removed

File: javalib/src/main/scala/java/math/BigInteger.scala (hunk 3 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/math/BigInteger.scala]: removed

File: unit-tests/src/test/scala/java/lang/ScalaNumberSuite.scala (hunk 1 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/ScalaNumberSuite.scala:148]: Done.  There are also some tests in j.l.BigIntegerSuite and j.l.BigDecimalSuite to check that
previously failing cases pass with the new __scala_== implementation.

File: javalib/src/main/scala/java/lang/Number.scala (hunk 4 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Number.scala]: I committed with the recommended fix and Travis CI is all green.  Thank you for the patient 
explanation.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Number.scala]: After the successful commit, I sat down and drew out the truth tables, mentally thanking my Discrete Math professor.

I believe the following code is equivalent and correct.  It passes the same tests as the
code in the current commit.   I find this code to be easier to read and understand.
I think future developers may also find it easier.

```
  @inline override def __scala_==(other: _Object): scala.Boolean = {           
    if ((this.isInstanceOf[ScalaNumber]) ||                                    
        (!other.isInstanceOf[ScalaNumber])) {                                  
      this.equals(other)                                                       
    } else {                                                                   
      other.equals(this)                                                       
    }       
```
It may also have performance benefits. I believe that the `this` left comparand will more
 likely be a ScalaNumber, by a large factor. The code above would do one test in that case,
leading to a lower amortized cost for some/most workloads.

Since the code is inlined, and the type of `this` is known at compile time, there is
a sporting chance that the inliner will reduce the call to `this.equals(other)` when
this is known to be a ScalaNumber.

Normally, I would go with the commited code and be done with it. However, this is a 
`hot` path, where likely instruction path length matters, as long as correctness is maintained.

Insert the classical refrain of "Show me the data, across a series of workloads'.

Note to future self:   

The test for `other` being a scala number is necessary to pass the 'j.l.Integer == BigInt` 
case and similar in the test suite.  The code above can not be correctly reduced to `this.equals(other)`.

Comment (sjrd) [reply javalib/src/main/scala/java/lang/Number.scala]: > I believe the following code is equivalent and correct. It passes the same tests as the
> code in the current commit. I find this code to be easier to read and understand.
> I think future developers may also find it easier.
> 
> I can do another commit if my proposed code is acceptable.
> 
> ```
>   @inline override def __scala_==(other: _Object): scala.Boolean = {           
>     if ((this.isInstanceOf[ScalaNumber]) ||                                    
>         (!other.isInstanceOf[ScalaNumber])) {                                  
>       this.equals(other)                                                       
>     } else {                                                                   
>       other.equals(this)                                                       
>     }       
> ```

This is indeed correct. I'm not sure about the performance impact.

> It may also have performance benefits. I believe that the `this` left comparand will more
> likely be a ScalaNumber, by a large factor. The code above would do one test in that case,
> leading to a lower amortized cost for some/most workloads.

The cases where `this` is a `ScalaNumber` are basically *only* for `scala.math.BigInt` and `scala.math.BigDecimal`. For those, we know that equality is expensive (at least it's more than one or two tests) so their equality will dwarf whatever optimization we try to do for them in `__scala_==`. Therefore, this does not seem to be a scenario worth optimizing for.

> Since the code is inlined, and the type of `this` is known at compile time, there is
> a sporting chance that the inliner will reduce the call to `this.equals(other)` when
> this is known to be a ScalaNumber.

That is true, but the same reasoning applies to the existing code as well. If `this` is known to be a `ScalaNumber` at compile time, then the condition
```scala
other.isInstanceOf[ScalaNumber] && !this.isInstanceOf[ScalaNumber]
```
reduces to
```scala
other.isInstanceOf[ScalaNumber] && false
```
which, because `isInstanceOf` is always pure, can also be optimized down to
```scala
false
```
allowing the whole method to reduce to `this.equals(that)`.
