### PR TITLE
Fix #3078, allow methods to have more then 10k instructions

### LINKED ISSUE #3078: large `List` causes assertion failed in interflow
This was encountered in https://github.com/typelevel/idna4s/pull/64, which uses source generation to implement the UTS46 standard for IDNA, which often build large collections.

Specifically, https://github.com/typelevel/idna4s/pull/64/commits/f996802220673f9b430f9fa98042f13875ad79bb causes the `nativeLink` step to crash due to this assertion.

https://github.com/scala-native/scala-native/blob/51b6b29cb8175194126208ae172d0b08f03cbc56/tools/src/main/scala/scala/scalanative/interflow/UseDef.scala#L89

### Minimizer

https://gist.github.com/armanbilge/2032a9623b7acfa36771e5165f30682d

### Output

<details>

```
scala-cli --native debug.scala 
Compiling project (Scala 3.2.1, Scala Native)
Compiled project (Scala 3.2.1, Scala Native)
Picked up JAVA_TOOL_OPTIONS:  -Xmx3489m
[info] Linking (10723 ms)
[info] Discovered 658 classes and 3684 methods
[info] Optimizing (debug mode) (10101 ms)
Exception in thread "main" java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:208)
        at scala.scalanative.interflow.UseDef$.enterInst$1(UseDef.scala:89)
        at scala.scalanative.interflow.UseDef$.$anonfun$apply$5(UseDef.scala:116)
        at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
        at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
        at scala.scalanative.interflow.UseDef$.$anonfun$apply$3(UseDef.scala:114)
        at scala.scalanative.interflow.UseDef$.$anonfun$apply$3$adapted(UseDef.scala:112)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.scalanative.interflow.UseDef$.apply(UseDef.scala:112)
        at scala.scalanative.interflow.UseDef$.eliminateDeadCode(UseDef.scala:155)
        at scala.scalanative.codegen.Lower$Impl.onInsts(Lower.scala:180)
        at scala.scalanative.nir.Transform.onDefn(Transform.scala:18)
        at scala.scalanative.nir.Transform.onDefn$(Transform.scala:8)
        at scala.scalanative.codegen.Lower$Impl.super$onDefn(Lower.scala:84)
        at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefn$1(Lower.scala:84)
        at scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:43)
        at scala.scalanative.codegen.Lower$Impl.onDefn(Lower.scala:84)
        at scala.scalanative.codegen.Lower$Impl.$anonfun$onDefns$1(Lower.scala:72)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.scalanative.codegen.Lower$Impl.onDefns(Lower.scala:63)
        at scala.scalanative.codegen.Lower$.apply(Lower.scala:23)
        at scala.scalanative.codegen.CodeGen$.$anonfun$lower$2(CodeGen.scala:37)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
        at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:80)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Error: scala.build.errors.ScalaNativeBuildError: Error compiling with Scala Native
For more details, please see '/workspace/sandbox/.scala-build/stacktraces/1673202207-1552726076556393695.log'
```

</details>

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #3078 in which assertion error was thrown during build. In functions having more then 10k instructions some instructions would start to use ids of merge blocks (in the Interflow optimizer). 

* Increased limit to 1 million instructions
* Added check for methods having more allowed limit

### CODE REVIEW

File: tools/src/main/scala/scala/scalanative/interflow/MergeProcessor.scala [hunk 1]
```diff
@@ -473,6 +481,8 @@ final class MergeProcessor(
 object MergeProcessor {
   case object Restart extends Exception with scala.util.control.NoStackTrace
 
+  private val MergeBlockOffset = 1000000L
```
Comment (ekrich) [inline tools/src/main/scala/scala/scalanative/interflow/MergeProcessor.scala:484]: Do you think it might be a good idea to leave some hints here or at the top about the 1m limit?

Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/interflow/MergeProcessor.scala:484]: There is an assertion at the begging of the MergeProcessor constructor, but I can add some comments here as well. 
I don't think we shall ever reach such a big number again in any sane code, but better be safe than sorry
