### PR TITLE
Fix #1330 "SocketSuite buffer size tests failing on WSL"

### LINKED ISSUE #1330: SocketSuite buffer size tests failing on WSL
On windows/WSL after going through the instructions

> javalib/publishLocal
> tests/test

I have two failing tests:

> [info] * java.net.SocketSuite$
> [info]   [fail] receiveBufferSize
> [info]   [fail] sendBufferSize

### PR DESCRIPTION
**Pull request by LeeTibbert**
* The presenting problem was expressed in issue #1330
    "SocketSuite buffer size tests failing on WSL".
    This issue is now fixed.

  * The underlying issue was a conceptual problem in the two tests
    "receiveBufferSize" & "sendBufferSize".

    The Java 8 API documentation for methods setReceiveBufferSize & and
    setSendBufferSize at URL
        https://docs.oracle.com/javase/8/docs/api/java/net/
	      Socket.html#setReceiveBufferSize-int- // yes, trailing dash!

    describes the argument to the calls as a _hint_ which the Operating
    System (OS) can ignore.  There are several valid reasons why the OS can
    choose to do so. Changing the buffer size, even before a bind() call
    may not be supported. The buffer size may already be at its maximum.

    The result is that a call to get*BufferSize after the set call may
    return almost any strictly positive value. It makes no sense testing
    it.  That test has been removed.

  * Previously the two changed tests could leave a socket open (no close())
    if the assertion failed. This is potential leak of a limited resource.
    The code in this pull request does not have this potential leak.

64/32 bit issues:

      None known.

Documentation:

       None required. The comments in the Suite itself should suffice.

Testing:

	* Built and tested ("test-all") on X86_64. All tests passed.

	* I do not have access to a WSL system but will ask the original
	  poster to exercise the change.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
@asoltysik 
Looks like you were the original author.  If you are still involved/interested, could you give
this change a quick review?  Often the author as a unique perspective.

I try to treat the original code with respect and hope that I have done so here.

Thank you (and thank you for the original code itself!)

Lee

File: unit-tests/src/test/scala/java/net/SocketSuite.scala [hunk 1]
```diff
@@ -54,23 +54,55 @@ object SocketSuite extends tests.Suite {
...
+    // setSendBufferSize do not unexpectedly throw and that the former
+    // returns a minimally sane value.
+    // See more extensive comments in setBufferSize test.
+
+    val s = new Socket()
+
+    try {
+      val prevValue = s.getReceiveBufferSize
+      assert(prevValue > 0)
+      s.setReceiveBufferSize(prevValue + 100)
```
Comment (jonas) [inline unit-tests/src/test/scala/java/net/SocketSuite.scala]: Looks like you copy pasted the above code. Should be getSendBufferSize and setSendBufferSize.

Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/net/SocketSuite.scala]: Oops!  Thank you for the review and, especially, catching that! 
Color me embarrassed.

Just corrected this and will baby-sit Travis to ensure I did not
mess anything up on the process of correcting.

**Comment by LeeTibbert** [comment]
@asoltysik Thank you for the review, especially from the original author.

**Comment by martijnhoekstra** [comment]
The socket testsuite passes on WSL on this branch.
