### PR TITLE
Fix #1623: Fix an infinite loop in j.i.RandomAccessFile#readLine

### LINKED ISSUE #1623: j.i.RandomAccessFile loops forever
@david-bouyssie reported on gitter that RandomAccessFile#readLine has an infinite
loop.  Adding imports to the code he posted one gets the reproducer:

```
mport java.io.RandomAccessFile
import java.io.RandomAccessFile._

val reader = new RandomAccessFile("./test.txt","r")
println( reader.readLine() )
```
When this code tries to read any extant, non-empty test.txt  it hangs in a tight CPU loop.
The file I used to reproduce the reported problem contained one line: abc.
 (Three characters and a newline).

I have a fix working in my sandbox and am in the process of tidying it up for
submission as a PR.

Part of that PR work will be to check other implementations of readLine for that
or similar bugs.

Thank you, @david-bouyssie, for helping make Scala Native better.

### PR DESCRIPTION
**Pull request by LeeTibbert**
We correct the condition which lead to an infinite loop. 
Previously, two-byte Chars were being used where 1-byte Bytes
should have been.

This PR updates and supersedes now closed PR #1624. The latter
has extensive notes which may aid future developers.

### CODE REVIEW

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
@WojciechMazur Thank you for the timely review & approval.  Always nice to have a second set of eyes, especially
when chasing tiny details.

Not trying to push the river, but rather to understand the process.  Do I need to do anything to get this merged or just
wait my turn?    The reason that I ask is that this PR blocks another PR which fixes an embarrassing set of EOF bugs.
I am well aware that things take time, so am asking to eliminate stalls not to increase stress.

File: javalib/src/main/scala/java/io/RandomAccessFile.scala [hunk 1]
```diff
@@ -76,20 +76,39 @@ class RandomAccessFile private (file: File,
...
-    if (getFilePointer() == length()) null
-    else {
+    // DataInputStream#readLine has been deprecated since JDK 1.1
+    // so implement RAF#readLine, rather than delegating.
+    var pos = getFilePointer()
+    var end = length() // standard practice: 1 past last valid byte.
+    if (pos >= end) {
+      null // JDK 8 specification requires null here.
+    } else {
       val builder = new StringBuilder
```
Comment (ekrich) [inline javalib/src/main/scala/java/io/RandomAccessFile.scala:86]: This isn't specifically part of the PR but I think we should be using `java.lang.StringBuilder` here to remove the Scala lib dependency.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/io/RandomAccessFile.scala:86]: Good suggestion, good eyes!  Thank you.  Review leads to better code all around.

Since that line is new code, I think that making the change you suggest does not
break the "unity of purpose" required of a PR.  

Easy enough to write to current practices and not introduce technical debt.

Other Scala lib dependencies may have crept in but I know of no easy way
to find them all at once.  At least this one is gone.  Others as they are found
(We will have to have a planned, but "Turn off Predef" bugfix week sometime).
