### PR TITLE
Fix #4221: Make two java.net Socket tests more robust to use outside CI

### LINKED ISSUE #4221: SocketTest fails with unexpected exception
This is probably an issue with my box with a port taken or something but the test fails in perhaps an alternative path. I am not sure if this is a failure or not.

Config:
macOS Ventura 13.7
openjdk 17.0.12 2024-07-16 LTS
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

```scala
[error] Test org.scalanative.testsuite.javalib.net.SocketTest.connectWithTimeout failed: java.lang.AssertionError: unexpected exception type thrown; expected:<java.net.SocketTimeoutException> but was:<java.net.ConnectException>, took 0.008 sec
[error]     at java.lang.AssertionError.this(Throwables.scala:209)
[error]     ...
[error] Caused by: java.net.ConnectException: Connection refused
```

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #4221 

Modify  two `java.net` `SocketTest` and `DatagramSocketTest` Tests so that they
are more robust and/or informative when used outside the Scala Native
CI (Continuous Integration) environment. 

Network firewalls in particular,  especially highly restrictive firewalls, can
invalidate assumptions in the Test suite about the network environment.

This an instance of the overall discussion of the proper balance 
between the sensitivity and generality of Tests: [ROC curve](https://en.wikipedia.org/wiki/Receiver_operating_characteristic).

### CODE REVIEW

File: unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/net/DatagramSocketTest.scala [hunk 1]
```diff
@@ -395,6 +395,26 @@ class DatagramSocketTest {
...
+     *
+     *   Network developers will need to bypass this check and run the
+     *   test manually.
+     */
+    assumeTrue(
+      "Advanced and/or CI-only test",
+      ju.Optional
+        .ofNullable(System.getenv("GITHUB_ACTIONS"))
+        .orElse("false")
+        .equalsIgnoreCase("true")
```
Comment (WojciechMazur) [inline unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/net/DatagramSocketTest.scala:415]: It can be safely simplified to just 
```suggestion
      sys.env.contains("CI")
```
Similar approach was used in other tests

Comment (LeeTibbert) [reply unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/net/DatagramSocketTest.scala:415]: Thank you for the suggestion.
> Similar approach was used in other tests

I've learned since then.  In a development environment, one has to go out of their way
to define `GITHUB_ACTIONS`. It is perfectly reasonable for a user to have defined `CI`
for something pertinent to their own environment.  Perhaps the devo is one of many and
is named "Charles Ingalls"?

I can make the change next week if you like the `CI` approach.

If you/we decide to go the `GITHUB_ACTIONS` route,  for consistency I can go back and
change the other occurrences of `CI` to the former. I am probably the only one who has
ever used that path.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
Thank you for all the merges today.
