### PR TITLE
Fix #2249: Improve inet_ntoa() ease-of-use.

### LINKED ISSUE #2249: inet_ntoa() declaration does not match Posix spec.
Later:  I seem to have a vague recollection that Scala Native can not pass structures by value.
           Before diving too deeply here, check if that restriction exists or ever existed.
Later+1: See issue #555.
  
##### At the very least, the broken declaration deserves a comment, with reasoning.

Whilst working on corrections to PR #1921, I was hindered by the fact that 
the Scala Native declaration of `posix/arpa/inet inet_ntoa()` does not
match the Posix 2018 standard:
```
@name("scalanative_inet_ntoa")
  def inet_ntoa(in: Ptr[in_addr]): CString = extern
```
From the Posix 2018 standard: 
```
char        *inet_ntoa(struct in_addr);
```
SN a Ptr, Posix does not.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Make it easier for a developer to understand that the argument
of posixlib `inet_ntoa()` is non-standard. Provide rationale
and possible adaptation.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
It is my understanding that the current recommended style for block comments
is `/* */`.  If I tot that wrong, I will change it.  I am __far__ more interested in
the content.    I welcome any wordsmithing and/or improvement.  This stuff
is hard to describe.

File: posixlib/src/main/scala/scala/scalanative/posix/arpa/inet.scala [hunk 1]
```diff
@@ -22,6 +22,19 @@ object inet {
   @name("scalanative_ntohs")
   def ntohs(arg: uint16_t): uint16_t = extern
 
+  /* The argument for inet_ntoa() differs from the POSIX specification
```
Comment (ekrich) [inline posixlib/src/main/scala/scala/scalanative/posix/arpa/inet.scala:25]: Since `scaladoc` get generated, you can use `/** followed by */ and do the standard doc comments. On the `in` entry, that would be the place to say that it is pointer but the spec says reference.

File: docs/lib/posixlib.rst [hunk 2]
```diff
@@ -10,7 +10,7 @@ Scala Native provides bindings for a core subset of the
 C Header          Scala Native Module
 ================= ==================================
 `aio.h`_          N/A - *indicates binding not available*
-`arpa/inet.h`_    scala.scalanative.posix.arpa.inet_
+`arpa/inet.h`_    scala.scalanative.posix.arpa.inet_ [#inet_ntoa]_
```
Comment (ekrich) [inline docs/lib/posixlib.rst:13]: I think it would be better to point out in general in the interopt section that certain anomalies in the specs of `clib` and `posixlib` exist due to this limitation. We are certainly hopeful that our wizard compiler developers can eventually remove the restrictions.

We can make it more clear at each of the sites like suggested and then when they get changed it will be more obvious and the `scaladoc` can be adjusted when we change them back to spec. Some have multiple places like `complex` and are totally non-standard so we don't want to go overboard so we create more work for later. Plus, we haven't had one question about this yet.

You could add something here above the C and POSIX lib - https://scala-native.readthedocs.io/en/latest/lib/index.html - or maybe here. I don't really see much about the limitation - https://scala-native.readthedocs.io/en/latest/user/interop.html#memory-layout-types

**Review by ekrich — CHANGES_REQUESTED** [review]

File: docs/lib/posixlib.rst (hunk 2 above)
Comment (LeeTibbert) [reply docs/lib/posixlib.rst:13]: Ack.  Will reply when/if I can

**Review by WojciechMazur — APPROVED** [review]
