### PR TITLE
Fix #817: Maintain a fixed-size cache of compiled RE2 patterns to replace the finalize method

### LINKED ISSUE #817: Pattern.scala potentially leaks a native memory
There is a class Pattern:
`scala-native/javalib/src/main/scala/java/util/regex/Pattern.scala`
and there is a method:
```
override protected def finalize(): Unit = {
    super.finalize()
    cre2.delete(_regex)
  }
```
You can search `cre2.delete` over codebase, there is no other place where it called. Seems like memory for native part of regex never released.

There are 4 more places where finalize method is declared:
```
scala-native/javalib/src/main/scala/java/io/FileInputStream.scala
scala-native/javalib/src/main/scala/java/io/FileOutputStream.scala
scala-native/javalib/src/main/scala/niocharset/ISO_8859_1_And_US_ASCII_Common.scala
scala-native/javalib/src/main/scala/niocharset/UTF_8.scala
```

### PR DESCRIPTION
**Pull request by matil019**
Fix: #817 

The singleton object `java.util.regex.Pattern` gets a new "Store" which keeps a fixed-size, FIFO circular storage to cache compiled RE2 patterns. The Store automatically deletes older patterns when needed, eliminating the need for `Pattern.finalize`.

### CODE REVIEW

File: javalib/src/main/scala/java/util/regex/cre2h.scala [hunk 1]
```diff
@@ -57,4 +57,8 @@ object cre2h {
   final val ERROR_BAD_UTF8           = 12
   final val ERROR_BAD_NAMED_CAPTURE  = 13
   final val ERROR_PATTERN_TOO_LARGE  = 14
+
+  // this trivial wrapper class is needed to avoid compiler crash at nativeOptimizeNIR
+  // a possible instance of #367 or #939
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/cre2h.scala]: It's definitely #367, #939 is a duplicate.

File: unit-tests/src/test/scala/java/util/regex/PatternSuite.scala [hunk 2]
```diff
@@ -372,6 +372,18 @@ object PatternSuite extends tests.Suite {
...
+  if (runStressTests) {
+    test("compile should not leak memory") {
+      println("===== AN ENDLESS STRESS TEST INVOKED =====")
+      while (true) {
+        for {
+          pattern <- (1 to 500).map(_.toString)
+        } Pattern.compile(pattern)
+      }
+    }
+  }
```
Comment (densh) [inline unit-tests/src/test/scala/java/util/regex/PatternSuite.scala]: If we can't run this test in CI, we should not include it as it's likely to get out of date in long-term.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 3]
```diff
@@ -118,18 +41,157 @@ object Pattern {
       res
     }
 
-  def adaptPatternToRe2(regex: String): String = {
-    regex
+  private object CompiledPatternStore {
+    private case class Entry(regex: String, flags: Int, re2: RE2RegExpOps)
+
+    private val cache =
+      scala.collection.mutable.IndexedSeq.fill[Entry](100)(null)
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: Given that the memory for compiled regular expressions is never going to be freed, the overhead of storing them permanently is negligible. Lets use normal (non-fixed-size) hash map for the cache instead.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 4]
```diff
@@ -118,18 +41,157 @@ object Pattern {
       res
     }
 
-  def adaptPatternToRe2(regex: String): String = {
-    regex
+  private object CompiledPatternStore {
+    private case class Entry(regex: String, flags: Int, re2: RE2RegExpOps)
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: We don't expose our RE2 as a public API, so flags are always constant, no need to remember them in the cache. It can be as simple as a mapping from regex string to a compiled regex instance.

Comment (matil019) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: The overload `compile(String regex, int flags)` does exist in JDK. `Entry.flags` is meant to cache the second parameter (not RE2's).

File: javalib/src/main/scala/java/util/regex/Pattern.scala (hunk 3 above)
Comment (matil019) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: Compiled regexes can be and actually are freed in`put` (l. 76). That said, I agree with you that a normal map is appropriate. How about using (Scala's) `LinkedHashMap` with a separate `size` field? This way, we can keep cache with a Map while limiting the memory usage by keeping `tail`s.

File: javalib/src/main/scala/java/util/regex/Pattern.scala (hunk 4 above)
Comment (densh) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: Good point.

File: javalib/src/main/scala/java/util/regex/Pattern.scala (hunk 3 above)
Comment (densh) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: Lets try the following then:

```
final case class Key(regex: String, flags: Int)
final class Node(var key: Key, var value: RE2RegExpOps, var rc: Int, var next: Node)

var current: Node = ???
var map: java.util.HashMap[Key, Node] = ???
```

1. Nodes form a ringbuffer of some fixed length (lets say 128).
   Every node stores a key that identifies the value it contains,
   precomplied regular expression and a reference count of current
   users of given regular expression.

2. Apart from the ringbuffer there is also a map from keys to 
   nodes that provides direct mapping to already precompiled regular expressions.

3. Whenever a key is requested we do the following:

   1. Check if it's in the map, if it is, lookup the regex through the map
      and increase the reference count for the node while it's being used. 

   2. If it's not, start traversing the ring buffer until a node with rc=0
      is found. We dispose of the old regular exression and remove the key
      from the map. Now the node can be re-used to store a new key/value pair.

   3. If while traversing we get back to the location where we started, 
      we need to grow a ringbuffer by 1 more node, and then we can do the same as ii.

Comment (sjrd) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: You realize that your algorithm never decrements `rc`? Obviously it can't, since you don't know when someone does not use a regex anymore.

Just use an LRU and stop worrying.

Comment (densh) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: @sjrd The only access to the store is through withRE2Regex so it does know when to decrement and increment.

Comment (densh) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: It also scales trivially to multithreaded equivalent with CAS and atomic RC in presence of different threads using different regexes at their own pace.

Comment (matil019) [reply javalib/src/main/scala/java/util/regex/Pattern.scala]: @densh Implemented your suggestion.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 5]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+          n
+        else
+          f(freshNode(n), num - 1)
+      val last = freshNode(null)
+      last.next = f(last, 128)
+      last
+    }
+
+    // Used to quickly look up a Node from a Key.
+    val map = scala.collection.mutable.HashMap.empty[Key, Node]
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: `private`

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 6]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+                     var rc: Int,
+                     var next: Node)
+
+    private def freshNode(next: Node) =
+      new Node(null, new RE2RegExpOps(null), 0, next)
+
+    import scala.annotation.tailrec
+
+    // The tip of Nodes. The Nodes form a ring buffer of some length.
+    var last: Node = {
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: `private`

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 7]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+        map += reused.key -> reused
+        // advance `last` so that it points to the next node (which is likely the least recently used one)
+        last = reused.next
+        reused
+      }
+    }
+
+    def withRE2Regex[A](regex: String, flags: Int)(f: RE2RegExpOps => A): A = {
+      // increase the refcount of the selected node while in use to prevent it from deleted
+      val node = synchronized {
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: `synchronized` here is probably not the best way to make this thread-safe. It's safe to assume single-threaded-only for now as we don't support threads yet.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 8]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+    final case class Key(regex: String, flags: Int)
+    final class Node(var key: Key,
+                     var value: RE2RegExpOps,
+                     var rc: Int,
+                     var next: Node)
+
+    private def freshNode(next: Node) =
+      new Node(null, new RE2RegExpOps(null), 0, next)
+
+    import scala.annotation.tailrec
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: This import should go to the top of the file.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 9]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+      val node = synchronized {
+        val n = selectNode(regex, flags)
+        n.rc += 1
+        n
+      }
+      try f(node.value)
+      finally node.rc -= 1
+    }
+
+    def doCompile(regex: String, flags: Int): RE2RegExpOps = Zone {
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: Is this used anywhere outside this file? If not lets make it `private`.

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 10]
```diff
@@ -118,18 +41,177 @@ object Pattern {
...
+            newnode
+          } else if (n.rc <= 0)
+            n
+          else
+            findUnused(n.next)
+        val reused =
+          if (last.rc <= 0)
+            last
+          else
+            findUnused(last.next)
```
Comment (densh) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: It's good to keep curly braces if `if` is multi-line, here and above.

**Comment by densh** [comment]
LGTM, nicely done @matil019 !
