### PR TITLE
Fix #1748: Address all the compiler warnings, and enable fatal warnings.

### LINKED ISSUE #1748: Various warnings in SN build should be removed.
This Issue gives me a place upon which to hang a PR.

I welcome other people's list of least favorite warnings in the Scala Native build and 
discussion of the changes I am proposing.

The basic issue is that the Scala native build contains various warnings.  For example,
octal numbers and the idiom for single quote characters. In many cases, the compiler
gives the suggested fix in plain sight (yes, I suspect sometimes the suggested fix
is wrong, but should not prevent taking advantage of the cases where it is right),

I have been taught and believe that zero "known warnings" is a good goal because it reduces cognitive load, reduces required wizardry, and makes it easier for new developers to come on board.
For me, it also increases my confidence that the build is reasonably correct.  Besides, a 
clean SN build would make Cotton Mather proud, or at least less scornful.

For many of the warnings, deprecations in particular, removing the cause of the warning needs to
be done to prepare for SN supporting Scala 2.12 and above.

These warnings have disturbed my tranquility for years. Previously the files in question
had been under active development.  I propose take advantage of the current quiet period
to make changes which should be non-controversial.

I will edit this, not necessarily exhaustive,  task list as I identify classes of defects
and as I pick off the low hanging fruit. 
#### consistent basic scalacOptions 

- [X] scalacOptions should be specified and as consistent as feasible across projects.

#### 'rebuild' sbt command
- [X] Deprecations - general
- [X] there were two deprecation warnings; re-run with -deprecation for details
- [X] there were 114 deprecation warnings; re-run with -deprecation for details
- [X] Octal escape literals are deprecated, use \u0000 instead.
- [X] deprecated syntax for character literal (use '\'' for single quote)
- [X] method lines_! in trait ProcessBuilder is deprecated (since 2.11.0): use lineStream_! instead
- [X] there were three unchecked warnings; re-run with -unchecked for details.
- [X] there were four feature warnings; re-run with -feature for details
- [X] Exhaustivity analysis reached max recursion depth, not all missing cases are reported.
- [X] various "implicit value scala.language.implicitConversions" needed warnings
- [X] trait NotNull in package scala is deprecated (since 2.11.0), multiple places
- [X] value Disabled in class CrossVersionFunctions is deprecated (since 1.3.0)
 
#### 'test-all' sbt command
- [X]  assert(anyNull.asInstanceOf[Null] == null) is always true.
- [X] there were three deprecation warnings; re-run with -deprecation for details
- [X] there were 53 feature warnings; re-run with -feature for details

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This PR was motivated by Issue #1748 "Various warnings in SN build
    should be removed". That Issue contains a list of check-boxes which
    describe some of the warnings removed by this PR.

    That issue is now fixed to the best of my ability.  There might
    be some warnings hiding in the weeds.

 *  This PR edits build.sbt so that a set of scalac options are applied
    to all sub-projects. Some of those projects modify the base options
    to suit their needs. 

                       Note Well:  By prior practice, there is no "root" project is declared in ("."). 
                      The scalacOptions of this PR  are not applied there. scalacOptions
                      are the empty list, same as before.  

                      The lack of -Xfatal-warnings when sbt is started from the command line
                      is somewhat astonishing, but it has the useful side effect of allowing one
                      to at least get to the sbt prompt when there are compilation errors.
                      Doing something there with a project should cause -Xfatal-warnings
                      to be used.    
    Previously the handling of scalacOptions was
    inconsistent and scattered over the file. Some sub-projects used
    no options, not even those recommended for current practice.

*   IN PARTICULAR, "-Xfatal-warnings" IS ENABLED IN ALL PROJECTS
    EXCEPT sandbox. It is far better to not let warnings creep into
    the code-base than to run around and attempt to clean them up
    afterwards.

*  Deprecation checking is disabled in the scalalib project because the multiple deprecation 
    warnings there are beyond the control of Scala Native developers.

* Deprecation checking is currently disabled in the test project, as it effectively was prior to this PR.
   The test code currently has one case where it tests a known deprecated Java 8 interface.
    I will create an Issue describing a possible solution so the idea does not get lost..
   Unfortunately, that solution will not happen soon because it is on the down side of the
   Pareto cost/benefit ratio. 

Documentation:

  * The affected files are all internal to the Scala Native build itself.
    Any change visible to a developer using Scala Native artifacts
    is unintentional and a bug.

    Where the changes are not obvious, I left comments in the code so
    that developers of Scala Native itself have some minimal documentation.

Testing:
###### Safety
  * Built ("rebuild")and tested ("test-all") in debug mode using sbt 1.3.10
    & Java 8 on X86_64 only . All tests pass. grep "\[warn\]" of the logfile
    reports zero occurrences.

  * Built and tested ("test-all") in release-fast mode using
    sbt 1.3.9 & Java 8 on X86_64 only . All tests pass.

###### Efficacy 

   * Visual inspection of both the build and test-all as they happened.
 
   * Manually executed grep "\[warn\]" of each of the log file in my private builds. No items found.
      Also did more extensive searches for "fatal", "depr", and "deprecation".

### CODE REVIEW

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala [hunk 1]
```diff
@@ -8,7 +8,27 @@ trait NirGenType { self: NirGenPhase =>
...
+  //
+  // A hypothetical other user could override, but the override itself
+  // states that user is taking the blade guards off on purpose and playing
+  // with sharp edges: A persona damna inde secuta actus suos ("A person
+  // bears the consequences of their own actions").
+  //
+  // 'final' can & should be restored once SN is compiled with Scala >= 2.12.
+
+  /* final */
+  case class SimpleType(sym: Symbol, targs: Seq[SimpleType] = Seq.empty) {
```
Comment (sjrd) [inline nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala:31]: You mark it as `sealed` to work around the bug. That's what we did in Scala.js:
https://github.com/scala-js/scala-js/blob/8dc581072cc47ded199a0b497ff5283de1ed89c2/ir/src/main/scala/org/scalajs/ir/Trees.scala#L56

File: project/build.sbt [hunk 2]
```diff
@@ -20,11 +20,3 @@ addSbtPlugin("com.eed3si9n"       % "sbt-dirty-money"   % "0.2.0")
...
 addSbtPlugin("com.jsuereth"       % "sbt-pgp"           % "2.0.0")
 addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"   % "0.6.1")
-
-scalacOptions ++= Seq(
-  "-deprecation",
-  "-unchecked",
-  "-feature",
-  "-encoding",
-  "utf8"
-)
```
Comment (sjrd) [inline project/build.sbt:30]: This should be kept. These settings apply to the build itself. If you remove them, we won't see warnings happening in the build itself anymore.

File: tools/src/main/scala/scala/scalanative/interflow/Eval.scala [hunk 3]
```diff
@@ -90,6 +90,7 @@ trait Eval { self: Interflow =>
             throw BailOut("try-catch")
           }
           return Inst.Unreachable(Next.None)
+        case _ => BailOut
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/interflow/Eval.scala:93]: I'm pretty sure this does nothing but loading the companion object `BailOut`. It should be `bailOut` to call the `def` defined above. Also, since all the other `case`s in this match have their bodies on separate lines, consider following the style, as follows:
```suggestion
        case _ =>
          bailOut
```

File: unit-tests/src/test/scala/java/lang/StringSuite.scala [hunk 4]
```diff
@@ -255,10 +255,37 @@ object StringSuite extends tests.Suite {
     splitTest("ab", splitExpr = Some("(ab)"))
   }
 
-  test("getBytes") {
-    val b = new Array[scala.Byte](4)
-    "This is a test".getBytes(10, 14, b, 0)
-    assert(new String(b) equals "test")
+  test("getBytes(\"UTF-8\")") {
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/lang/StringSuite.scala:258]: It doesn't seem like these changes should be part of this PR.

File: unit-tests/src/test/scala/scala/AsInstanceOfSuite.scala [hunk 5]
```diff
@@ -20,7 +20,15 @@ object AsInstanceOfSuite extends tests.Suite {
...
-    assert(anyNull.asInstanceOf[Null] == null)
+//    (anyNull.asInstanceOf[Null] == null) and
+//    (anyNull.asInstanceOf[Null] eq null) are _compile_ time tests and
+//    will always be true. How do I know? Scalac tells me so...
+//    Wrapping in an Option gives a somewhat convoluted runtime test.
+//    If something is massively wrong with anyNull.asInstanceOf[Null]
+//    the Option will hold a Some(), of some kind, rather than the expected
+//    None. I (LeeTibbert) am not sure what value this test adds beyond
+//    symmetry & completeness.
+    assert(Option(anyNull.asInstanceOf[Null]).isEmpty)
```
Comment (sjrd) [inline unit-tests/src/test/scala/scala/AsInstanceOfSuite.scala:31]: Consider the following instead:
```suggestion
    assert((anyNull.asInstanceOf[Null]: Any) == null)
```
That keeps the test as is, only silencing the warning, rather than making it more convoluted.

**Comment by LeeTibbert** [comment]
@sjrd Thank you for your timely and, as always, cogent review.  Your experience with scala & sbt
shows.  I know that you have a lot of requests for your time, so I appreciate it.

I will study your comments, implement them, and then do another commit.

File: unit-tests/src/test/scala/java/lang/StringSuite.scala (hunk 4 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/StringSuite.scala:258]: I like the way you think of things...

Reading your comment, it looked like a space shot to me also. I could not reverse engineer it to
provide a reason, so I spent some hours re-creating the original conditions:
```
[error] /Devo_1/PR_build_warnings_I1748_V2/unit-tests/src/test/scala/java/lang/StringSuite.scala:260:22: method getBytes in class String is deprecated: see corresponding Javadoc for more information.
[error]     "This is a test".getBytes(10, 14, b, 0)
[error]                      ^
[error] one error found
[error] (tests / Test / compileIncremental) Compilation failed
[error] Total time: 49 s, completed May 5, 2020 3:56:41 PM
```

The code of this PR gets rid of the deprecated overload of getBytes() and then
provides a reasonably strong test, including Unicode, for the current overload.

File: build.sbt [hunk 6]
```diff
@@ -33,10 +33,23 @@ lazy val mimaSettings: Seq[Setting[_]] = Seq(
   }
 )
 
+// Common start but individual sub-projects may add or remove scalacOptions.
+lazy val baseScalacSettings = {
+  scalacOptions ++= Seq(
```
[the remark this answers is not in the document]
Comment (LeeTibbert) [reply build.sbt]: Implemented as suggested.  Thank you.   It makes the code simpler & easier to understand,
but then, you knew that.

I put that snippet at what I thought was a logical place.  If you think someplace
else in the file is better, I can move it.

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala (hunk 1 above)
Comment (LeeTibbert) [reply nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala]: Implemented as suggested.  Thank you for your knowledge and willingness to share it.
Large block of code smell comments removed.

File: project/build.sbt (hunk 2 above)
Comment (LeeTibbert) [reply project/build.sbt:30]: Restored as suggested.

File: tools/src/main/scala/scala/scalanative/interflow/Eval.scala (hunk 3 above)
Comment (LeeTibbert) [reply tools/src/main/scala/scala/scalanative/interflow/Eval.scala]: Good catch!  Thank you.   Implemented as suggested.

File: unit-tests/src/test/scala/scala/AsInstanceOfSuite.scala (hunk 5 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/scala/AsInstanceOfSuite.scala]: Implemented as suggested.  Thank you.

**Comment by LeeTibbert** [comment]
@errikos   If you have time & interest, could you please review my 2 suggested changes to  nir Types.scala file in this PR?  They provide a wildcard case for two match statements.  I believe
they cause no change in semantics, but would like to check.

It looks like you were active in the file after I first filed this PR.  When I did a new build after
responding to review comments, your edits in Types.scala began to cause CI for this PR to fail:

```
warn] /home/travis/build/scala-native/scala-native/nir/src/main/scala/scala/s\
calanative/nir/Types.scala:157:39: match may not be exhaustive.

[warn] It would fail on the following inputs: Nothing, Null, Ptr, StructValue(\
_), Unit, Var(_), Vararg, Virtual
[warn]   def typeToName(tpe: Type): Global = tpe match {
[warn]                                       ^

[warn] /home/travis/build/scala-native/scala-native/nir/src/main/scala/scala/s\
calanative/nir/Types.scala:173:44: match may not be exhaustive.

[warn] It would fail on the following inputs: Array(_, _), ArrayValue(_, _), B\
ool, Byte, Char, Function(_, _), Nothing, Null, Ptr, Ref(_, _, _), StructValue\
(_), Unit, Var(_), Vararg, Virtual
[warn]   def primConvSig(tpe: Type): Sig.Method = tpe match {
[warn]                                            ^
[warn] two warnings found
```
To my uninformed eyes, adding the missing cases seemed to add no value.  Do you approve of the
wording of the Exception message or can you suggest better?

Least of our worries, I put the Exception on a separate line because if I did the obvious one liner, scalafmt modifies the line to be more than the 80 columns of my screen (project .scalafmt.conf
has a long line max, for some reason.)  Some other files in that directory have Exceptions on
their own line, so it is consistent with those.

Thank you if you are able to review.   If not, I understand.  Too little time for any of us.

File: nir/src/main/scala/scala/scalanative/nir/Types.scala [hunk 7]
```diff
@@ -168,6 +168,8 @@ object Type {
     case Array(tpe, _)      => toArrayClass(tpe)
     case ArrayValue(tpe, _) => toArrayClass(tpe)
     case Function(args, _)  => Global.Top(s"scala.Function${args.length}")
+    case _ =>
+      throw new Exception(s"unknown type ${tpe.show}")
```
Comment (errikos) [inline nir/src/main/scala/scala/scalanative/nir/Types.scala:172]: This could be phrased as "unexpected" instead of "unknown". Essentially, typeToName is used to wrap a type to a name (as per SN terminology). If the match fails, then the type given was not expected there.

Therefore, I would phrase it as something like "type to name: unexpected type ${tpe.show}".

File: nir/src/main/scala/scala/scalanative/nir/Types.scala [hunk 8]
```diff
@@ -176,5 +178,7 @@ object Type {
     case Long   => Sig.Method("longValue", Seq(tpe))
     case Float  => Sig.Method("floatValue", Seq(tpe))
     case Double => Sig.Method("doubleValue", Seq(tpe))
+    case _ =>
+      throw new Exception(s"unknown type ${tpe.show}")
```
Comment (errikos) [inline nir/src/main/scala/scala/scalanative/nir/Types.scala:182]: This is not used, must have been left behind. You may remove `primConvSig` entirely.

File: unit-tests/src/test/scala/java/lang/StringSuite.scala (hunk 4 above)
Comment (sjrd) [reply unit-tests/src/test/scala/java/lang/StringSuite.scala:258]: Ah, I see what's happening.

Now that's a bit tricky, because the changes mean that we are not testing `getBytes(Array[Byte])` anymore. Even if it is deprecated, we must keep testing it. That shows that we have to live with deprecations *in the test suite*. This is inevitable.

Would adding `-deprecation:false` in the test suite project solve this? (like you did in the `scalalib` project)

File: nir/src/main/scala/scala/scalanative/nir/Types.scala (hunk 7 above)
Comment (LeeTibbert) [reply nir/src/main/scala/scala/scalanative/nir/Types.scala:172]: Implemented as suggested.  Thank you for the rapid turnaround review and suggested improvement.

When writing C code, I almost always put the function name in the error message, expecially
if there is more than one place where "error foo" might occur. 

It seems the practice is Scala is to omit the method name and let people figure things
out from the Exception stack trace.  I find that takes much more time and emotional energy
to walk back a pig-ugly stack trace than to comprehend a face-evident message.

File: nir/src/main/scala/scala/scalanative/nir/Types.scala (hunk 8 above)
Comment (LeeTibbert) [reply nir/src/main/scala/scala/scalanative/nir/Types.scala:182]: Deleted, thank you.

File: unit-tests/src/test/scala/java/lang/StringSuite.scala (hunk 4 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/StringSuite.scala:258]: I rolled back the deprecation check in the test sub-project. That puts that sub-project at
"no worse than today"and allows the main benefit of this PR to advance.

Fate willing, I will file two PRs. One to add the UTF-8 test. As long as it is written and
working, it is worthwhile to capture the currently recommended case.

The second PR would add deprecation checking back in.  I need to sandbox 
some ideas from Scala 2.13.2 and the silencer plugin.

Comment (ekrich) [reply unit-tests/src/test/scala/java/lang/StringSuite.scala:258]: It might be nice if you experimented with `sbt-tpolecat` if you find the time. It is the most strict but also is designed for cross project so if we release a 2.12/2.13 and eventually Scala 3/Dotty it should take the options in account as they are changed/added/removed from version to version.

Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/StringSuite.scala]: @ekrich Thank you, as always, for the on-point suggestion.  You could open an Issue for
 discussion and as a forget-me-not.

At the time I did this PR, I had looked at tpolecat's recommendation list and the date on
that list.  I chose the options I understood, mostly from having used them.  I also wanted
to chose options which did not disrupt the world too much. I left that for my no-unused-imports
PR :grimacing:  

Based on your recommendation, I just did a quick sweep of sbt-tpolecat. A topic for
a separate Issue.  Selected option, such a "partial-unification" and such look promising
but require a menagerie of plugins.   Out of scope for this PR, I think but worth discussing
in another venue.

**Comment by LeeTibbert** [comment]
@sjrd Thank you for the approval and the time leading up to it.

Build is now green across the board.

**Comment by LeeTibbert** [comment]
@errikos I believe that I made the changes you requested and that this is ready for, in the fullness of time, your final approval.

**Comment by errikos** [comment]
LGTM. Thank you @LeeTibbert !
