### PR TITLE
Fix #3408: Implement two javalib static String join() methods.

### LINKED ISSUE #3408: javalib String is missing two static join methods
Whilst reviewing PR #3396, I discovered that  javalib `String` appears to be missing two static `join`  methods.

The `StringJoiner` class in PR #3396 may be useful to implement the missing methods.

Scala Native does not have some String methods, such as, I believe, `intern` because they are hard to 
implement or of low value.    It looks like it is time to inventory the `String` methods to see what is
missing and why.  I personally like the style of leaving an unimplemented methods as 
`// def intern(): Mumble // Unimplented, too hard`.    Some folks frown on that style. I find
it useful to find such a "broken heart" rather than a stunning & hard to find absence.
Shows that someone at least considered the issue.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #3408 

 Implement javalib static String join() methods & corresponding Tests.
This implementation uses the new `StringJoiner` code.

### CODE REVIEW

File: javalib/src/main/scala/java/lang/String.scala [hunk 1]
```diff
@@ -8,7 +8,8 @@ import java.util._
 import java.util.regex._
 import java.nio._
 import java.nio.charset._
-import java.util.Objects
+import java.util.{Objects, Arrays}
```
Comment (tanishiking) [inline javalib/src/main/scala/java/lang/String.scala:11]: Unused import?

```suggestion
import java.util.Objects
```

**Review by tanishiking — APPROVED** [review]
One nit comment, but otherwise it looks good from my side :)

File: javalib/src/main/scala/java/lang/String.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/String.scala:11]: @tanishiking 

Thank you for the review & suggestion.  Good to have a second pair of eyes.
