### PR TITLE
Fix #253

### LINKED ISSUE #253: Implement java.lang.Class::getComponentType
The following snippet executes successfully

``` scala
    val arrInt = Array (1, 2)
    arrInt.reverse
```

The following throws an exception:

``` scala
    class A (i: Int)

    val arrA = Array (new A(1), new A(2))
    arrA.reverse

```

### PR DESCRIPTION
**Pull request by densh**
Provides initial implementation for java.lang.Class::getComponentType.

### CODE REVIEW

File: nativelib/src/main/scala/java/lang/Class.scala [hunk 1]
```diff
@@ -15,10 +15,21 @@ final class _Class[A](val ty: Ptr[Type]) {
...
+  def getComponentType(): _Class[_] = {
+    if (ty == typeof[BooleanArray]) classOf[scala.Boolean]
+    else if (ty == typeof[CharArray]) classOf[scala.Char]
+    else if (ty == typeof[ByteArray]) classOf[scala.Byte]
+    else if (ty == typeof[ShortArray]) classOf[scala.Short]
+    else if (ty == typeof[IntArray]) classOf[scala.Int]
+    else if (ty == typeof[LongArray]) classOf[scala.Long]
+    else if (ty == typeof[FloatArray]) classOf[scala.Float]
+    else if (ty == typeof[DoubleArray]) classOf[scala.Double]
+    else classOf[java.lang.Object]
```
Comment (densh) [inline nativelib/src/main/scala/java/lang/Class.scala]: It is indeed an approximation for the time being. The goal here was to unblock reverse. There is a separate ticket for precise semantics.
