### PR TITLE
Cache stack trace elements

### LINKED ISSUE #920: Stack trace generation is slow
Currently we spent a lot of time on conversion from C strings to Scala Strings in fillInStackTrace. It is a performance bottleneck on applications that use exceptions for control-flow (e.g. non-local returns.)

Possible solution: we can do it lazily.

/cc @darkdimius

### PR DESCRIPTION
**Pull request by Duhemm**
Generating stack traces is slow because we convert C strings to Scala
strings. This commits improves the situation by caching stack trace
elements and lazily converting strings.

Fixes #920

### CODE REVIEW

File: javalib/src/main/scala/java/lang/StackTraceElement.scala [hunk 1]
```diff
@@ -37,21 +113,18 @@ final class StackTraceElement(val getClassName: String,
...
+    collection.mutable.HashMap.empty[CUnsignedLong, StackTraceElement]
+  private def makeStackTraceElement(
+      cursor: Ptr[scala.Byte]): StackTraceElement = {
+    val name   = stackalloc[CChar](256)
+    val offset = stackalloc[scala.Byte](8)
+
+    unwind.get_proc_name(cursor, name, 256, offset)
+    new StackTraceElement(name)
   }
+  def cached(cursor: Ptr[scala.Byte],
```
Comment (densh) [inline javalib/src/main/scala/java/lang/StackTraceElement.scala]: `private[lang]`

File: javalib/src/main/scala/java/lang/StackTraceElement.scala [hunk 2]
```diff
@@ -1,15 +1,91 @@
...
+          }
+      }
 
-  if (getMethodName == null)
-    throw new NullPointerException("Method name is null")
+    initDone = true
+    _className = className
+    _methodName = methodName
+    _fileName = null
+    _lineNumber = 0
```
Comment (densh) [inline javalib/src/main/scala/java/lang/StackTraceElement.scala]: As soon as you complete the initialization you can set `symbol` field to null as it's never going to be used again.

File: javalib/src/main/scala/java/lang/StackTraceElement.scala (hunk 1 above)
Comment (densh) [inline javalib/src/main/scala/java/lang/StackTraceElement.scala]: Lets also add a comment that explains why and how are stack trace elements cached.

**Comment by Duhemm** [comment]
@densh Done!

**Comment by densh** [comment]
Needs some from scalafmt, otherwise LGTM!

**Comment by densh** [comment]
Needs some love from scalafmt, otherwise LGTM!

**Comment by Duhemm** [comment]
@densh Done!

**Comment by densh** [comment]
LGTM, thanks!
