### PR TITLE
Performs better checks in commix semaphore operations

### LINKED ISSUE #2220: Make commix GC more robust
This issue is a follow-up on the PR #2216, which fixed a problem with the lengths of the semaphores but did not make the commix garbage collector checks more robust, to tackle several outstanding problems in commix (see that PR for the detailed discussion):

* Assert on the semaphores names to not be longer than `_POSIX_NAME_MAX` and or `_XOPEN_NAME_MAX`.
* Check on the calls of `sem_open`, `sem_post`, `sem_wait`, etc to return 0, and if they don't, exit the process.
* Investigate how if `errno` is supposed to be thread specific (at least in Linux), and commix is supposed to be executing on another thread, the `errno` was being polluted. To reproduce that, the code in #2200 and the version `0.4.0` of the library in MacOS end up with an `errno` of 9 [here](https://github.com/scala-native/scala-native/blob/15ea60eef45c6263cbb7b736c66eec72c3ab51e6/javalib/src/main/scala/java/lang/IEEE754Helpers.scala#L58) because of a `sem_post` in commix for a semaphore that was not properly open.

### PR DESCRIPTION
**Pull request by ncordon**
The `commix` garbage collector performs operations on semaphores (`sem_open`, `sem_wait` or `sem_post`). This PR adds assertions and prints to the stderr on those, exiting the process with `errno` if they fail.

Uses `fprintf` to `stderr` instead of `perror` for consistency with other checks already done in the garbage collector (see [this](https://github.com/scala-native/scala-native/blob/cda609582a1dfdc119bb85b6cf811918e065c0d6/nativelib/src/main/resources/scala-native/gc/commix/Heap.c#L101) for an example)

Closes #2220

### CODE REVIEW

File: nativelib/src/main/resources/scala-native/gc/commix/Heap.c [hunk 1]
```diff
@@ -27,7 +27,7 @@
 #define HEAP_MEM_FD_OFFSET 0
 
 void Heap_exitWithOutOfMemory() {
-    printf("Out of heap space\n");
+    fprintf(stderr, "Out of heap space\n");
     StackTrace_PrintStackTrace();
     exit(1);
```
Comment (ncordon) [inline nativelib/src/main/resources/scala-native/gc/commix/Heap.c:32]: This was not being printed to the `stderr`

File: nativelib/src/main/resources/scala-native/gc/immix/Heap.c [hunk 2]
```diff
@@ -23,7 +23,7 @@
 #define HEAP_MEM_FD_OFFSET 0
 
 void Heap_exitWithOutOfMemory() {
-    printf("Out of heap space\n");
+    fprintf(stderr, "Out of heap space\n");
```
Comment (ncordon) [inline nativelib/src/main/resources/scala-native/gc/immix/Heap.c:26]: This was not being printed to the stderr

**Review by WojciechMazur — APPROVED** [review]
