### PR TITLE
Fixes #1245: Implementation of Enum.equals/Enum.hashCode

### LINKED ISSUE #1245: Link error with Enum
I'm getting this linking error:

```
[error] cannot link: @java.lang.Enum::hashCode_i32
```

### PR DESCRIPTION
**Pull request by cquiroz**

### CODE REVIEW

File: javalib/src/main/scala/java/lang/Enum.scala [hunk 1]
```diff
@@ -7,4 +7,9 @@ abstract class Enum[E <: Enum[E]] protected (_name: String, _ordinal: Int)
   def ordinal(): Int              = _ordinal
   override def toString(): String = _name
   final def compareTo(o: E): Int  = _ordinal.compareTo(o.ordinal)
+  // equals and hashCode copied from scala.js
```
Comment (densh) [inline javalib/src/main/scala/java/lang/Enum.scala]: Given that implementation here is trivial, lets drop this comment.

Comment (cquiroz) [reply javalib/src/main/scala/java/lang/Enum.scala]: Removed the comment and rebased onto master

**Comment by densh** [comment]
LGTM, tnanks @cquiroz ! 👍
