### PR TITLE
Fix #3329: javalib MappedByteBufferImpl no longer calls FileChannel truncate method

### LINKED ISSUE #3329: javalib MappedByteBuffer uses FileChannel.truncate() to increase file sizes.
Discovered whilst studying Issue #3316.

Many version of the JDK documentation describe `FileChannel.truncate()` as not increasing
a files size.  

The current SN implementation of javalib `MappedByteBuffer` uses `FileChannel.truncate()`
to possibly "grow" a file. The current SN implementation of that method allows that. When
that implementation if fixed to follow the JDK, `MappedByteBuffer` will fail.

I encountered the problem of a newly failing `MappedByteBuffer` once `FileChannel.truncate() 
works as documented on non-Windows (tests failing in a way which slay the entire SN test runner,
without leaving a log or debug info!). 

I believe that Windows has some code which makes it robust to a "correct" `truncate()`. 

Implementation Notes:

1) This Issue should probably be fixed before `truncate()` is fixed.

2) The Windows code writes 0`s one byte at a time, it may be possible to
     reduce or eliminate that code, depending on how Windows handles
     the intervening, if any, blocks of a `sparse` file.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #3329 

###### Credit: 
Aly on Scala Native Discourse gave invaluable information on how Windows extends files.
Any defects from misinterpretation of that information fall on this Author.

##### Changes

javalib `MappedByteBufferImpl` no longer calls `FileChannel#truncate` to extend files.
The latter method is defined as never extending a file, so the former method calling
the latter was a defect.

This is primarily an internal re-organization which prepares the ground for correcting the more
visible and impactful Issue #3330.

A keen user may detect three user visible changes.
- argument checking is more extensive and stricter.  
- Message of an `IllegalArgumentException` was changed to match (a, not every) JVM.
- Thanks to Aly, the performance of extending a file on Windows should be significantly improved.

### CODE REVIEW

File: unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/nio/channels/FileChannelTest.scala [hunk 1]
```diff
@@ -296,4 +297,54 @@ class FileChannelTest {
...
+      assertEquals("lines size", 1, lines.size())
+      assertEquals("lines content", data, lines.get(0))
+
+      val channel = FileChannel.open(
+        f,
+        StandardOpenOption.READ,
+        StandardOpenOption.WRITE
+      )
+
+      try {
```
Comment (ekrich) [inline unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/nio/channels/FileChannelTest.scala:319]: You could use `Using` to manage the resource here rather than `try`, `finally`. https://www.scala-lang.org/api/2.13.6/scala/util/Using$.html

Comment (LeeTibbert) [reply unit-tests/shared/src/test/scala/org/scalanative/testsuite/javalib/nio/channels/FileChannelTest.scala:319]: Eric,  
Thank you for the suggestion.  This code needs to also run on Scala 2.12.n.   
I believe that `Using` is not available for that Scala version. `Tis a pity, 
the `Using` idiom is much closer to the Java `try-with-resources` idiom.
Did I miss something in Scala 2.12?

**Review by WojciechMazur — APPROVED** [review]
