### PR TITLE
Fix #2396: URI normalize doesn't seem to work

### LINKED ISSUE #2396: URI normalize doesn't seem to work
```scala
val uri = new URI("/a/b")
uri.normalize()
```

In JVM this returns "/a/b", in Native we get:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.Throwable.fillInStackTrace(Unknown Source)
    at java.lang.String.substring(Unknown Source)
    at java.net.URI.normalize(Unknown Source)
```

### PR DESCRIPTION
**Pull request by jchyb**
Before, it used to always throw StringIndexOutOfBoundsException. Now, related instructions have been swapped, so this should no longer be the case. Additional tests were also added.

### CODE REVIEW

File: unit-tests/shared/src/test/scala/javalib/net/URITest.scala [hunk 1]
```diff
@@ -237,4 +237,33 @@ class URITest {
     }
   }
 
+  @Test def normalize(): Unit = {
+    def testNormalize(relative: Boolean): Unit = {
+      val first = if (relative) "" else "/"
+      assertEquals(new URI(s"${first}a/b").normalize(), new URI(s"${first}a/b"))
```
Comment (WojciechMazur) [inline unit-tests/shared/src/test/scala/javalib/net/URITest.scala:243]: Please make the expected result be present on the left side of `assertEquals`, and the actual value on the right side. That's an assumption taken by JUnit, otherwise it would lead to confusing messages in the logs in case of the failed tests.

**Review by WojciechMazur — APPROVED** [review]
