### PR TITLE
Fix #360

### LINKED ISSUE #360: doubleToRawLongBits/doubleToLongBits discrepancy
As discovered by @soc:
```scala
    val x = Double.NaN
    val y = longBitsToDouble(doubleToRawLongBits(x) | 1)
    // assertNot(x == y) // FIXME this works on the JVM, but fails on native.

    val z = longBitsToDouble(doubleToLongBits(x) | 1)
    // assertNot(x == z) // FIXME this works on the JVM, but fails on native.
```

### PR DESCRIPTION
**Pull request by densh**
Review @sjrd

### CODE REVIEW

File: unit-tests/src/main/scala/scala/DoubleComparisonSuite.scala [hunk 1]
```diff
@@ -0,0 +1,323 @@
...
+  test("fcmp") {
+    // These were code-generated on the JVM using:
+    //
+    // scala> val values = Seq(("0.0d", 0.0d),
+    //                         ("-0.0d", -0.0d),
+    //                         ("Double.MaxValue", Double.MaxValue),
+    //                         ("Double.MinValue", Double.MinValue),
+    //                         ("Double.NaN", Double.NaN),
+    //                         ("42.0d", 42.0d),
+    //                         ("-42.0d", -42.0d))
```
Comment (sjrd) [inline unit-tests/src/main/scala/scala/DoubleComparisonSuite.scala]: You might want to add infinities, here. `Double.PositiveInfinity` and `Double.NegativeInfinity`.

File: unit-tests/src/main/scala/scala/FloatComparisonSuite.scala [hunk 2]
```diff
@@ -0,0 +1,324 @@
...
+  test("fcmp") {
+    // These were code-generated on the JVM using:
+    //
+    // scala> val values = Seq(("0.0f", 0.0f),
+    //                         ("-0.0f", -0.0f),
+    //                         ("Float.MaxValue", Float.MaxValue),
+    //                         ("Float.MinValue", Float.MinValue),
+    //                         ("Float.NaN", Float.NaN),
+    //                         ("42.0f", 42.0f),
+    //                         ("-42.0f", -42.0f))
```
Comment (sjrd) [inline unit-tests/src/main/scala/scala/FloatComparisonSuite.scala]: Same here.
