### PR TITLE
Fix #1008, #1528, partial #1579: unit-tests fails with more than 254 Suites

### LINKED ISSUE #1008: Running a large number of unit tests results in EOFException
When running unit tests for ScalaTest through Scala Native, a large number of tests is causing the Scala Native program to crash with the following exception:

```
[error] java.io.EOFException
[error] 	at java.lang.Throwable.init(Unknown Source)
[error] 	at java.lang.Exception.init(Unknown Source)
[error] 	at java.io.IOException.init(Unknown Source)
[error] 	at java.io.IOException.init(Unknown Source)
[error] 	at java.io.EOFException.init(Unknown Source)
[error] 	at java.io.EOFException.init(Unknown Source)
[error] 	at java.io.DataInputStream.readFully(Unknown Source)
[error] 	at java.io.DataInputStream.readFully(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.receive(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.testRunner(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMainBase.testMain(Unknown Source)
[error] 	at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
[error] 	at <none>.main(Unknown Source)
```

The crash appears to be related to the high number of unit tests, as the tests run fine when enabled individually but the exception occurs when many tests are enabled at the same time. To reproduce, comment out one of the disabled test files in GenScalaTestNative.scala in https://github.com/scalatest/scalatest/pull/1185 and run `scalatestTestNative/test`.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* Issue #1008 reported problems with unit-tests when executing
    a large number of Suites.  Issue #1528 renewed concern with
    the problem.  Issue #1579 reported a number of problems
    in java.io.DataInputStream.scala.

    This PR fixes issues #1008 and #1528 by implementing a partial
    fix to #1579.

    The partial fix removes an erroneous end-of-file (EOF) test and
    the call to the other buggy code identified in #1579 and #1578.

    It was simpler to replace readFully with correct and more performant
    code than to create PRs for the entire fault chain.

    A full fix for Issue #1579 will follow on after this PR has been
    accepted. This sequencing of edits isolates & highlights the
    effective change in this PR and, I hope, allows for easier review.

  * Because of fundamental design issues the 'too many unit-tests' experience
    may re-appear in the future, but not for this reason.

    The current protocol sends a list of tasks from the local master
    process to the 'remote' (pseudo) process running the tests.
    The latter re-orders its internal list and replies with the newly
    ordered list.  Is is easy to conceive of a situation where
    these lists exceed the bounds of memory as the number of unit-test
    Suites grows into the thousands.

    Tasks (Suites) are executed on at a time, so I see no limit to the
    number of tasks there but each task itself must stay within the
    bounds of available memory.

Documentation:

  * None needed. Unit-tests are internal to SN.

Testing:

  * In my private development environment I built and tested ("test-all")
    in debug mode with both sbt 0.13.18 & 1.2.8 (1) and the existing 254
    unit-test Suites. All ran & passed (2).

  * I then enabled the previously disabled AtomicReferenceSuite.scala,
    giving 255 tests. I ran tests/test again and all 255 ran & passed.

  * I added 10 additional Suites, giving 265 Suites. and ran tests/test.
    All tests ran & passed, including Suites 255 through 265.

  * After this PR is accepted, I will submit another one which will
    enable AtomicReferenceSuite.scala.  This should provide the
    255th test and give final validation to this PR.  That seems
    to be conceptually simpler & easier all around than my submitting 10,
    or so, dummy Suites with this PR, only to delete them in another PR.

  Note 1: I believe it is a known issue, but for completeness
          I report that sbt 1.2.8 builds in release mode but
	  compiling unit-tests fails after after a half hour or so.

  Note 2: Due to a change in sbt between 0.13 and 1.0, link-order
          never passes for me with 1.2.n.  PR #1466 fixes this issue
	  and is awaiting acceptance.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Travis CI appears stuck while compiling  scripted-tests code late in the run.

The unit-tests section affected by this PR passes with flying colors.

I will try a dummy submit tomorrow after the Travis CI folks have started
their work week    

A second, less invasive, PR which submitted today is also hanging in Travis CI,
so I think it it a Travis or sbt issue rather than something specific to these two PRs.

**Comment by densh** [comment]
I can confirm that this makes tests pass on #1426, congrats on the fix, its was a hard one to find! 👏

File: javalib/src/main/scala/java/io/DataInputStream.scala [hunk 1]
```diff
@@ -35,14 +35,21 @@ class DataInputStream(in: InputStream)
...
-    while (i < len) {
-      val value = readByte()
-      if (value == -1) throw new EOFException()
-      b(i + off) = value
-      i += 1
+    }
+
+    var offset = off
+
+    while (offset < len) {
```
Comment (densh) [inline javalib/src/main/scala/java/io/DataInputStream.scala]: I don't think this is correct. `off` argument gives and offset potentially in the middle of the array, `len` is not necessarily the length of the array but number of the bytes to read. So for example in an array with 20 elements, you can give offset 10 and length 2. This would mean that the while loop is not going to run even a single iteration.

Comment (densh) [reply javalib/src/main/scala/java/io/DataInputStream.scala]: A better version of the same code would be:
```
  override final def readFully(b: Array[Byte], off: Int, len: Int): Unit = {
    if ((off < 0) || (len < 0) || (len > b.length - off)) {
      throw new IndexOutOfBoundsException()
    }

    var offset = off
    var length = len

    while (length > 0) {
      val read = in.read(b, offset, length)

      if (read == -1) {
        throw new EOFException()
      } else {
        offset += read
        length -= read
      }
    }
  }
```

**Comment by densh** [comment]
I believe the timeout on Travis has nothing to do with this PR. 3/4 configurations completed without any problems after a restart.

**Comment by densh** [comment]
It would be nice to add a few DataInputStream tests (at least for readFully to start with), we don't seem to have any atm. You can use ByteArrayInputStream as the input to doing any actual I/O.

File: javalib/src/main/scala/java/io/DataInputStream.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/io/DataInputStream.scala]: You are absolutely correct! Space shot on my part, sorry.

I will make the suggested correction this evening (Eastern Daylight Time).

Comment (LeeTibbert) [reply javalib/src/main/scala/java/io/DataInputStream.scala]: Thank you for the correction.

**Comment by LeeTibbert** [comment]
Out of order execution. I poked Travis CI before reading the review comments.
I will implement them overnight.

**Comment by densh** [comment]
LGTM, thanks @LeeTibbert ! 👍
