### PR TITLE
Fix #2769, #2650: SN 0.4.x - remove several defects discovered by ProcessTest

### LINKED ISSUE #2769: `ProcessTest` fails on macOS-12
10/12 ProcessTests fails due to timeouts when executed on GitHub Actions macOS-12 env. 
https://github.com/scala-native/scala-native/runs/7658264104?check_suite_focus=true

### PR DESCRIPTION
**Pull request by LeeTibbert**
##### Release trains
This PR is intended for the SN 0.4.x release train. It addresses a set of bugs
which may be experienced by people in the wild attempting to use the Process class
with macOS.

It is also appropriate for 0.5.0.  After its merge into 0.5.0 I can submit
another PR removing a feature introduced in the 0.4.x stream. At that
time, it looked like some signal defects were specific to arm64 (Apple M1).
Turns out, they due to a platform independent change in macOS 12.0.

##### Changes
ProcessTest now runs cleanly on Linux, various macOS versions, and Windows. 
Its failures in CI on macOS 12.n turned out to be real problems.  Good for ProcessTest.

##### Analysis, for Reviewers & the curious
After years of documenting that `vfork()` was going to be deprecated, Apple finally
did it in macOS 12.  They deprecated `vfork()` and made it, basically, an alias
for `fork()`.  This appears to have changed timings so that a parent process can
run earlier than the child.  Always a theoretical possibility, but not the facts
on the ground.  Now they are.

Changing the timing meant that the parent could send SIGTERM to the
child before the child had executed one of the exec family.  There is 
as window in the child between fork() and exec() where a delivered
signal will execute any special signal handler of the parent (
because exec has not yet re-set them).  SN build establishes
a signal handler for SIGTERM (and others). Executing it
causes an unexpected & unwanted traceback. That 
traceback can cause concern to people reading log files.

Lastly, when SIGKILL (which can not be caught) and SIGTERM
were handled, they went through some defective code in `process_monitor.cpp`
which caused the carnage reported in @2769.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
4 multiarch failures have to do with lld not liking `deflate.c` and
unrelated to this PR.

Other than that "All Green" and ready for review.

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala [hunk 1]
```diff
@@ -179,28 +179,23 @@ object UnixProcess {
...
-         * It is unsafe to directly run any code in vfork2 on top of the parent's stack without
-         * creating a new stack frame on the child. To fix this, put all of the code that needs
-         * to run on the child before execve inside of a method.
+        /* 2022-08-06 Old unattributed requirement from prior 'vfork'
+         *     implementation. Probably from older FreeBSD documentation.
+         *     Probably unnecessary but harmless in current 'fork()'
+         *     implementation. Someday a braver soul with time on their hands
+         *     can try removing it.
+         *
+         * It is unsafe to directly run any code in vfork2 on top of the
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/process/UnixProcess.scala:193]:
```suggestion
        /* 2022-08-06 Old unattributed requirement from prior 'vfork'
         * implementation. Probably from older FreeBSD documentation.
         * Probably unnecessary but harmless in current 'fork()'
         * implementation. Someday a braver soul with time on their hands
         * can try removing it.
         *
         * It is unsafe to directly run any code in vfork2 on top of the
```

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala [hunk 2]
```diff
@@ -228,12 +223,30 @@ object UnixProcess {
               unistd.execve(c"/bin/sh", newArgv, envp)
             }
           }
-          // The spec of vfork requires calling _exit if the child process fails to execve.
+          /* Older, definitely FreeBSD requirement. No such written
+           * requirement with fork(), but it is probably good idea anyway.
+           *   // The spec of vfork requires calling _exit if the child process
+           *   // fails to execve.
+           */
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/process/UnixProcess.scala:230]:
```suggestion
          /* Older, definitely FreeBSD requirement. No such written
           * requirement with fork(), but it is probably good idea anyway.
           *
           * The spec of vfork requires calling _exit if the child process
           * fails to execve.
           */
```

**Review by ekrich — COMMENTED** [review]
Thanks for doing this - just a couple of suggestions on the comment formatting.

Does this allow all the process tests to work now?

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala (hunk 2 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala:230]: Eric, 

Than you for the timely & helpful review, especially on a hot summer afternoon.

> Does this allow all the process tests to work now?

Yes, I believe.  CI passed, with the exception of apparently unrelated
(new) multiarch failures.  It works on my machines.  It should
run on your machines. If not, let me know.

Actually `ProcessTest` was the canary, doing its job.
I fixed both underlying defects and also made `ProcessTest`
more robust to a timing assumption it was making in two places.

The initial wait could be improved by the next generation.
 I wanted to get this off the  shipping dock after having my
mind torn apart for days tracking down the defects.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala:230]: re: initial whitespace blocking in comments.  

Based on your suggestion, there may be an evolution available here.
What I was trying to achieve is to distinguish the old and the new
parts of the comment.   I could not use font (italics) and I could
not use the color of the type, so I used indentation.

I could use something like
```
/* Current comment:
 *         Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
 *         Donec tristique varius condimentum. Phasellus auctor ut lacus 
 *        eget sodales.
 *
 * Now obsolete comment:
 *        Suspendisse sed odio nec libero maximus efficitur ac ut felis. 
 *       Aliquam erat volutpat. Morbi malesuada est sit amet venenatis viverra
  */
```
I can move the "Lorem" under the "Current" and the "Suspendisse" under "Now"
or use 1 space indentation under "Lorem", etc.   

I think the old comment have some value for someone trying to follow the
series of changes or understand the changes.    

You are a fresh set of eyes. Should I just delete the old comments
and let folks use "git history"?   Anyone in this code in the future
is in a world filled with regret, so perhaps obsolete comments
will not bring much of either edification or solace.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala:230]: As I was rushing to escape this issue, I had a thought.  Perhaps using greater-than (right angle bracket) ">"
as as a quote-block character?  Something like what is done in Discourse and often in email?
Very rushed and inexact:
```
/* This is the way we do things now.
 * it is far better than what was done in the ">" quoted text below.
 *
 *  > This is the way we used to do things.
 *  > it worked for us for many a year.
 * /
```

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala]: Eric,  I re-worked the comment sections you identified.

I also got to correct the error code given to `_exit()`. 127 is
the convention for "exec failed" and gives  better clue than 1
in case failure ever happens.

Iterative improvement.

File: javalib/src/main/scala/java/lang/process/UnixProcess.scala [hunk 3]
```diff
@@ -179,28 +179,28 @@ object UnixProcess {
...
+    unistd.fork() match {
       case -1 =>
         throw new IOException("Unable to fork process")
+
       case 0 =>
-        /*
-         * It is unsafe to directly run any code in vfork2 on top of the parent's stack without
-         * creating a new stack frame on the child. To fix this, put all of the code that needs
-         * to run on the child before execve inside of a method.
+        /* The ">" quoted section below describes an unattributed requirement
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/process/UnixProcess.scala:187]: I think it is much nicer now so future people do not have to worry about alignment. It would be easier though to just document what you want to say about the function in the first paragraph and then just explain the extra stuff in order without the special quoting stuff. I'm sure you can just use paragraphs and the sentence order to explain the gotchas and legacy stuff so it makes sense. That might make it easier if somebody cleans up the code to remove the extra notes as well.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcess.scala:187]: Again, thank you for the review iteration.

My current thinking is that if we are having a hard time describing the
oddness, then I should do at least a trial of the real fix:  getting
rid of the oddness so that it does not need to be explained, remembered,
fixed, fixed-again, and maintained. I am being short/cross but not
with you, with time spent on quirks.

CI will tell us if it does not like that approach it will let us know.
Of course, I/we will only know when this stuff is widely 
exercised.

**Comment by LeeTibbert** [comment]
Eric, 

It is not time for a victory dance yet, but CI seemed to like, modulo usual suspects, my
getting rid of the 'unusual` code and the comment under discussion.   

There are also a few removals of imports and minor cleanup.  I could not help myself,
especially knowing that I will be having to read and trace this code again and sooner
than I would like.

Do you concur with the major post-fork/pre-exec changes?   If yes, review
has lead to advancement.
-----------------------------------------------------------------------------------------------------

The inline `unistd.close` code in the post-fork/pre-exec section is just begging
to be done in an for loop or relative. I believe that the current practice is that
javalib not use scala lib methods, so I held off.

Someone who is better at Java than I am could fill a java Array and 
iterate over it, closing both !Ptr and !Ptr + 1.  Using scalaOps.
The only way I know of creating and populating a Java array
is to create it and then populate index-0, index-1, etc. in
explicit code.

The simplification in concept and lines of code doing things
that way would probably not repay the effort.

If you know of a better way to fill and/or iterate over an
Array in javalib, please let me know.

**Review by WojciechMazur — APPROVED** [review]
