### PR TITLE
Fix #4395: Support for configurable C++ standard (e.g. C++17) when compiling C++ sources

### LINKED ISSUE #4395: Support for configurable C++ standard (e.g. C++17) when compiling C++ sources
## Background

I'm trying to use a **C++17-based library** (mlpack) with Scala Native and encountered a build limitation. Scala Native defaults to compiling C++ sources with `-std=c++11`:

> [https://github.com/scala-native/scala-native/blob/main/tools/src/main/scala/scala/scalanative/build/LLVM.scala#L78](https://github.com/scala-native/scala-native/blob/main/tools/src/main/scala/scala/scalanative/build/LLVM.scala#L78)

When attempting to override it using:

```scala
nativeConfig ~= { c =>
  c.withCompileOptions(c.compileOptions ++ Seq("-std=c++17"))
}
```

this results in the following error:

```
[error] error: invalid argument '-std=c++17' not allowed with 'C'
```

This happens because the flag is incorrectly applied to C sources as well, not just C++ sources. As a result, I'm unable to use any library requiring C++17 (e.g., using `if constexpr`, `std::optional`, or structured bindings)

Related issue: #2610 — it was marked resolved, but this scenario (mixed Scala Native C code + user C++17 code) still fails.

---

## Reproduction steps

I've created an **example**:
[https://github.com/pantShrey/scala-native-cpp17-issue](https://github.com/pantShrey/scala-native-cpp17-issue)

It includes the following C++ source file:

```cpp
#include <iostream>
#include <vector>

void useStructuredBinding() {
    std::vector<std::pair<int, double>> data = {{1, 1.1}, {2, 2.2}};
    for (auto& [i, d] : data) {  // C++17 structured binding
        std::cout << "i=" << i << ", d=" << d << "\n";
    }
}

extern "C" void callUseStructuredBinding() {
    useStructuredBinding();
}
```

Calling this function from Scala Native without modifying the default flags results in a C++17 compiler error. Trying to patch it using `-std=c++17` causes the global C compiler error shown above.

---

## What I expected

The ability to configure `-std=c++17` (or newer) **for `.cpp` sources only**, without breaking compilation of Scala Native’s internal `.c` files.

---

##  Questions

1. **Is it currently possible** to apply `-std=c++17` selectively only for `.cpp` sources?
2. If not, **can this feature be added** — e.g., expose a `nativeCppCompileOptions` setting?
3. Is there a **workaround**  I can use in the meantime?
4. Is there a reason `-std=c++11` is currently **hardcoded** instead of being user-configurable?

### PR DESCRIPTION
**Pull request by ekrich**
The intent here is to allow a default, and project specific settings.

This means that if someones project needs C++17 and there compiler is not new enough, things will fail. If it is the end users project wanting a newer version if should still work. We will test that out.

### CODE REVIEW

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala [hunk 1]
```diff
@@ -19,6 +19,12 @@ sealed trait NativeConfig {
   /** The compilation options passed to LLVM. */
   def compileOptions: Seq[String]
 
+  /** The compiler C version -std=XXX */
+  def compileStdC: Option[String]
+
+  /** The compiler C++ version -std=XXX */
+  def compileStdCpp: Option[String]
+
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: I'm wondering if maybe we should just follow the the Bazel convention here. 
They're having 3 attributes (settings): 
`conlyopts` -  Add these options to the C compilation command.
`copts` -  Add these options to the C/C++ compilation command.
`cxxopts` - Add these options to the C++ compilation command. 

So `copts` is already covered by `compileOptions`, we could just add 2 new settings for the other two. 
Searching for custom `-std=X` setting in LLVM is easy is relatively cheap, we can insert the defaults if there is no custom settings. 
However, it would still not fix a big bigger issue - if parts of the (Scala Native C/C++) stdlib require some version od -std, let's say `-std=c++14`, but users code or it's dependency require newer standard it would still fail. 

So maybe we can third alternative - let's define `-std` setting in the project descriptor so that we can always control our own sources - but allow users to use custom values for everything else.  We can play with order or filtering of options coming from project descriptor over these defined by user.

Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: I was thinking of allowing the the project descriptor so the internal libs or third party libs could select their minimum or required version.

I will have to look at the Bezel convention but Lee was making fun of cxx  so maybe cpp :-) But why is `copt` for both C/C++? Maybe I am missing a key point here. I wanted to make it very specific so we can add other things if needed. I can work on naming etc. once I get it going.

Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: I was looking and indeed C++ has other flags specific to C++ so I understand what you were saying about finding the std flag. I will work towards that.

**Comment by ekrich** [comment]
When adding `-fcxx-exceptions` to the `cppOptions` we do get a link.

```scala
nativeConfig ~= {
          _.withCOptions(Seq("-std=c17")).withCppOptions(Seq("-std=c++17", "-fcxx-exceptions"))
        }
```

Results:
```sh
[debug] /usr/bin/clang
[debug] 	-c
[debug] 	/Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/native/dependencies/windowslib_native0.5_3-0.5.9-SNAPSHOT-4/scala-native/windows/winnt/accessToken.c
[debug] 	-o
[debug] 	/Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/native/dependencies/windowslib_native0.5_3-0.5.9-SNAPSHOT-4/scala-native/windows/winnt/accessToken.c.o
[debug] 	-Wno-override-module
[debug] 	-std=c17
[debug] 	-fexceptions
[debug] 	-funwind-tables

[debug] /usr/bin/clang++
[debug] 	-c
[debug] 	/Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/native/dependencies/nativelib_native0.5_3-0.5.9-SNAPSHOT-0/scala-native/eh.cpp
[debug] 	-o
[debug] 	/Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/native/dependencies/nativelib_native0.5_3-0.5.9-SNAPSHOT-0/scala-native/eh.cpp.o
[debug] 	-Wno-override-module
[debug] 	-std=c++17
[debug] 	-fcxx-exceptions
[debug] 	-fexceptions
[debug] 	-funwind-tables
[debug] 	-gdwarf-4
[debug] 	-DSCALANATIVE_USING_CPP_EXCEPTIONS
```
```sh
scala-native % otool -L /Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/sandbox 
/Users/eric/workspace/scala-native/sandbox/.3/target/scala-3.7.1/sandbox:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
```

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala (hunk 1 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: The solution here was to `cOptions` and `cppOptions` - similar to the above - we already have `compileOptions` that apply to both so this seem the most sensible, and maybe better than the Bazel names.

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala [hunk 2]
```diff
@@ -456,6 +449,45 @@ private[scalanative] object LLVM {
...
+      case opts  =>
+        if (opts.exists(s => s.startsWith(stdPrefix))) opts
+        else defaultCStd +: opts
+    }
+    val exceptionHandling =
+      if (isCppRuntimeRequired(config, analysis))
+        List("-fexceptions", "-funwind-tables")
+      else Nil
+
+    options ++ exceptionHandling
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/LLVM.scala]: I think that both `--std=X` and `-std=X` formats  are valid. Probably we can also simplify it, so that here we're only add the default `-std` flag if missing. 
Also we should check for both cOptions and shared compileOptions

```suggestion
  
    val languageStandard = { 
        def isStdFlag(option: String) == option.startsWith("-std=") ||  option.startsWith("--std=") 
        val hasStdFlag = config.compilerConfig.cOptions.exists(isStdFlag) ||  config.compilerConfig.compileOptions.exists(isStdFlag)
       if (!hasStdFlag) List(defaultCstd) 
       else Nil
    }
    val exceptionHandling =
      if (isCppRuntimeRequired(config, analysis))
        List("-fexceptions", "-funwind-tables")
      else Nil

    options ++ exceptionHandling ++ languageStandard
``` 

Similary for C++ options

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala [hunk 3]
```diff
@@ -473,6 +503,8 @@ object NativeConfig {
         | - clangPP:                 $clangPP
         | - linkingOptions:          ${showSeq(linkingOptions)}
         | - compileOptions:          ${showSeq(compileOptions)}
+        | - cOptions:                $cOptions
+        | - cppOptions:              $cppOptions
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: We can use `showSeq` helper to print it as `[some, value]` instead of using collection specific toString, eg. `Seq(some, value)`

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala [hunk 4]
```diff
@@ -19,6 +19,12 @@ sealed trait NativeConfig {
   /** The compilation options passed to LLVM. */
   def compileOptions: Seq[String]
 
+  /** C only options including -std=XXX */
+  def cOptions: Seq[String]
+
+  /** C++ only options including -std=XXX */
+  def cppOptions: Seq[String]
+
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: Maybe let's make the docs here more specific, eg. `The compilation options used when compiling .cpp files, these would be merged with the generic 'compileOptions' used when compiling all sources.`.

File: tools/src/main/scala/scala/scalanative/build/NativeLib.scala [hunk 5]
```diff
@@ -95,7 +95,41 @@ private[scalanative] object NativeLib {
...
+              descOpts.exists(s => s.startsWith(LLVM.stdPrefix)) match {
+                case false => nativeConfig.withCOptions(c => c ++ descOpts)
+                case true  => {
+                  val filtOpts = nativeConfig.cOptions.filterNot(e =>
+                    e.startsWith(LLVM.stdPrefix)
+                  )
+                  nativeConfig.withCOptions(filtOpts ++ descOpts)
+                }
+              }
+          }
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/NativeLib.scala]: Why do we need this filtering? I think that in most cases clang compiler allows multiple same settings but making only the last effective, for example 
```c
#include <stdio.h>

int main(){
  printf("std version: %d", __STDC_VERSION__);
  return 0;
}
```

When compiling with `clang -std=gnu23 --std=c11 --std=gnu17 test.c ` we'd get `__STDC_VERSION__ 201710L` 

Based on that we can make a simple concatenation of settings using a fixed order from the least to the most specific: 
1. `NativeConfig.compileOptions` (the most generic) 
2. `NativeConfig.{c,cpp}Options` (more specific, language specific) 
3. `Descriptor.{c,cpp}Options` (module source specific) 

> I was thinking about adding also `Descriptor.compileOptions` for generic, shared options, but it makes no sense - we'd never use these options to compile something else then .c or .cpp files

So here we'd only append the options found in descriptor to existing NativeConfig (AFAIR it's dependency specific, each one has it's own copy), and make final concatentation (generic compileOptions + {c,cp}Options) when compiling actual sources

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala [hunk 6]
```diff
@@ -96,16 +99,6 @@ private[scalanative] object LLVM {
         config.compilerConfig.targetTriple.map(_ => s"-Wno-override-module")
       multithreadingEnabled ++ usingCppExceptions ++ allowTargetOverrrides
     }
-    val exceptionsHandling = {
-      val targetSpecific = if (isCppRuntimeRequired(config, analysis)) {
-        val opt = if (isCpp) List("-fcxx-exceptions") else Nil
-        List("-fexceptions", "-funwind-tables") ++ opt
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/build/LLVM.scala:102]: I think these are currently not propagated when compiling .ll files

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala (hunk 4 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: Agreed.

File: tools/src/main/scala/scala/scalanative/build/NativeLib.scala (hunk 5 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeLib.scala]: No, we don't need it - was just doing it to make it look cleaner for the module setting.

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala (hunk 6 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/LLVM.scala:102]: Yes, by my reading of the code.

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala (hunk 2 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/LLVM.scala]: Ok, I will rework this.  Having this `config.compilerConfig.compileOptions.exists(isStdFlag)` won't work because the std flags only work for C or C++ respectively. This is why our current setup wouldn't work.

```sh
% clang++ -std=c11 hello.cpp
error: invalid argument '-std=c11' not allowed with 'C++'
```

Also, curious if we should use `Seq` or `List` for the options. I have `Seq` now - not sure why I changed it.

File: tools/src/main/scala/scala/scalanative/build/NativeConfig.scala (hunk 3 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/NativeConfig.scala]: Fixed.

File: tools/src/main/scala/scala/scalanative/build/LLVM.scala (hunk 2 above)
Comment (ekrich) [reply tools/src/main/scala/scala/scalanative/build/LLVM.scala]: I think it looks better now.

**Review by WojciechMazur — APPROVED** [review]
