### PR TITLE
Fix generation of closure with type lambda parameters.

### LINKED ISSUE #4082: Incorrect codegen in `getkyo/kyo`
Needs to be minimized based on https://github.com/getkyo/kyo/issues/845

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #4082 
Also improves closure codegen by the usage of narrowed parameter types (previously any ref type was interpreted as `j.l.Object`)

### CODE REVIEW

File: nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala [hunk 1]
```diff
@@ -346,8 +346,16 @@ trait NirGenExpr(using Context) {
 
         val selfType = nir.Type.Ref(anonClassName)
         val methodName = anonClassName.member(funSig)
-        val paramTypes = selfType +: sigTypes
-        val paramSyms = funSym.paramSymss.flatten
+        val nirParamTypes = selfType +: sigTypes
+        val paramTypes = funSym.info.paramInfoss.flatten.drop(env.size)
+        assert(
+          sigTypes.size == paramTypes.size,
+          s"""Ammount of paramaters in NIR and AST differ:
```
Comment (lolgab) [inline nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala:353]:
```suggestion
          s"""Amount of parameters in NIR and AST differ: 
```
