### PR TITLE
Fix #4747: `genIf` incorrectly forces `Unit` type when only one branch is `Unit`

### LINKED ISSUE #4747: Regression with Pattern Matching on Union Types containing Unit
Reproduction:

```scala
type Error = Throwable

def produceUnion(succeed: Boolean): Error | Unit =
  if succeed then () else RuntimeException("error")

@main def test(): Unit =
  // Pattern A - Direct inline: WORKS 
  val directResult: Error | Unit = RuntimeException("error")
  directResult match
    case _: Unit  => println("unit")
    case e: Error => println("error")  // Correctly prints "error"

  // Pattern B - Via method: BROKEN 
  produceUnion(false) match
    case _: Unit  => println("unit")   // Always matches on Native!
    case e: Error => println("error")  // Never reached
```

Expected both patterns to print `error` (works on JS / JVM).

### PR DESCRIPTION
**Pull request by arashi01**
Fixes #4747. In `genIf`, the condition to force return type to `nir.Type.Unit` used `||` instead of `&&`. This caused union types like `Error | Unit` to lose type discrimination when one if-branch returns Unit - the entire expression was typed as Unit, discarding the non-Unit value.

Changed `isUnitType(thenp.tpe) || isUnitType(elsep.tpe)` to `isUnitType(thenp.tpe) && isUnitType(elsep.tpe)` so Unit is only forced when both branches are Unit. It looks like the change was introduced in #3644, so not sure if there is a specific use case that the current changes break.

### CODE REVIEW

**Review by arashi01 — COMMENTED** [review]
Refined to:
- Add `isNonCoercibleType` check for native types (RawPtr, RawSize, CStruct, CArray, CFuncPtr) that cannot be coerced to reference types
- Force Unit return type only when:
  1. The tree's type is Unit, OR
  2. Both branches are Unit, OR
  3. One branch is Unit and the other is a non-coercible native type
- Preserve the tree's computed LUB type when one branch is Unit and the other is a reference type (e.g., RuntimeException), enabling proper pattern matching on union types like `Error | Unit` 

This resolved the failures from the initial commit (maintains compatibility with `nonNullToCString` in CString.scala etc etc)

**Comment by arashi01** [comment]
@WojciechMazur Have a quick look when you can, since this reverts #3644 essentially on the Scala 3 code path.

File: unit-tests/shared/src/test/scala-3/scala/issues/Scala3IssuesTest.scala [hunk 1]
```diff
@@ -87,6 +87,22 @@ class Scala3IssuesTest:
     assertThrows(classOf[NullPointerException], () => useUnit(null))
   }
 
+  // Issue #4747: Union type discrimination lost when one if-branch returns Unit
+  @Test def issue4747(): Unit = {
+    import scala.issues.issue4747._
```
Comment (WojciechMazur) [inline unit-tests/shared/src/test/scala-3/scala/issues/Scala3IssuesTest.scala]: The package can be inlined here, seperate object should be only used if it's required to reproduce the issue (e.g. parts of the tests cannot be locally defined

File: nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala [hunk 2]
```diff
@@ -481,9 +481,31 @@ trait NirGenExpr(using Context) {
...
       val retty =
-        if (isUnitType(thenp.tpe) || isUnitType(elsep.tpe)) nir.Type.Unit
+        if (isUnitType(tree.tpe)) nir.Type.Unit
+        else if (isUnitType(thenp.tpe) && isUnitType(elsep.tpe)) nir.Type.Unit
+        else if (isUnitType(thenp.tpe) && isNonCoercibleType(elsep.tpe))
+          nir.Type.Unit
+        else if (isNonCoercibleType(thenp.tpe) && isUnitType(elsep.tpe))
+          nir.Type.Unit
         else genType(tree.tpe)
+
```
Comment (WojciechMazur) [inline nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala]: We shouldn't check for both intersection of both Then and Else branches - if both would be unit then at this point the expression of the whole tree would be also an Unit, so that's just an additional computation cost. 

I think that original change in https://github.com/scala-native/scala-native/pull/3644 was in fact broken. 
Here we can potentially just simplify it by just returning to state before this change: 

```scala
    def genIf(tree: If): nir.Val = {
      given nir.SourcePosition = tree.span
      val If(cond, thenp, elsep) = tree
      val retty = genType(tree.tpe)
      genIf(retty, cond, thenp, elsep)
    }
```

It would however need 1 change in nativelib to explicitlly discard non-unit value: 
```scala
diff --git a/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala b/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala
index 92e5637e4..3ca81978d 100644
--- a/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala
+++ b/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala
@@ -215,7 +215,7 @@ package object unsafe extends unsafe.UnsafePackageCompat {
     // Set null termination bytes (z.alloc does not initialize memory)
     val cstrEndRaw = elemRawPtr(cstr.rawptr, size)
     if (charSize == 1) storeByte(cstrEndRaw, 0) // most common case
-    else ffi.memset(cstrEndRaw, 0, charSize.toRawSize)
+    else ffi.memset(cstrEndRaw, 0, charSize.toRawSize): Unit
 
     cstr
   }
```

Current implementation was automatically discarding such cases which might has hidden that problem. However, all of such cases needs to be handled in the nativelib runtime as we don't want to allow the SN specific primitives (RawSize/RawPtr) to be used outside. 
Problems like that would most likekly be found early if we'd enabled `-Wvalue-discard` in the codebase (should we should do in the followups)


It might result in some additional BoxedUnit instances, but these should be eliminated by the optimizer.

Comment (arashi01) [reply nscplugin/src/main/scala-3/scala/scalanative/nscplugin/NirGenExpr.scala]: Agreed. That makes more sense. Needed a few more explicit `: Unit` declarations.

**Comment by arashi01** [comment]
@WojciechMazur 

> Also CLA check is failin, you'd need to [sign it first on this page](https://contribute.akka.io/contribute/cla/scala)

Have tried a couple of times. Keep getting a 500 Error. Although I'm pretty sure I've signed it before for other ecosystem projects in the past so its a little weird; unless it has changed.

**Comment by WojciechMazur** [comment]
> @WojciechMazur
> 
> > Also CLA check is failin, you'd need to [sign it first on this page](https://contribute.akka.io/contribute/cla/scala)
> 
> Have tried a couple of times. Keep getting a 500 Error. Although I'm pretty sure I've signed it before for other ecosystem projects in the past so its a little weird; unless it has changed.

I can see the service confirms that, not sure why the GH Actions check fails  
https://contribute.akka.io/contribute/cla/scala/check/arashi01
