### PR TITLE
PipeIO: do not "check if process exited"

### LINKED ISSUE #4544: UnixProcessGen2 hangs on process with larger stdout
#4478 refactor must have introduced or unmasked a bug, which manifested itself in scalafmt post-upgrade to v0.5.9: the pre-push hook in this repository would hang indefinitely, without any messages.

Together with @LeeTibbert, we discovered that the hang occurs when scalafmt runs `git ls-files` on the repository, to determine which files to format. After a number of debugging iterations in #4484, here's the "winning combination":
- in PipeIO, remove attempts to check if the process has exited after every read
- in GenericProcess, when we register a completion to drain stdout/stderr upon exit, make sure to do this in separate async tasks rather than sequentially (first stdout, then stderr)

In addition, the latter fix uncovered a bug in how stderr redirection (to stdout) is currently implemented, by allowing to read the merged stream from either stdout or stderr, instead of exclusively from stdout (with stderr being empty).

Thus, this is the sequence of PRs fixing all bugs discovered so far:
- #4541: [DRY] cosmetic, to avoid duplicating fixes in UserProcessGen1 as well (as the fork logic is fully identical)
- #4542: [DRY] introduce convenience methods which create and validate pipes, duplicate and validate descriptors etc.
- #4543: fix bug with stderr redirection, present a null input stream for stderr, instead of a copy
- #4540: drain stdout and stderr independently and asynchronously upon process exit
- #4539: in PipeIO, do not check for process exit after every read; also, add a failing test first, and fix it.

### PR DESCRIPTION
**Pull request by kitbellew**
This is unnecessary and might lead to a deadlock. Also add some tests which were failing before this fix.

Fixes #4544.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
> This is unnecessary and might lead to a deadlock.

From several long days of intense debugging, I think this PR should be called out as a major fix and
accomplishment.

My part of the effort was chasing a 100% reproducible deadlock on macOS, various Scala versions,
with "git ls-files --full-names".  Dynamically racing thru a number of layers, I eventually discovered
that removing the "check if process exited" check solved the deadlock.  After some dust settled,
I realized that I had also seen this change in the stream of PRs created by @kitbellew.  
My work adds evidence to the validity of that change here.

I am certain that we have enough evidence to indict, convice, & send to St. Helena that piece
of code.

**Comment by kitbellew** [comment]
@LeeTibbert @WojciechMazur fyi, this is the last step in this sequence. (however, i found more things to fix, in other commits.) i just rebased it, so it contains only its own 2 commits.

File: javalib/src/main/scala/java/lang/process/PipeIO.scala [hunk 1]
```diff
@@ -169,39 +164,36 @@ private[process] object PipeIO {
         )
       }
 
-      if (len == 0) 0
-      else {
-        try {
-          synchronized {
-            val avail = availableUnSync()
+      if (len == 0) return 0
```
Comment (LeeTibbert) [inline javalib/src/main/scala/java/lang/process/PipeIO.scala]: Author's prerogative and functionally correct.

It is time to ship this puppy but I must point out
an eyesore.

I am too much influenced by my early training to
like `return` statements in the middle of a method
that we write.  They make tracing entry and exit
conditions hellacious.

In some code ported from Java, such as JSR-166 code,
they are 'necessary' and convenient but I wouldn't and
did not here, use that idiom in code that we write.

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/PipeIO.scala]: i am not enamored of returns either, but would occasionally do them early in a method, as a way to dispose of unrelated or error conditions. will be happy to restore the indented else part, just say the word.

Comment (kitbellew) [reply javalib/src/main/scala/java/lang/process/PipeIO.scala]: actually, don't say the word. done.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/PipeIO.scala]: Thank you for listening to my grump.  I think we should ship this puppy as soon as
the test pass.    This has been a long campaign, I am impressed by the productivity
and improvements.

Not pushing for less than excellence but I have every confidence that we all will
be back here again & sooner that we like.   Not a slight of the current work, but 
rather an acknowledgement of the complexity of the area, especially with a
mono-threaded legacy.

**Comment by LeeTibbert** [comment]
I like the comprehensive set of new multi-thread oriented Tests added to `ProcessTest`.
Constrains the space which can hide bugs; but bugs are clever when it comes to survival.

**Comment by kitbellew** [comment]
@WojciechMazur once again, only the flaky windows test needs to be re-run.

**Review by WojciechMazur — APPROVED** [review]
