### PR TITLE
Only include delimcc on platforms that support continuations

### LINKED ISSUE #3885: (playdate support) delimcc.c is compiled even if Continuations isn't used
To reproduce:

1. Add this line to delimcc.c, just to make it clear that the code is being included
```diff
diff --git a/nativelib/src/main/resources/scala-native/delimcc.c b/nativelib/src/main/resources/scala-native/delimcc.c
index bd00eb6aa..dd0597d1e 100644
--- a/nativelib/src/main/resources/scala-native/delimcc.c
+++ b/nativelib/src/main/resources/scala-native/delimcc.c
@@ -1,4 +1,6 @@
 #if defined(SCALANATIVE_COMPILE_ALWAYS) || defined(__SCALANATIVE_DELIMCC)
+
+#error "this shouldn't happen!"
 #include "delimcc.h"
 #include <stddef.h>
 #include <stdio.h>

```
2. Publish a snapshot
3. Try to link an app/library, even a "hello world" or a no-op main.

Output:

```
[info] Linking (multithreadingEnabled=true, disable if not used) (322 ms)
[info] Discovered 907 classes and 5623 methods after classloading
[info] Checking intermediate code (quick) (4 ms)
[info] Multithreading was not explicitly enabled - initial class loading has not detected any usage of system threads. Multithreading support will be disabled to improve performance.
[info] Linking (multithreadingEnabled=false) (277 ms)
[info] Discovered 774 classes and 4690 methods after classloading
[info] Checking intermediate code (quick) (2 ms)
[info] Discovered 749 classes and 3668 methods after optimization
[info] Optimizing (debug mode) (156 ms)
[info] Produced 43 LLVM IR files
[info] Generating intermediate code (413 ms)
[error] /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c:3:2: error: "this shouldn't happen!"
[error] #error "this shouldn't happen!"
[error]  ^
[error] 1 error generated.
[info] Compiling to native code (1524 ms)
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[info] Total (2502 ms)
[error] Failed to compile /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c
[error] (Compile / nativeLink) Failed to compile /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c
```

Example app setup (requires a publish of `0.5.1-SNAPSHOT`): https://github.com/kubukoz/demos/compare/sn-continuations-repro?expand=1

### PR DESCRIPTION
**Pull request by JD557**
Fix #3885 by only including delimcc on platforms that support continuations.

In turn, this will only initialize continuations in platforms that support them.

### CODE REVIEW

File: nativelib/src/main/scala/scala/scalanative/meta/LinktimeInfo.scala [hunk 1]
```diff
@@ -45,6 +45,10 @@ object LinktimeInfo {
   )
   def isWeakReferenceSupported: Boolean = resolved
 
+  @resolvedAtLinktime()
+  def isContinuationsSupported: Boolean =
```
Comment (JD557) [inline nativelib/src/main/scala/scala/scalanative/meta/LinktimeInfo.scala:49]: Not sure if this should be `areContinuationsSupported`... but then shouldn't the above check also be `areWeakReferencesSupported`?

Also, hopefully the list of platforms here is correct. I assumed so because previously only Windows was excluded.

Comment (WojciechMazur) [reply nativelib/src/main/scala/scala/scalanative/meta/LinktimeInfo.scala:49]: The plural variant seems more correct, but we won't replace the already existing `isWeakReferenceSupported` for compatibility reasons. So going with either singular (for keeping convention) or plural (for correctness) is fine with me

**Review by WojciechMazur — APPROVED** [review]
