### PR TITLE
Fix #1909, #1843: Statically resolve constructors, not as virtual methods

### LINKED ISSUE #1843: AssumptionViolatedException ctor triggers runtime error in native JUnit self-tests
In `junit-runtime/src/main/scala/org/junit/AssumptionViolatedException.scala`, the `(String, Throwable)` constructor results in an unknown runtime error when running JUnit self-tests from sbt:
```
junitTestOutputsNative/test
```

The bug is only present in native JUnit self-tests. At runtime, the native test runner exits unexpectedly when the AssumptionViolation is tested. This is why the aforementioned constructor is not available at the moment. Some details:
  - The constructor is always made reachable, no matter if it is used or not. This suggests maybe some bug in the reachability analysis and/or code generation.
  - After some digging around, I found out that the one to blame is the `Throwable` argument. When the argument is changed to anything else (or removed entirely), then everything works as expected. That is, the constructor is only made reachable when used and the runtime error goes away.

### LINKED ISSUE #1909: Segmentation fault on produced binary
Let me share with you a bit strange but very simple code :

```
import java.util.Random

class RandomWrapper(impl: Random = new Random()) extends Random {
  def this(seed: Long) = {
    this()
  }
}

object Bug extends App {
  new RandomWrapper()
}
```

When I build it via M2 on my machine and try to run, it crashed with `segmentation fault`.

When I remove:
```
  def this(seed: Long) = {
    this()
  }
```

it works.

I guess it is a bug.

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1909 
Resolves #1843 

This PR fixes issue described in the linked issue. 
<del>After a few tries, the most naive fix of this problem was considered to be the most effective and non-breaking.</del>
 Original fix for this issue did not worked when `release` mode was used. New implementation generates targets based on condition with `sig` can be virtual.

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

File: tools/src/main/scala/scala/scalanative/linker/Infos.scala [hunk 1]
```diff
@@ -159,7 +159,9 @@ final class Class(val attrs: Attrs,
       }
 
     add(this)
-    subclasses.foreach(add)
+    if (sig.isVirtual || out.isEmpty) {
```
Comment (WojciechMazur) [inline tools/src/main/scala/scala/scalanative/linker/Infos.scala:162]: It's still unclear for me why the `|| out.isEmpty` condition was needed. When it's omitted program resulted in segfaults.

Comment (sjrd) [reply tools/src/main/scala/scala/scalanative/linker/Infos.scala:162]: That doesn't look good. It doesn't really make sense. Do you have any idea what kind of code pattern cause the segfault without that condition?

Comment (WojciechMazur) [reply tools/src/main/scala/scala/scalanative/linker/Infos.scala:162]: Here's one example which gives errors in Check
```
[warn]   0000  didopt def @"M17java.lang.System$D14loadPropertiesL20java.util.PropertiesEPT17java.lang.System$" : (@"T17java.lang.System$") => nothing {
[warn]   0001  %20000(%1 : @"T17java.lang.System$"):
[warn]   0002    %50001 = module @"T33scala.collection.mutable.HashMap$"
[warn]   0003    %50002 = call[(@"T33scala.collection.mutable.HashMap$") => @"T32scala.collection.mutable.HashMap"] @"M33scala.collection.mutable.HashMap$D5emptyL32scala.collection.mutable.HashMapEO" : ptr(%50001 : !?@"T33scala.collection.mutable.HashMap$")
[warn]   0004    %50003 = classalloc @"T20java.util.Properties"
[warn]   0005    %50004 = method %50003 : !?@"T20java.util.Properties", "RL32scala.collection.mutable.HashMapE"
[warn]   0006    unreachable

...
[warn]   in inst #5 : 
[warn]     can't call RL32scala.collection.mutable.HashMapE on @"T20java.util.Properties"
```

`Properties` does not have such constructor, but it extends `Hashtable` which does. It happens after optimization stage so probably it was inlined for some reason. 

It ends up with exit code 134 instead of seg fault

**Review by sjrd — APPROVED** [review]
