### PR TITLE
Fix #4352: javalib UnixProcessGen2 is now atomic

### LINKED ISSUE #4352: UnixProcessGen2 jl.Process#isAlive can block for un-acceptable lengths of time
PR #4349 attempted to drive out one devil (unwanted Exception) and appears to have introduced another.
I believe I have constructed a scenario  in my mind where `java.lang` `Process#isAlive()` can block for
minutes or longer when underpinned by `UnixProcessGen2`.

Skipping lightly over why one might have thread-safety concerns about a Java 1 method which is not described as 
thread-safe, hence needing external synchronization...   Sometimes rationality & doctrinal purity get overruled
by use in the field, especially when "but it works on JVM!".

<hr>
Later: 

I believe that `WindowsProcess` has a similar issue with  `exitStatus()`. Let me defects I introduced
and leave Windows for another day/week.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #4352 

javalib `java.lang.process` `UnixProcessGen2` now uses `java.util.concurrent.atomic` methods
to guard a possibly shared exit status.  

Previously, it `synchronized` on the `Process` instance. The current approach should be
lighter weight.  

In addition, the implementation was refactored to reduce complexity and values passed around
but not used.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
This PR is passing CI and ready for review, as time permits.

A private build of `os-lib` for SN continues to pass the `os-lib` `SubprocessTests` (and others)
when using the code of this PR.

File: javalib/src/main/scala/java/lang/process/UnixProcessGen2.scala [hunk 1]
```diff
@@ -76,29 +69,51 @@ private[lang] class UnixProcessGen2 private (
     outfds: Ptr[CInt],
     errfds: Ptr[CInt]
 ) extends UnixProcess() {
+
+  private class CachedExitValue() {
+    final val EXIT_VALUE_UNKNOWN = jl.Integer.MIN_VALUE
+
+    // Non-negative values indicate exit status is known to be that value.
+    val cached = new juc.atomic.AtomicInteger(EXIT_VALUE_UNKNOWN)
```
Comment (He-Pin) [inline javalib/src/main/scala/java/lang/process/UnixProcessGen2.scala:77]: CachedExitValue can extends the AtomicInteger to save some allocation

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcessGen2.scala:77]: Thank you for the suggestion.

I wanted to centralize all the handling of the 'cached' value in one
place so I created a class.

One could indeed save an instance allocation by having private methods
and a local variable.  Early iterations of this PR did exactly that. It reminded
me of very early Fortran II code.   I was finding that having access to the
variable spread all over the place made it very difficult to tell who as
modifying the variable and when. Having methods makes the handling
much more consistent.  It is harder to have a slightly wrong synchronization
is one (or more) places and miss it.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/process/UnixProcessGen2.scala:77]: On reading the suggestion several more times, I think I see the essence of it.
// not compiled
```
private class CachedExitValue() extends AtomicInteger(){
    final val EXIT_VALUE_UNKNOWN = jl.Integer.MIN_VALUE

    // Non-negative values indicate exit status is known to be that value.
    this.set(EXIT_VALUE_UNKNOWN)

```

That would preserve the class and indeed reduce an allocation at Process creation.

He-Pin is that code somewhat like you suggested?

Comment (He-Pin) [reply javalib/src/main/scala/java/lang/process/UnixProcessGen2.scala:77]: Yes, in Java we will use `Atomic*FieldUpdator` to save some allocation too, I'm not sure about how Scala native encoding here, but that should not have much difference.
