### PR TITLE
fix: Deadlocks in singlethreaded execution context

### LINKED ISSUE #3859: Deadlock in future without multithreading
A trivial and quite expected code can be deadlocked if build it without multithreadin.

I use  a06f46dcb9c5aa2cbb52aff298bd551f71dcfbe2 as local root and had changed definition of sandbox module to disable multithreading like this:
```diff
diff --git a/project/Build.scala b/project/Build.scala
index 26be043c2..b204cf8b7 100644
--- a/project/Build.scala
+++ b/project/Build.scala
@@ -671,7 +671,11 @@ object Build {
       .enablePlugins(MyScalaNativePlugin)
       .withNativeCompilerPlugin
       .withJUnitPlugin
-      .settings(noJavaReleaseSettings)
+      .settings(nativeConfig ~= { c =>
+          import scala.scalanative.build._
+          c.withMultithreading(false)
+        },
+        noJavaReleaseSettings)
       .dependsOn(scalalib, javalib, testInterface % "test")
 
 // Testing infrastructure ------------------------------------------------
```

Now, I made a trivial example of code
```scala
import scala.util._

import scala.concurrent._
import scala.concurrent.duration._

object Test {
  implicit val ec: ExecutionContext = ExecutionContext.global

  def main(args: Array[String]): Unit = {
    Await.result(Future.successful(1) map (_ + 1), Duration.Inf)
  }
}
```
which is deadlocked. But when multithreading is enabled, it works.

If I remove part with `map (_ + 1)` it works as well without multithreading.

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #3859 
Based on work in #3853, kept as draft until deciding the new API for Native ExecutionContext

The only changes related to this fix are in the commit 516444b03f14f2ebc546b2753ef9b523fc674bb2

### CODE REVIEW

**Comment by catap** [comment]
So, no need for user to make their own interface after all :)

File: nativelib/src/main/scala/scala/scalanative/runtime/NativeThread.scala [hunk 1]
```diff
@@ -42,16 +44,22 @@ trait NativeThread {
...
   final def park(): Unit =
-    park(0, isAbsolute = false)
+    if (isMultithreadingEnabled) park(0, isAbsolute = false)
+    else NativeExecutionContext.queueInternal.helpComplete()
 
   @alwaysinline
   final def parkNanos(nanos: Long): Unit = if (nanos > 0) {
-    park(nanos, isAbsolute = false)
+    if (isMultithreadingEnabled) park(nanos, isAbsolute = false)
+    else NativeExecutionContext.queueInternal.stealWork(nanos.nanos)
```
Comment (JD557) [inline nativelib/src/main/scala/scala/scalanative/runtime/NativeThread.scala:53]: I'm not sure if this works as expected, as `stealWork(FiniteDuration)` rounds down to the millisecond, so in a lot of situations this won't yield.

I guess this matches what's said on the javadoc, but I also see that the `WindowsThread` uses `millis.max(1).toUInt`... I don't know, maybe this is OK. 🤷

Comment (catap) [reply nativelib/src/main/scala/scala/scalanative/runtime/NativeThread.scala:53]: If we use JDK as reference implementation I’d like to point that small delay is a kind of edge case.

see: https://kirill.korins.ky/articles/sleeping-at-jvm-thread-for-a-very-short-period/ where I kept notes on that investigation

File: javalib/src/main/scala/scala/scalanative/runtime/Proxy.scala [hunk 2]
```diff
@@ -1,6 +1,8 @@
-package scala.scalanative.runtime
+package scala.scalanative
+package runtime
 
 import scala.scalanative.annotation.alwaysinline
+import scala.concurrent.duration.FiniteDuration
 
 object Proxy {
```
[the remark this answers is not in the document]
Comment (WojciechMazur) [reply javalib/src/main/scala/scala/scalanative/runtime/Proxy.scala:7]: Right, this one should be fixed, but I'll do it in follow up PR. It's actually more dangerous since it's defined in javalib which does not emit Bytecode
