### PR TITLE
Fix #4169: javalib BigDecimal#floatValue rounding case now matches JVM

### LINKED ISSUE #4169: BigDecimal to Float conversion does unwanted rounding
Steps to reproduce:
1. Save the following code into `example.sc`:
```scala
val bd = BigDecimal("1.199999988079071")
val f = bd.toFloat
println(f.toString)
println(java.lang.Float.floatToIntBits(f).toHexString)
```
2. Compile and run it using JVM:
```sh
scala-cli --power package --assembly example.sc --force -o example.jar
./example01.jar
```
The output will be:
```txt
1.1999999
3f999999
```
3. Compile and run it using Scala Native:
```sh
scala-cli --power package --native-version 0.5.6 --native example.sc --native-mode release-full --force -o example.bin
./example.bin
```
The output will be:
```txt
1.2
3f99999a
```
4. Compile and run it using Scala.js:
```sh
scala-cli --power package --js --js-mode release example.sc --force -o example.js
node ./example.js
```
The output will be:
```txt
1.1999999284744263
3f999999
```

As you can see JVM and Scala.js are right in conversion (but serialize floats to strings differently).

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #4169

javalib `BigDecimal.scala` was re-ported from Scala.js in order to pick up its fix
to Scala Native Issue  4169. 

This re-port also picks up a few other fixes in Scala.js to that class since the
last port. See Scala.js commit history for details.

### CODE REVIEW

File: javalib/src/main/scala/java/math/BigDecimal.scala [hunk 1]
```diff
@@ -1571,122 +1615,14 @@ class BigDecimal() extends Number with Comparable[BigDecimal] {
...
-        val resultBits =
-          (sign & 0x8000000000000000L) |
-            (exponent.toLong << 52) |
-            (bits & 0xfffffffffffffL)
-        java.lang.Double.longBitsToDouble(resultBits)
-      }
-    }
-  }
+  @inline private def toStringForFloatingPointValue(): String =
+    s"${unscaledValue()}e${-scale()}"
```
Comment (WojciechMazur) [inline javalib/src/main/scala/java/math/BigDecimal.scala:1625]: The transformation BigDecimal -> String -> Float/Double can be much more expensive in Scala Native when compared to JS runtime. 
The old implementation also used additional allocations, e.g. in `BigInteger.valueOf`, hwoever before merging we should at least perform some local benchmarks to compare performance and documentation purpose. 
Some simple loop with time measurement in sandbox for large number of iterations (eg. 100k) in release-fast mode should be good enough

**Comment by LeeTibbert** [comment]
Wojciech,

As always, thank you for the review and suggestions.

I am converting this to Draft because there are a number of concerns I need
to suss out.

I'd like to convince myself that making some required point edits, such as removing scalastyle comments
and adding the () used in many places by the 0.5.6 code, is worthwhile.


Skipping lightly over the well known saying: There are fools, damn fools, and (micro) benchmarkers.

I do not believe the numbers I am seeing and need to spend more time investigating.  If they are
true, the code of this PR is, across 10 million iterations, about a full microsecond slower per iteration
than the 0.5.6 code. 

Fast code or correct code, eh?

That, I believe, leads to two paths of investigation:

1) What is the reported round defect in the 0.5.6 code.  I had been hoping to avoid
     trying to figure that out.

2) In this PR code, is the time being spent in creating the String to pass to Double.parseDouble()
    or Float.parseFloat() or in those routines themselves?  If the latter, it might be because of the 
    CString creation.  That would indicate a more general concern to users of those methods.

More as I understand more. So much for simple....

**Comment by LeeTibbert** [comment]
Wojciech,

I believe that I have gotten to a point requiring an umpire's call. Can you suggest
a direction?

##### TL;DR

I recommend using the `Float.parseFloat()` and `Double.parseDouble()` approach, even 
though it currently has a performance hit of a factor of 4.

Given a small finite amount of developer time, investing that time  in fixing Issue #4176 
is highly likely to reduce the performance hit to `BD.doubleValue` & `BD.floatValue()`
and improve the performance of the current corresponding `BigInteger` methods.
In addition, the change will most likely benefit the much more highly used `BD.to*String()`
methods.

##### Background
1. As Sébastien (sjrd) noted in the corresponding Scala.js PR 4727,

  *  `BigDecimal.floatValue()` should be correct, but need not be fast.
      Using a BigDecimal to represent a float is possible but probably not frequent.

  * The corresponding `BigInteger` methods currently convert to String and use
     the `java.lang` Float & Double parse methods.  

    For Scala Native, this means that changing SN BigDecimal to use those parse methods would bring
    the performance down compared to current GitHub mainline code, but still on a par with 
    current `BigInteger` code.

2. Issue #4169 describes a defect in, at the lowest level, `BigDecimal.parseFloat()`.  I suspect 
    that a similar defect exists in `BigDecimal.parseDouble()` for some magic BigDecimal with greater
    than, 15 significant digits. To the best of my knowledge, there has been no report, of such  defect
    and, with economic time, I have not been able to find such a number. Not to succumb to 
    Fear, Uncertainty, and Doubt (FUD), having `BD.doubleValue()` use `Double.parseDouble()`
    would increase confidence in code, albeit at some performance penalty. 

##### Alternatives (non-exhaustive)

Numbered to identify, only rough priority

1. Use code of base topic: convert to String & then use `Double.parseDouble()` & `Float.parseFloat()`.

2.

**Comment by WojciechMazur** [comment]
> I recommend using the Float.parseFloat() and Double.parseDouble() approach, even
though it currently has a performance hit of a factor of 4. 

> BigDecimal.floatValue() should be correct, but need not be fast.
Using a BigDecimal to represent a float is possible but probably not frequent. 

Agree, we don't have enough enough resources to strive for perfection. Let's focus on correctness and let's move on to other topics. Thank you for making a deep analysis of this problem

**Comment by LeeTibbert** [comment]
W,

Thank you for the guidance. I'll proceed that way.

The earlier "get a rough benchmark" gave us at least having some
idea of performance impact and sets the ground for any improvements
using `StringBuilder` in a separate PR may have.

**Comment by LeeTibbert** [comment]
The one failing test is an intermittent Windows `ProcessTest#concurrentPipe`.  I think
I am finally motivated enough to fix, in another PR, the concurrency logic error in that test.

All other tests are Green.  Marking as "Ready for review".

There may be some instability in the SN Test harness itself.

**Review by WojciechMazur — APPROVED** [review]
