### PR TITLE
Fix #1925: Emit .nir files using OutputStreams rather than fixed-sized ByteBuffers.

### LINKED ISSUE #1925: Can't build scalatest's unit test via scala-2.12
I've used 8b4e4090 to try testing support scala-2.12 on real life. I've published it locally via
```
sbt ++2.11.12 publishLocal 
sbt ++2.12.12 publishLocal 
```

After that I've switched scalatests to using `0.4.0-SNAPSHOT`. You can find code here: https://github.com/catap/scalatest/tree/scala-native-2.12

The next step is try to pass scalatest's unit test. It fails on `test:compile` with trace:
```
[error] java.nio.BufferOverflowException
[error] 	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
[error] 	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putBytes(BinarySerializer.scala:61)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putUTF8tring(BinarySerializer.scala:57)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putSig(BinarySerializer.scala:260)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putOp(BinarySerializer.scala:353)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putInst(BinarySerializer.scala:119)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$putInsts$1(BinarySerializer.scala:109)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$putInsts$1$adapted(BinarySerializer.scala:109)
[error] 	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error] 	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putSeq(BinarySerializer.scala:46)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putInsts(BinarySerializer.scala:109)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.putDefn(BinarySerializer.scala:218)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$serialize$3(BinarySerializer.scala:31)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.$anonfun$serialize$3$adapted(BinarySerializer.scala:29)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error] 	at scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:242)
[error] 	at scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:148)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at scala.scalanative.nir.serialization.BinarySerializer.serialize(BinarySerializer.scala:29)
[error] 	at scala.scalanative.nir.serialization.package$.serializeBinary(package.scala:16)
[error] 	at scala.scalanative.nscplugin.NirGenFile.$anonfun$genIRFile$1(NirGenFile.scala:34)
[error] 	at scala.scalanative.nscplugin.NirGenFile.$anonfun$genIRFile$1$adapted(NirGenFile.scala:33)
[error] 	at scala.scalanative.io.package$.withScratchBuffer(package.scala:16)
[error] 	at scala.scalanative.nscplugin.NirGenFile.genIRFile(NirGenFile.scala:33)
[error] 	at scala.scalanative.nscplugin.NirGenFile.genIRFile$(NirGenFile.scala:32)
[error] 	at scala.scalanative.nscplugin.NirGenPhase.genIRFile(NirGenPhase.scala:12)
[error] 	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$7(NirGenPhase.scala:99)
[error] 	at scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$7$adapted(NirGenPhase.scala:97)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.foreach(ParHashMap.scala:80)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
[error] 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error] 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error] 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error] 	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error] 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error] 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

You can reproduce it by:
```
sbt ++2.12.12 clean
sbt ++2.12.12 scalatestTestNative/test:compile
sbt ++2.12.12 scalatestTestNative/test
```

I also had modified `.jvmopts` to use `-Xmx16G` because it requires a lot of memory to build unit tests.

When I try to do it on `2.11.12` it works fine.

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1925 

<del>This PR add support for additional `ByteBufferPool`s used when standard buffer pool is not big enough to execute given function. 
Also added support for setting buffers size using System property `scala.native.bufferpool.size.<pool_name>` allowing users to make ad hoc tuning depending from their platform or project. </del> 

This PR changes `BinarySerialization` implementaiton to use `ByteArrayOutputStream` instead of `ByteBuffer`s,  same way as it's done in scala.js.
Since `ByteBufferPool` is no longer in use anywhere it was removed from the project.

### CODE REVIEW

**Comment by sjrd** [comment]
Hum, I don't like this, TBH. This feels like a workaround instead of addressing the root problem.

The root problem here IMO is that the NIR serializer takes a fixed `ByteBuffer`. It is not able to adjust the size of the byte buffer if it needs more space. We shouldn't be "trying" to serialize something and retry with a bigger buffer if the first one is not large enough. Instead we should serialize to something that can grow as needed.

A solution would be to use an `OutputStream` instead of a `ByteBuffer`. We can give it a `ByteArrayOutputStream`, or possibly even directly a `BufferOutputStream(FileOutputStream)` since we're going to send to a file anyway.

File: util/src/main/scala/scala/scalanative/io/package.scala [hunk 1]
```diff
@@ -1,22 +1,26 @@
...
-  private val pool = new ByteBufferPool
-
-  def withScratchBuffer(f: ByteBuffer => Unit): Unit = {
-    val buffer = pool.claim()
-    buffer.clear
-    try f(buffer)
-    finally pool.reclaim(buffer)
+  private val namedPools: List[NamedPool] = List(
+    "small" -> 8 * 1024 * 1024,
+    "large" -> 40 * 1024 * 1024
```
Comment (catap) [inline util/src/main/scala/scala/scalanative/io/package.scala:16]: and at some point you added `"huge"` and `"impossible"` size when someone try to compile very big and complicated file?

I do have files like, but I don't move forward to it yet :)

This files requires 60Gb heap to be compiled via scala-native, when scala and scala-js working fine on default settings.

=> I really afraid to increase this buffer size.

Comment (WojciechMazur) [reply util/src/main/scala/scala/scalanative/io/package.scala]: Yeah, that was not the best solution. It should work better with battle-tested solution used in scala.js using OutputStreams

**Review by catap — APPROVED** [review]
I'd love to confirm that I can't reproduce https://github.com/scala-native/scala-native/issues/1925 on this branch.

Also scala-native starts to use less memory to compile. That's a good news.

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenFile.scala [hunk 2]
```diff
@@ -29,10 +27,8 @@ trait NirGenFile { self: NirGenPhase =>
...
-  def genIRFile(path: Path, defns: Seq[nir.Defn]): Unit =
-    withScratchBuffer { buffer =>
-      serializeBinary(defns, buffer)
-      buffer.flip
-      VirtualDirectory.local(path.getParent).write(path, buffer)
-    }
+  def genIRFile(path: Path, defns: Seq[nir.Defn]): Unit = {
+    val outStream = new FileOutputStream(path.toFile)
+    serializeBinary(defns, outStream)
+  }
```
Comment (catap) [inline nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenFile.scala:33]: At another hand this code has at least one issue: you never close `outStream` and it is possibly that sbt gets Too Many Open Files.

Trivial changes fixes the code:
```
    val outStream = new FileOutputStream(path.toFile)
    try {
      serializeBinary(defns, outStream)
    } finally {
      outStream.close()
    }
```

File: nir/src/main/scala/scala/scalanative/nir/Prelude.scala [hunk 3]
```diff
@@ -29,11 +30,12 @@ object Prelude {
...
+  def writeTo(out: DataOutputStream, prelude: Prelude): DataOutputStream = {
     val Prelude(magic, compat, revision, hasEntryPoints) = prelude
-    buffer.putInt(magic)
-    buffer.putInt(compat)
-    buffer.putInt(revision)
-    buffer.put((if (hasEntryPoints) 1 else 0).toByte)
+    out.writeInt(magic)
+    out.writeInt(compat)
+    out.writeInt(revision)
+    out.write((if (hasEntryPoints) 1 else 0).toByte)
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/Prelude.scala:38]:
```suggestion
    out.writeBoolean(hasEntryPoints)
```

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala [hunk 4]
```diff
@@ -3,18 +3,31 @@ package nir
...
+    write => put,
+    writeDouble => putDouble,
+    writeFloat => putFloat,
+    writeInt => putInt,
+    writeChar => putChar,
+    writeLong => putLong,
+    writeShort => putShort
+  }
+  import bufferUnderyling.currentPosition
+  def serialize(defns: Seq[Defn], outputStream: OutputStream): Unit = {
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala:30]: We deserve a blank line, here.
```suggestion
  import bufferUnderyling.currentPosition
  
  def serialize(defns: Seq[Defn], outputStream: OutputStream): Unit = {
```

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala [hunk 5]
```diff
@@ -29,23 +42,23 @@ final class BinarySerializer(buffer: ByteBuffer) {
...
+      }
 
-    positions.zip(offsets).map {
-      case (pos, offset) =>
-        buffer.position(pos)
-        putInt(offset)
-    }
-    buffer.position(end)
+    bufferUnderyling.writeTo(outputStream)
+    buffer.flush()
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala:61]: These two need to be reversed, otherwise `flush()` is futile:
```suggestion
    buffer.flush()
    bufferUnderyling.writeTo(outputStream)
```

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenFile.scala (hunk 2 above)
Comment (sjrd) [reply nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenFile.scala:33]: Indeed, we definitely need to `try ... finally outStream.close()` here.

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]
