### PR TITLE
Fix #1768: Handle segfault when current directory was unlinked

### LINKED ISSUE #1768: Segfault when current directory unlinked
Hi.

# Steps to reproduce:

1. compile 

```scala
object Main {
  def main(args: Array[String]): Unit = {
    java.nio.file.Paths.get(".")
  }
}
```

2. run

```console
$ mkdir testdir
$ cd testdir
$ rm -r ../testdir
$ project-out
[1]    24245 segmentation fault (core dumped)  project-out
```

I fixed this for my private branch here: https://github.com/avdv/scala-native/commit/939a12916ba5e25e3d7b1603b5d65cfd4e23cbd9

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1768 
I've imported fix of https://github.com/avdv/scala-native/commit/939a12916ba5e25e3d7b1603b5d65cfd4e23cbd9 mentioned in issue. 
I have no idea how to provide valid tests for this case. I don't think i can be done using scripted-tests either.

### CODE REVIEW

**Comment by sjrd** [comment]
> I have no idea how to provide valid tests for this case. I don't think i can be done using scripted-tests either.

Did you test it manually using the reproducing steps in #1768, at least?

File: javalib/src/main/scala/scala/scalanative/nio/fs/UnixFileSystemProvider.scala [hunk 1]
```diff
@@ -137,7 +138,8 @@ class UnixFileSystemProvider extends FileSystemProvider {
 
   private def getUserDir(): String = {
     val buff = stackalloc[CChar](4096)
-    val res  = unistd.getcwd(buff, 4095)
+    val res = unistd.getcwd(buff, 4095)
+    if (res == null) throw UnixException("Could not determine current working directory", errno.errno)
```
Comment (sjrd) [inline javalib/src/main/scala/scala/scalanative/nio/fs/UnixFileSystemProvider.scala:142]: Coding style nitpick: IMO it's better to always put statements and exceptions (with type `Unit` and `Nothing`) as separate lines in `if`s and `while`s. That makes them more visible.
```suggestion
    if (res == null)
      throw UnixException("Could not determine current working directory", errno.errno)
```

**Comment by WojciechMazur** [comment]
> > I have no idea how to provide valid tests for this case. I don't think i can be done using scripted-tests either.
> 
> Did you test it manually using the reproducing steps in #1768, at least?

Yes, I've check it out. 
Here's stack trace that would be produced 
```[wojciechmazur@localhost]~/projects/scala-native/test_1768% ~/projects/scala-native/scala-native/sandbox/target/scala-2.11/sandbox-out
java.nio.file.NoSuchFileException: Could not determine current working directory
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.nio.fs.UnixException$.apply(Unknown Source)
        at scala.scalanative.nio.fs.UnixFileSystemProvider.getUserDir(Unknown Source)
        at scala.scalanative.nio.fs.UnixFileSystemProvider.fs$lzycompute(Unknown Source)
        at scala.scalanative.nio.fs.UnixFileSystemProvider.getFileSystem(Unknown Source)
        at java.nio.file.FileSystems$.fs$lzycompute(Unknown Source)
        at java.nio.file.FileSystems$.getDefault(Unknown Source)
        at java.nio.file.Paths$.fs$lzycompute(Unknown Source)
        at java.nio.file.Paths$.get(Unknown Source)
        at Test$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

instead of previous 
```
zsh: segmentation fault (core dumped)  ~/projects/scala-native/sandbox/target/scala-2.11/sandbox-out
```
