### PR TITLE
Fix #3707: javalib Inet6Address#hashCode is now more robust to null hostnames

### LINKED ISSUE #3707: java.net.Inet6Address hashCode method should be robust to null hostnames
The following code should succeed.

```
val addr6_1 = Inet6Address.getByAddress(null, addrBytes,  6)
addr6_1.hashCode()
```
Instead the `hashCode()` invocation gives a NullPointerException (NPE). Oops!

Note that the hostname is a null, not an empty string.  

Folks passing nulls around, Java style, is why we can not have nice things.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #3707: 

javalib `Inet6Address#hashCode` is now more robust to null hostnames.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
I believe this PR is ready for review.

As per usual, I reviewed the logs of the failing tests.  Those failures are the usual suspects.

File: javalib/src/main/scala/java/net/Inet6Address.scala [hunk 1]
```diff
@@ -45,7 +45,8 @@ final class Inet6Address private (
   override def hashCode(): Int = {
     var res = 1
     res = 31 * res + ju.Arrays.hashCode(ipAddress)
```
Comment (He-Pin) [inline javalib/src/main/scala/java/net/Inet6Address.scala:47]: Ipaddress can be null too

**Review by He-Pin — APPROVED** [review]
Lgtm

File: javalib/src/main/scala/java/net/Inet6Address.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/net/Inet6Address.scala:48]: Good catch!  Thank you.

It is not evident to a reviewer and certainly not to me when I wrote it, but `ju.Arrays.hashCode(null)`
always returns 0. That is both robust sensible.  

I added a comment to remind myself and others who try to verify that method in the future.

Dratted nulls!

**Comment by LeeTibbert** [comment]
I believe this PR is ready for review.

As is my practice, I examined the log files of the tests which have completed as of the end
of this sprint:  usual offenders.

**Review by WojciechMazur — APPROVED** [review]
