### PR TITLE
Fix #1496: Encode Strings in NIR as char code units instead of UTF-8

### LINKED ISSUE #1496: Bad values in Strings created from constants with Unicode high surrogate characters.
This is an issue discovered whilst attempting to port re2s to SN. Specifically, it
was revealed by a new test for Character.charAt() in CharacterSuite.scala.

SN 0.4.0-Snapshot appears to mangle strings containing Unicode high surrogate characters.
That is given a declaration of the form ` val str1 = "eo\uDBFFl"` (last value is an ell) 
 the value at index 2 is the expected 56319 in Scala JVM and the, I believe, incorrect
63 in SN.  

I was really testing high surrogates at the end of the line, but this  is a better example.

This may be a specific case of a more general problem.

I believe the problem is in the conversion of the string to array values, that is, the load,
not the reading of the array locations.,  When I manually load the location with
the expected value, all proceeds in SN as expected.

Strings containing 'normal' unicode, such as the euro-sign, seem to be handled OK.

I have not dived into the code to try to figure out where the problem may lie.
I would probably start looking at constructors for String(). (Duh!)

I am using bleeding edge SN, so this may be a transient.

JVM behavior:
```
scala>   val str1 = "eo\uDBFFl" 
str1: String = eo?l
scala> str1(0)
res0: Char = e
scala> str1(1)
res1: Char = o
scala> str1(2)
res2: Char = ?
scala> str1(2).toInt
res3: Int = 56319    // <<< LeeT this is the expected value
scala> str1(3).toInt
res4: Int = 108

```
SN behavior:
```
 LeeT Debug 3: codePointAt. seq(0) is e
[info] LeeT Debug 3: codePointAt. seq(1) is o
[info] LeeT Debug 3: codePointAt. seq(2) is ?
[info] LeeT Debug 3: codePointAt. seq(3) is l
[info] 
[info] LeeT Debug 3: codePointAt. index: 2  is 63
[info] LeeT Debug 3: codePointAt. limit  is 4
[info] LeeT Debug 3: codePointAt. seq.length is 4

```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1496 
This PR fixes encoding of string in NIR files. Each `Val.String` is encoded as `List[Char]` which is equal to list of code points of chars. 
Previous implementation encoded `Val.String` as UTF-8 string which resulted in data loss e.q in case of Unicode surrogate pairs.
Legacy encoding/decoding methods `putString`/`getString` where replaced with `putASCIIString`/`getASCIIString`. They're still used while encoding names (`Sig`, `Global` etc.) which are always ASCII strings. Thanks to that size of NIR files should not change.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Wojcieck,

Than you for the fix. In reading through the changed files, I noticed, with appreciation, that you 
also fixed the two testFails in the test suite. You also fixed the blunder/cut&paste_error, I mistakenly left
in one of the cases

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala [hunk 1]
```diff
@@ -40,10 +41,18 @@ final class BinaryDeserializer(buffer: ByteBuffer) {
...
   private def getString(): String = {
-    new String(getBytes(), "UTF-8")
+    if (prelude.revision < 7) getASCIIString()
+    else {
+      val chars = Array.fill(getInt)(getChar)
+      new String(chars)
+    }
+  }
+
+  private def getASCIIString(): String = {
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:52]: This should definitely be called `getUTF8String()` if it reads in UTF-8. ASCII is another charset.

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala [hunk 2]
```diff
@@ -40,10 +41,18 @@ final class BinaryDeserializer(buffer: ByteBuffer) {
 
   private def getInts(): Seq[Int] = getSeq(getInt)
 
-  private def getStrings(): Seq[String] = getSeq(getString)
   private def getString(): String = {
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:44]: It seems that this method is now only used in one place, namely the `case T.StringVal` at the end of the file. I suggest inlining it there, so that it's obvious that its logic is only relevant for string literals, and nothing else.

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala [hunk 3]
```diff
@@ -53,9 +53,12 @@ final class BinarySerializer(buffer: ByteBuffer) {
 
   private def putInts(ints: Seq[Int]) = putSeq[Int](ints)(putInt(_))
 
-  private def putStrings(vs: Seq[String]) = putSeq(vs)(putString)
-  private def putString(v: String) = putBytes {
-    v.getBytes("UTF-8")
+  private def putASCIIString(v: String) = putBytes {
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala:56]: Likewise, this method should be called `putUTF8String`

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala [hunk 4]
```diff
@@ -53,9 +53,12 @@ final class BinarySerializer(buffer: ByteBuffer) {
...
+    v.getBytes(StandardCharsets.UTF_8)
+  }
+  private def putString(v: String) = {
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinarySerializer.scala:59]: And likewise, this can be inlined in the `case Val.String`.

**Review by sjrd — CHANGES_REQUESTED** [review]
In addition to enabling the previously failing tests, we should have dedicated tests that make sure we can have string literals with all combinations of unpaired surrogates:
* low surrogate at the beginning
* high surrogate at the end (this is the only case exercised by the enabled tests)
* high surrogate followed by non-surrogate and followed by high surrogate
* low surrogate preceded by non-surrogate and preceded by low surrogate

**Review by sjrd — APPROVED** [review]
