### PR TITLE
Fix #3754: javalib ZipOutputStream#finish can now finish twice in a row

### LINKED ISSUE #3754: Null Pointer Exception in javalib ZipOutputSteam
javalib `java.util.zip.ZipOutputStream` throws a `NullPointerException`  when calling `finish()` and then `close()`.
By inheritance, `JarOutputStream` probably does the same thing.  

`finish()` is documented in the Java API and the sequence works when running the private test using the JDK.
(much merit & praise to those who gave the SN unit-tests the ability to run on both JDK and SN).

Now, the disputatious or minimalist might rightly ask "Doing something after a finish() is pretty
silly/questionable/smelly. Why would you ever call finish() and then close() and not just call
close() by itself?" `close()` is not documented to call `finish()`, although one would expect it to do so.
The JVM documentation also gives a somewhat cryptic use case: 
`Use this method when applying multiple filters in succession to the same output stream.`
Now that sounds like a recipe for happiness.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #3754

The javalib `java.util.zip.ZipOutputStream#finish` method now matches JVM behavior in
that it can be called more than once, say be a "finish(); close()" sequence, without throwing
a Null Pointer Exception (NPE).

### CODE REVIEW

File: javalib/src/main/scala/java/util/zip/ZipOutputStream.scala [hunk 1]
```diff
@@ -123,35 +123,35 @@ class ZipOutputStream(_out: OutputStream, charset: Charset)
   }
 
   override def finish(): Unit = {
-    if (out == null) {
+    if (out == null)
       throw new IOException("Stream is closed")
```
Comment (ekrich) [inline javalib/src/main/scala/java/util/zip/ZipOutputStream.scala:127]: The JVM throws `IOException` if the stream is closed/null first? Maybe a test for that is appropriate.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/util/zip/ZipOutputStream.scala]: Good suggestion.

I confirmed that JVM throws an IOException there, then added the Test you suggested.
Understanding the ultimate futility of matching JVM Exception message text, I changed the
SN text in 8 places. 

Maybe re-running CI with these changes will bring me better luck.  Roll those dice!

**Comment by LeeTibbert** [comment]
All test runs are happy, except my good pal multiarch.

Ready for review.

**Review by WojciechMazur — APPROVED** [review]

**Comment by ekrich** [comment]
Thanks Lee!
