### PR TITLE
[runtime] Fix materialization of lazilly collected stack traces

### LINKED ISSUE #4526: Incorrect exception stacktraces
Since 0.5.9, exception stacktraces are incorrect with the specific configuration Cats Effect tests are using. All the lines are like this: `at <none>.(Unknown Source)`. The configuration option turning on the problem seems to be `.generateFunctionSourcePositions(false)`. (Interestingly, I think we set that to `false` because on 0.5.8 `true` caused segfualts for us.)

Repro: #4524. Problem exists at least on ARM64 and x86_64 Linux.

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #4526  

Fix materialization of stack traces when debug symbols are not available  (add dedicated tests) 
Try to reenabled lazy stacktraces on Windows and 32bit architectures

### CODE REVIEW

File: nativelib/src/main/resources/scala-native/platform/windows/unwind.c [hunk 1]
```diff
@@ -2,10 +2,13 @@
 #if defined(_WIN32)
 
 #define WIN32_LEAN_AND_MEAN
-#include "platform/unwind.h"
+// clang-format off
+// windows.h must be included before dbghelp.h
+#include <windows.h>
```
Comment (ekrich) [inline nativelib/src/main/resources/scala-native/platform/windows/unwind.c:7]: This is interesting as I just was working on a C library ekrich/exip and found this which is similar - https://github.com/ekrich/exip/commit/fa9f7839542c293e3e1d815fa0da1e3c4418cbd2#diff-0e20d50b866c726d42d4d988bd902b7b4d38917be99fa38ee91a97cb50af0999R21-R24
This was for a Zoul compile on contiki-ng.
