### PR TITLE
Homogenises numeric exception messages

### LINKED ISSUE #2125: Integer.parseInt NumberFormatException error message
### JVM

```
scala> java.lang.Integer.parseInt("foo")
java.lang.NumberFormatException: For input string: "foo"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.lang.Integer.parseInt(Integer.java:615)
```

### scala-js

https://github.com/scala-js/scala-js/blob/465a7645f06325ff9785bb2529c20ebd48ca3df8/javalanglib/src/main/scala/java/lang/Integer.scala#L79-L80

### scala-native

https://github.com/scala-native/scala-native/blob/b9b83c63323fb42e96d243a04bebc8a65f30669b/javalib/src/main/scala/java/lang/Integer.scala#L331-L335

😢 
missing `"For input string: ` and double quotes.

Maybe not only `java.lang.Integer` but also `java.lang.Long` etc...

### PR DESCRIPTION
**Pull request by ncordon**
Closes #2125

Integer, Long and Short parsing / decoding exception messages were a little bit different from the ones JVM gives. I've tried to armonise those with respect to the ones JVM gives.

For example `Integer.parseInt("234.4")` was producing `java.lang.NumberFormatException:` rather than `java.lang.NumberFormatException: For input string: "234.4"`. That has been fixed now.

There are cases where we just would not have the same error message. For example for `Integer.decode("0xh")` we would produce:

```
java.lang.NumberFormatException: For input string: "0xh"
```

rather than

```
java.lang.NumberFormatException: For input string: "h"
```

which raises the question of up to what point do we want exactly equal error messages. 

The intent of this PR is leaving those in a better state than they were before, plus addresses some bugs in the decode methods (see comments below)

### CODE REVIEW

File: javalib/src/main/scala/java/lang/Integer.scala [hunk 1]
```diff
@@ -207,15 +207,22 @@ object Integer {
...
+    if (length == 0) fail(nm)
 
     var i        = 0
     var first    = nm.charAt(i)
     val negative = first == '-'
-    if (negative) {
-      if (length == 1) throw new NumberFormatException(nm)
+    val positive = first == '+'
+
+    if (negative || positive) {
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Integer.scala:224]: We were producing an error for `decode("+1324")` when that's a valid input

File: javalib/src/main/scala/java/lang/Integer.scala [hunk 2]
```diff
@@ -296,22 +303,22 @@ object Integer {
...
-      throw new NumberFormatException()
-    }
+    if (s == null)
+      throw new NumberFormatException("null")
+    if (radix < Character.MIN_RADIX)
+      throw new NumberFormatException(
+        s"radix $radix less than Character.MIN_RADIX")
+    if (radix > Character.MAX_RADIX)
+      throw new NumberFormatException(
+        s"radix $radix greater than Character.MAX_RADIX")
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Integer.scala:313]: Break downs in the different type of errors

File: javalib/src/main/scala/java/lang/Long.scala [hunk 3]
```diff
@@ -200,51 +200,48 @@ object Long {
...
-        }
+    var i          = 0
+    var firstDigit = nm.charAt(i)
+    val negative   = firstDigit == '-'
+    val positive   = firstDigit == '+'
 
-        i += 1
-        firstDigit = nm.charAt(i)
-      }
+    if (negative || positive) {
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Long.scala:217]: Again, this was a bug, if the long was preceded by `+` we were not decoding it correctly

File: javalib/src/main/scala/java/lang/Long.scala [hunk 4]
```diff
@@ -200,51 +200,48 @@ object Long {
...
       }
-
-      valueOf(parse(nm, i, base, negative))
+    } else if (firstDigit == '#') {
+      i += 1
+      if (i == length) fail(nm)
+      base = 16
     }
+
+    valueOf(parse(nm, i, base, negative))
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Long.scala:244]: This block has not changed apart from failing with the standard `fail` message that includes the `For input string: "$nm"`. But it has been taken out of an else (and we fail fast instead)

File: unit-tests/src/test/scala/java/lang/IntegerTest.scala [hunk 5]
```diff
@@ -18,6 +19,96 @@ class IntegerTest {
   val unsignedMaxValueText   = "4294967295"
   val unsignedMaxPlusOneText = "4294967296"
 
+  @Test def decodeTest(): Unit = {
```
Comment (ncordon) [inline unit-tests/src/test/scala/java/lang/IntegerTest.scala:22]: This test was missing

File: unit-tests/src/test/scala/java/lang/ShortTest.scala [hunk 6]
```diff
@@ -0,0 +1,188 @@
+package java.lang
```
Comment (ncordon) [inline unit-tests/src/test/scala/java/lang/ShortTest.scala:1]: `Short` did not seem to be tested at all. Caught a few small bugs doing the tests

File: javalib/src/main/scala/java/lang/Long.scala [hunk 7]
```diff
@@ -200,51 +200,48 @@ object Long {
...
+      if (i == length) {
+        return valueOf(0L)
+      }
 
-        firstDigit = nm.charAt(i)
-        if (firstDigit == 'x' || firstDigit == 'X') {
-          if (i == length) {
-            throw new NumberFormatException(nm)
-          }
-          i += 1
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Long.scala:233]: This was a small bug. If we check the length after increasing the counter, we are never going to output the exception because the length was just 2 (e.g. input `0x` or `0X`)

File: javalib/src/main/scala/java/lang/Long.scala [hunk 8]
```diff
@@ -200,51 +200,48 @@ object Long {
...
-          base = 16
-        } else {
-          base = 8
-        }
-      } else if (firstDigit == '#') {
-        if (i == length) {
-          throw new NumberFormatException(nm)
-        }
```
Comment (ncordon) [inline javalib/src/main/scala/java/lang/Long.scala:241]: Same, we are checking the length against `i = 0` here, that was going to always be false because or first digit is `#`. So the counter needed to be increased before checking for the length.

**Review by WojciechMazur — CHANGES_REQUESTED** [review]
Changes to logic look good to me, however, we should change formatting in tests to use `assertEquals` instead of `assertTrue` to get more information in case of failures.

**Comment by LeeTibbert** [comment]
@ncordon Thank you for the detailed work. The original Issue was one where it makes a user question the
underlying quality of Scala Native: if something so simple is wrong, what else is wrong.  You solved that
issue and expanded to fix an entire class of related bugs: good work!

I gave the changed files a rapid, first read and nothing stood out. I did notice that you figured out the 
JUnit "assertThrowsAnd()".  I had used the SN equivalent many times, but had stumbled when
trying to translate those to the JUnit idiom and never took the time to run it to ground (story of my
life).  I will use your code as a "how to do it" model.

I hope to do a line by line review later today or tomorrow. I expect to find nothing, so I am 
fine if this gets merged with Wojciech's suggested edits.  For historical reasons, the
prior art in those files was misdirection, a.k.a. technical debt. Sorry it caught you.

Just to show that I am reading, I suggest a small change to the title 
"Homogenaises" -> "Homogenises"

File: unit-tests/src/test/scala/utils/ThrowsHelper.scala [hunk 9]
```diff
@@ -12,4 +13,11 @@ object ThrowsHelper {
     val c = cond(expectThrows(expectedThrowable, code))
     assert(c)
```
Comment (ncordon) [inline unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: Even if I changed this for an `assertEquals` it would not give rich enough error messages, so I decided to add another helper here

File: unit-tests/src/test/scala/java/lang/IntegerTest.scala [hunk 10]
```diff
@@ -18,6 +19,96 @@ class IntegerTest {
...
+    import Integer.decode
+
+    assertTrue(decode("-1") == -1)
```
[the remark this answers is not in the document]
Comment (ncordon) [reply unit-tests/src/test/scala/java/lang/IntegerTest.scala]: Done!

File: unit-tests/src/test/scala/java/lang/IntegerTest.scala [hunk 11]
```diff
@@ -18,6 +19,96 @@ class IntegerTest {
...
+    assertTrue(decode("-0173") == -123)
+    assertTrue(decode("+0173") == 123)
+    assertTrue(decode("0173") == 123)
+    assertTrue(decode("-00") == 0)
+    assertTrue(decode("+00") == 0)
+    assertTrue(decode(signedMaxValueText) == signedMaxValue)
+    assertTrue(decode(signedMinValueText) == signedMinValue)
+
+    assertThrowsAnd(classOf[NumberFormatException], decode(null)) {
+      _.toString == "java.lang.NumberFormatException: null"
```
[the remark this answers is not in the document]
Comment (ncordon) [reply unit-tests/src/test/scala/java/lang/IntegerTest.scala]: I've added another small helper to test the error messages a little better

File: unit-tests/src/test/scala/utils/ThrowsHelper.scala (hunk 9 above)
Comment (ekrich) [reply unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: We really shouldn't use that method or add additional methods to the helper - `@deprecated` probably should have been added to this `object`. This was added because we changed all the tests to JUnit and there were some many tests with this pattern we added the method to ease the transition. Notice the comment. https://github.com/scala-native/scala-native/blob/master/unit-tests/src/test/scala/utils/ThrowsHelper.scala

Even the `assertThrows` from the `AssertThrows` object is planned to be removed as in this issue: https://github.com/scala-native/scala-native/issues/1881

Comment (ncordon) [reply unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: Any suggestions to test the exception message?

Comment (ekrich) [reply unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: I would suggest calling a helper function that calls `expectThrows` and calls `getMessage` on the exception.
https://github.com/scala-native/scala-native/blob/master/unit-tests/src/test/scala/utils/AssertThrows.scala#L78-L79 Maybe something like this.
```Scala
def exc(s: String): String = {
  val e = expectThrows(classOf[NumberFormatException], decode(s))
  val msg = e.getMessage()
  // could parse off: For input string: "-" to just get the "-" back
  msg
}

assertEquals("""For input string: "-"""", exc("-"))
```
Something like this anyway.

Comment (ncordon) [reply unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: That's what I did already by using a new method: `assertThrowsAndMessage` (see below)

Comment (ekrich) [reply unit-tests/src/test/scala/utils/ThrowsHelper.scala:14]: We need to not add to or use `ThrowsHelper` in new tests so please add your own local helper. Reuse is great but in this case we don't want to use that method. I will be doing a PR to deprecate or try and move it somewhere private.

**Review by WojciechMazur — APPROVED** [review]

**Comment by LeeTibbert** [comment]
@ncordon  Congratulations on the merged PR.  It removes a visible defect that has 
annoyed at least one person in the Scala Community already. One down off the
outstanding bug list.

##### For people reading this PR in the future:

You might, rightly, ask why the fix was to not bite the bullet and use JUnit5.

The first impediment is the perpetual lack of somebody with sufficient available
cycles to do the work.

I spent some time reviewing the state of the art and my memory. I believe the 
more fundamental issue is that JUnit5 uses lambdas and that lambdas 
either require or  work better with Scala 2.12+.  Since Scala Native
currently supports Scala 2.11.mumble, using JUnit5 is precluded.

Once SN no longer supports Scala 2.11, then the way is open
for some kind soul to donate the time to port to JUnit5.
I can only speak for my own cycles, but investing scarce
and dear engineering cycles into Scala 2.11 workarounds which
will soon get obviated simply makes no sense.
