### PR TITLE
Fix #1762: Restore NIR backwards compatibility for reflective instantiation

### LINKED ISSUE #1762: PR #1728 breaks NIR magic number checking & others
Every good, bold, and potentially useful PR, such as PR #1728 deserves it very own series
of bug reports. That shows that someone is attempting to use it.  Also shows that no good deed
goes unrecognized.

It is not surprising that PR #1728 breaks NIR version, given that it deals with NIR. However,
it is not immediately apparent from the description that artifacts from other projects built against -M2
are no longer useful. This should be in __bold__ print.

More specifically, not  only did PR #1728 update the NIR format, it did so in a way 
that breaks NIR magic number, version checking, and hope or prayer of a useful message.

What I am seeing, after locally porting portable-scala-reflect, and using it in ZIO, is 
```
bt:zio> last streamsTestsNative / Nativetest / nativeLink 
[error] java.lang.AssertionError: assertion failed: Can't read non-NIR file.
```
Tracing this back to the code changes in the PR, scalanative/nir/serialization/BinarySerializer.scala
has code:
```
    putBool(hasEntryPoint)

    putInt(Versions.magic)
    putInt(Versions.compat)
    putInt(Versions.revision)
```
which was previously 
```
    putInt(Versions.magic)
    putInt(Versions.compat)
    putInt(Versions.revision)
```
The ` putBool(hasEntryPoint)` is being put _before_ the magic number.  The almost
universal practice is that magic numbers are only magic if they are the first octets.

I believe the ` putBool(hasEntryPoint)` should happen after the Versions checking.
I also believe that Versions.compat & Versions.revision should be studied and almost
certainly changed (to 5, 1 or such).

### PR DESCRIPTION
**Pull request by errikos**
The commit db0631cab1d8f3f590b70fd7bc60e787ca22436c introduced static initialisers in the NIR, which are used to instantiate classes annotated with `@EnableReflectiveInstantiation`. They may serve further purposes in the future.

In order to make the classes that are allowed to be instantiated reflectively reachable, db0631cab1d8f3f590b70fd7bc60e787ca22436c introduced a boolean flag `hasEntryPoints` in the header of the NIR files, with the meaning "this NIR file has classes with entry points". Those classes need to be explicitly marked as reachable.

There were two problems, as described in #1762:

* The mere presence of `hasEntryPoints` broke backwards compatibility with NIR files that were compiled before the introduced change.
* We revised the NIR format, but did not advance the compat/revision versions.

This PR fixes #1762 in the following way:

* Advances the revision number of the NIR format from 6 to 7.
* Moves `hasEntryPoints` after the magic, compat, revision numbers in the header of the NIR file.
* Only checks for the presence of `hasEntryPoints` if the NIR file' revision version is at least 7. Otherwise, `hasEntryPoints` is assumed to be `false`.

### CODE REVIEW

**Comment by sideeffffect** [comment]
I this, PR closes https://github.com/scala-native/scala-native/issues/1762, could you please mention it in the description :pray:

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala [hunk 1]
```diff
@@ -12,11 +14,7 @@ final class BinaryDeserializer(buffer: ByteBuffer) {
...
 
-    val hasEntryPoint = getBool
-
-    val magic    = getInt
-    val compat   = getInt
-    val revision = getInt
+    val NirPrelude(magic, compat, revision, _) = NirPrelude.readFrom(buffer)
 
     assert(magic == Versions.magic, "Can't read non-NIR file.")
     assert(compat == Versions.compat && revision <= Versions.revision,
```
Comment (sjrd) [inline nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:20]: These two assertions should be moved to `NirPrelude.readFrom`, *before* trying to read the byte for `existsEntryPoint`.

File: tools/src/main/scala/scala/scalanative/linker/ClassPath.scala [hunk 2]
```diff
@@ -55,9 +56,9 @@ object ClassPath {
 
     lazy val classesWithEntryPoints: Iterable[Global.Top] = {
       files.filter {
-        case (top, file) =>
-          val buffer = directory.read(file, len = 1)
-          buffer.get() != 0
+        case (_, file) =>
+          val buffer = directory.read(file, len = 16)
```
Comment (sjrd) [inline tools/src/main/scala/scala/scalanative/linker/ClassPath.scala:60]: This 16 is magic, as seen from here. It should be a `val` in `NirPrelude` (and it probably be should 13, not 16).

File: util/src/main/scala/scala/scalanative/util/NirPrelude.scala [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+    val revision = buffer.getInt()
+
+    // indicates whether this NIR file has entry points
+    // and thus should be made reachable, no matter
+    // what the reachability algorithm does
+    // example: reflectively instantiatable classes
+    // since: compat = 4, revision = 7
+    val hasEntryPoints = {
+      import scala.math.Ordering.Implicits._
+      if ((compat, revision) < (4, 7))
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/NirPrelude.scala:24]: Once the assertions on `magic` and `compat` are moved above this point, this test simply becomes
```scala
if (revision < 7)
```

File: nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala (hunk 1 above)
Comment (errikos) [reply nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:20]: The problem with this is that we don't have access to the `Versions` object in `util` and I am not very keen in making `util` depend on anything. I believe it should be dependency-free.

We could move `Versions` to `util` (as in `NirVersions`), but I don't really like that either. `Versions` should stay in `nir`, since they indicate NIR versions. On the other hand, since NIR is core to the project, there is no harm in its version being visible from the outside (for the modules that depend on `util`).

If I were to choose between the two above, I think that the second solution is preferable.

Comment (errikos) [reply nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:20]: Of course, we could provide the `Version` in the `NirPrelude.readFrom` call...

Comment (sjrd) [reply nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:20]: What about moving `NirPrelude` to `nir/` instead? That seems like the obvious solution to me.

Comment (errikos) [reply nir/src/main/scala/scala/scalanative/nir/serialization/BinaryDeserializer.scala:20]: True. I totally missed that `tools` depends on `nir`.

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala [hunk 4]
```diff
@@ -58,7 +58,7 @@ trait NirGenType { self: NirGenPhase =>
   def genArrayCode(st: SimpleType): Char =
     genPrimCode(st.targs.head)
 
-  def genBoxType(st: SimpleType): nir.Type = st.sym match {
+  def genBoxType(st: SimpleType): scala.scalanative.nir.Type = st.sym match {
```
Comment (sjrd) [inline nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala:61]: Why are all these additional `scala.scalanative.` required, in this file?

Comment (errikos) [reply nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenType.scala:61]: Woah, seems that IntelliJ decided to "optimise imports" when I refactored.
