### PR TITLE
Fix #2138: j.i.DataInputStream#rebuffer handles short reads correctly.

### LINKED ISSUE #2138: j.i.DataInputStream#rebuffer does not handle short reads correctly.
Whilst studying Issue #2131, I noticed an "implementation expediency" (a.k.a. "weasel" or "punt")
in `java.io.DataInputStrea#rebuffer` and the way it handles short reads.
```
 if (in.read(inBasket, 0, n) < n)
      throw new java.io.EOFException
```
`EOFException` is proper if the return from `in.read()` is -.
Return values in the range 1 thru n -1 should cause a re-read for the remaining bytes.

That leaves handling 0.  The discussion here assumes that Issue @2137 has
been fixed.   Zero can be returned by `in.read` only if the count passed in is 0,
When the count is non-zero, the underlying `read` call interprets 0 reads as
the other side having gracefully shutown/closed the connection and 
so returns -1 (EOF).

A 0  return value would equal the count passed in and should be returned as is.  

This method is file private, the only callers are in DataInputStream itself. 
The usage within j.i.DIS currently always has a count in the range 1 to 8.
 If callers are silly enough to pass in a count of 0, they should handle the
result.  For maintenance robustness, one could put an assertion into `rebuffer` but I doubt it worth
 the runtime cost; rebuffer() gets called frequently.

The number of retries should be limited as long as the read series is making progress
(i.e. two zero reads in a row should stop).  This prevents infinite loops.

### PR DESCRIPTION
**Pull request by LeeTibbert**
The private rebuffer() method of java.io.DataInputStream now
correctly handles the case where a read() of the underlying stream
returns fewer that the requested number of bytes.

### CODE REVIEW

File: javalib/src/main/scala/java/io/DataInputStream.scala [hunk 1]
```diff
@@ -20,9 +23,35 @@ class DataInputStream(in: InputStream)
   private final val outBasket = ByteBuffer.wrap(inBasket) // default: BigEndian
 
   private final def rebuffer(n: Int): ByteBuffer = {
-    if (in.read(inBasket, 0, n) < n)
-      throw new java.io.EOFException
-    outBasket.clear() // tricky here: contents preserved, bookkeeping reset.
+    @tailrec
+    def rebufferImpl(n: Int, runningTotal: Int): Int = {
+      in.read(inBasket, 0, n) match {
+        case nRead if (nRead == n) => nRead
```
Comment (WojciechMazur) [inline javalib/src/main/scala/java/io/DataInputStream.scala:29]: How about simplifying these matches, eg.:
```suggestion
        case `n` => n
```

We can also replace next two with simple `case -1 => ...` and `case 0 => ...`. Looks more readable in my opinion

**Review by WojciechMazur — APPROVED** [review]

File: javalib/src/main/scala/java/io/DataInputStream.scala (hunk 1 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/io/DataInputStream.scala]: @WojciechMazur  Thank you for the timely & helpful review.  The three changes you suggested do 
improve the code.  I have incorporated all three.

I learned some Scala from your suggestion about using backticks. I never knew that they
could be used in a match to specify an argument reference.  I had always only 
used them to quote 'funny` names.  (The two integer cases were my brain not
being turned on, sorry.)
