### PR TITLE
Corrects bug in named semaphores length for commix garbage collector

### LINKED ISSUE #2200: OS X: NumberFormatException parsing doubles
Sorry for the weird title :)

SN: 0.4.0
OS: OS X 
Scala: 2.13

After doing some fixed number of iterations in parsing doubles from strings, an exception can be thrown on a valid number.

This only happens on OS X.

### Code

```scala
object Test {
  def main(args: Array[String]) = {
    val iters = args(0).toInt
    scala.util.Random.setSeed(500L)
    def lat = scala.util.Random.between(-90.0, 90.0)

    for (i <- 0 to iters) {
      val str = lat.toString

      try {
        str.toDouble
      } catch {
        case e =>
          println(s"Failed after $i iterations")
          throw e
      }
    }
  }
}
```

### Behaviour

On my OS X machine, it sees there's a magic number after which the number parsing can fail:

```
❯ ./target/native-2.13/core-out 100
❯ ./target/native-2.13/core-out 1000
❯ ./target/native-2.13/core-out 10000
❯ ./target/native-2.13/core-out 100000
Failed after 10767 iterations
java.lang.NumberFormatException: For input string "-34.98348554372167"
        <no stack trace available>
❯ ./target/native-2.13/core-out 10766
❯ ./target/native-2.13/core-out 10767
Failed after 10767 iterations
java.lang.NumberFormatException: For input string "-34.98348554372167"
        <no stack trace available>
```

On CI number is different, but same problem: https://github.com/keynmol/scala-native-repro-3/runs/2097599262?check_suite_focus=true#step:6:224

### reproduction

Repo and associated OS X failing build: https://github.com/keynmol/scala-native-repro-3/runs/2097599262?check_suite_focus=true#step:6:224

### PR DESCRIPTION
**Pull request by ncordon**
## What

Shortens the names for the commix GC semaphores.

Solves a problem with `_.toDouble` and `_.toFloat` on OSX, for all versions of Scala (see #2200 for context).

## Why
The `commix` garbage collector was polluting `errno` due to the semaphores not being created correctly with `sem_open` (and successive calls trying to manage them), due to the excessive length of their names. And the errno is checked by [other methods](https://github.com/scala-native/scala-native/blob/15ea60eef45c6263cbb7b736c66eec72c3ab51e6/javalib/src/main/scala/java/lang/IEEE754Helpers.scala#L65).

According to the Apple libc [docs](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sem_open.2.html) for `sem_open`, if the semaphores are more than `SEM_NAME_LEN` characters, the method returns -1 and sets `errno` to `ENAMETOOLONG`.

There are not official sources of documentation for the value for `SEM_NAME_LEN` is OSX, although this StackOverflow [post](https://stackoverflow.com/questions/5288671/sem-open-sets-enametoolong-for-less-than-64-characters-names-on-mac-os-x-10-6-6) answer suggests is 31. [This](https://mail-index.netbsd.org/tech-userlevel/2016/04/23/msg009896.html) other source does also. It holds with the fact that the snippet in #2200 does execute correctly for Scala after the changes.

The GC kicked off after a few iterations in the aforementioned snippet, which explains why it was failing on a given number of loops.

Closes #2200.

### CODE REVIEW

File: nativelib/src/main/resources/scala-native/gc/commix/Phase.c [hunk 1]
```diff
@@ -8,13 +8,13 @@
...
 void Phase_Init(Heap *heap, uint32_t initialBlockCount) {
     pid_t pid = getpid();
-    // size = static part + 32 bit int as string
-    char startWorkersName[32 + 10];
-    char startMasterName[31 + 10];
-    snprintf(startWorkersName, 32 + 10, "scalanative_commix_startWorkers_%d",
-             pid);
-    snprintf(startMasterName, 31 + 10, "scalanative_commix_startMaster_%d",
-             pid);
+    // size = static part + 10 digits (0xFFFFFFFC as maximum PID) + null char
```
Comment (ncordon) [inline nativelib/src/main/resources/scala-native/gc/commix/Phase.c:11]: Reference for the maximum PID:
* On Windows: https://stackoverflow.com/questions/17868218/what-is-the-maximum-process-id-on-windows
* On UNIX: https://unix.stackexchange.com/questions/16883/what-is-the-maximum-value-of-the-process-id

**Comment by ekrich** [comment]
Thank-you for your contribution. This looks like an important fix.
I found this documentation about `sem_open` that might be helpful to confirm your research. https://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_open.html#

File: nativelib/src/main/resources/scala-native/gc/commix/Phase.c (hunk 1 above)
Comment (LeeTibbert) [reply nativelib/src/main/resources/scala-native/gc/commix/Phase.c:11]: Great catch, thank you.  Guess that I did not throw enough 
darts at the board in my attempts to replicate the reported
failure in Issue #2200.

I do not want to do anything to slow down the merge of this PR.
With the consent of the author, I could do a follow-on PR.

I do think it is worthwhile suggesting a assert on the size
of the pid_t: i.e. that it is less than or equal to 8 bytes.
That is, guard the magic number 10 against pid_t
becoming a, say, 64 bit number.   (Or increase the
magic number to 20 (rounding up from necessary 19)
with a comment as to why 20).  Stack space is not free,
but it is cheap, especially compared to the execution time
cost of an assert. I think that SN is compiled without eliding
assertions.)

Open Group Posix 2018 says only that pid_t is a signed
integral type. Finding this bug once was hard, finding 
when someone increases the sizeof pid_t will be
hard too.  Bugs tend to re-occur.

Comment (LeeTibbert) [reply nativelib/src/main/resources/scala-native/gc/commix/Phase.c:11]: Given this is C code, the check for the size of pid_t could probably done with
preprocessor directives and have zero runtime cost.

Comment (ncordon) [reply nativelib/src/main/resources/scala-native/gc/commix/Phase.c]: Fair point! I've widened the maximum length of the pid to 20

File: nativelib/src/main/resources/scala-native/gc/commix/Phase.c [hunk 2]
```diff
@@ -8,13 +8,13 @@
...
-    int masterNameSize = 20 + 10 + 1;
+    // size = static part + 20 digits (maximum 64 bit number) + null char
+    int workerNameSize = 11 + 20 + 1;
+    int masterNameSize = 11 + 20 + 1;
     char startWorkersName[workerNameSize];
     char startMasterName[masterNameSize];
-    snprintf(startWorkersName, workerNameSize, "commix_startWorkers_%d", pid);
-    snprintf(startMasterName, masterNameSize, "commix_startMaster_%d", pid);
+    snprintf(startWorkersName, workerNameSize, "commix_mt_%d", pid);
+    snprintf(startMasterName, masterNameSize, "commix_wk_%d", pid);
```
Comment (ncordon) [inline nativelib/src/main/resources/scala-native/gc/commix/Phase.c:17]: It is basically `master_cx` and `worker_cx` or these other names. With 11 characters not much we can write 😂

Comment (ekrich) [reply nativelib/src/main/resources/scala-native/gc/commix/Phase.c:17]: Except we should try and avoid the `master` tag going forward if possible 😄

File: nativelib/src/main/resources/scala-native/gc/commix/Phase.c [hunk 3]
```diff
@@ -8,13 +8,13 @@
...
 void Phase_Init(Heap *heap, uint32_t initialBlockCount) {
     pid_t pid = getpid();
-    // size = static part + 32 bit int as string
-    char startWorkersName[32 + 10];
-    char startMasterName[31 + 10];
-    snprintf(startWorkersName, 32 + 10, "scalanative_commix_startWorkers_%d",
-             pid);
-    snprintf(startMasterName, 31 + 10, "scalanative_commix_startMaster_%d",
-             pid);
+    // size = static part + 20 digits (maximum 64 bit number) + null char
```
Comment (LeeTibbert) [inline nativelib/src/main/resources/scala-native/gc/commix/Phase.c:11]: Excellent!  Thank you for both taking the time and the helpful explanation.
Some devo down the line is going to sing your praises.

Comment (ncordon) [reply nativelib/src/main/resources/scala-native/gc/commix/Phase.c:11]: Thanks! That's so kind of you

**Comment by LeeTibbert** [comment]
@ekrich kindly encouraged me to take a closer look.
```
void Phase_Init(Heap *heap, uint32_t initialBlockCount) {
    pid_t pid = getpid();
    // size = static part + 20 digits (maximum 64 bit number) + null char
    int workerNameSize = 11 + 20 + 1;
    int masterNameSize = 11 + 20 + 1;
    char startWorkersName[workerNameSize];
    char startMasterName[masterNameSize];
    snprintf(startWorkersName, workerNameSize, "commix_mt_%d", pid);
    snprintf(startMasterName, masterNameSize, "commix_wk_%d", pid);
    // only reason for using named semaphores here is for compatibility with
    // MacOs we do not share them across processes
    heap->gcThreads.startWorkers =
        sem_open(startWorkersName, O_CREAT | O_EXCL, 0644, 0);
    heap->gcThreads.startMaster =
        sem_open(startMasterName, O_CREAT | O_EXCL, 0644, 0);
```
I had been looking at the snprintf lines and making sure that pid_t did
not overrun them.  

The base note, a link to the number format exception in the original issue,
Given that, I think the __fundamental__ flaw is that the return value of the
two `sem_open` calls are not checked.  
```
    heap->gcThreads.startWorkers =
        sem_open(startWorkersName, O_CREAT | O_EXCL, 0644, 0);
    heap->gcThreads.startMaster =
        sem_open(startMasterName, O_CREAT | O_EXCL, 0644, 0);
```
I would have to study & think some more about the proper thing to do.
My first reaction is a perror() and exit(EXIT_FAILURE) or errno.

Once that is peeled back, one gets to the provoking flaw, the length
of the proposed semaphore name.  Since this is C,  _POSIX_NAME_MAX and or _XOPEN_NAME_MAX
ought to be available. The constructed name should not be longer than that.
We start getting into the fact that the returns from snprintf() are not being checked
(i.e. does the proposed name fit into _POSIX_NAME_MAX + 1 and still leave
it properly NUL terminated?)  Yeech!  

With the PID on the right, a number of spaces are unused when, as currently,
the PID is 10 bytes.  Perhaps the PID should go first.

I would have to write a small design study to see what would be correct,
tight, and easy to follow.  

In the short run, perhaps adding the error checks to both `sem_open` calls is
enough to give correctness and we could chat offline about a follow up PR to
add elegance?  

Sorry I did not pick up on the fundamental problem sooner...

**Comment by ekrich** [comment]
Thanks @LeeTibbert. Do you think this could possibly be a separate PR if this fixes a major problem as it is?

**Comment by LeeTibbert** [comment]
@ekrich @ncordon  I concur that the PR as-is could proceed, with the idea of a more comprehensive
PR to follow (yes, I am willing to devote cycles to that.)

A relatively easy (hah! what does that word mean?) 1+ would be to add a 
assertion after each `sem_open` testing that the return value is not SEMFAILED
(which should be already be defined & included in semaphore.h).  That is not
as good/helpful as a perror() & exit() but 1 line in two places, rather than 10 in
each of two places.

**Comment by ncordon** [comment]
This PR is just to make it work, but definitely the code could be made more robust.

A flaw in the garbage collectors in my opinion (apart from not checking the output of `sem_open`, which in this case was -1) is not to clean `errno`. So if you have a garbage collector executing on the same thread, that's likely to cause unintended behaviours. 

Another problem here is that `commix` is supposed to be executing in another thread if I understand correctly and `errno` is supposed to be something not shared between threads, so not sure how the `errno` ends up being shared (makes me think commix is being executed in a lightweight thread or something).

I'm happy to open an issue describing all those problems and take a look at them. Does that sound go?

**Comment by LeeTibbert** [comment]
Sounds like a plan. Fix the immediate need so that end users are not being
hosed by it, then go for a better fix.

I personally think the process should exit if `sem_open` fails.  An
incorrect garbage collector is, what are Linus' words "very bad, Double ungood"?
I hope I did not give the impression that errno should be set to 0 or ignored,
quite the opposite.

To summarize from my end LGTM, particularly if a followup issue is created
to capture the dangling ends.

**Comment by ncordon** [comment]
Issue created!

**Review by WojciechMazur — APPROVED** [review]
