### PR TITLE
Fix #1470: Correct/Fix sys/select.scala fd_set declaration, remove selectOps. Breaking changes.

### LINKED ISSUE #1470: posix/sys/select.scala declares fd_set with wrong number of bytes.
Issue #1128 implied a long cascade of PRs to fix it.  All the the last have been submitted & accepted.   I am creating this issue fo focus on the single remaining defect.

With good evidence, I believe that posix/sys/select.scala is declaring the type fd_set
with wrong number of bytes/octets.
To my eyes,  the current declaration ` type fd_set = CStruct1[Ptr[CLongInt]]` allocates 
8 explicit bytes (for the Ptr).  If there are hidden bytes allocated for the CStruct1
that is an additional issue.   So, lets say we have small N bytes allocated, where there
is some imprecision about the number of bytes & it can change with implementation
changes to CStruct1.

#### The Issue: memory spray!
Focusing on Linux [Note 1 below], the sizeof(fd_set) is 128 bytes, giving the 1024 bit buffer
 that FD_ZERO is documented as expecting & will write to. 
If  C FD_ZERO is passed the current exceedingly short buffer, one has a memory spray!  

I am not sure why this issue is not being seen in unit-tests in debug mode.  It was
the underlying problem of Issue #128 in release mode.  

PR #1454 fixed Issue #1128 by removing the uses of select with the buggy
implementation in accept() & listen() and replacing them with calls to poll().

#### Proposed solution

I am in the midst of creating a WIP PR implementing the following solution,
so that people can see what it looks like, consider its ramifications, etc. 

I believe the key is to change the declaraton of fd_set to
```
 private[this] type _16 = Digit[_1, _6]

  // 16 * 64 == 1024 == FD_SETSIZE                                              
  type fd_set = CStruct1[CArray[CLongInt, _16]]
```
There are cascade changes to SocketHelpers.scala required.
Also some defensive programming changes around the fixed 1024 bit size.

This change will be a hard break for anyone using select() with the 
incorrect declaration.  However, there code is almost certainly broken already.
Forcing a fix might not be a bad thing.

##### Note 1
For the sake of discussion and understanding, I am skipping a long, tedious
discussion about the sizeof(fd_set) on other Operating Systems and in the
near, middle, & long term.  I can sing those verses if someone likes, but it
usually takes me a few beverages to get there.  The short story is that almost
all contemporary OSen have a fd_set of 1024 or larger.

### PR DESCRIPTION
**Pull request by LeeTibbert**
This PR simplifies and supersedes PR #1253 "Correct/Fix posix
sys/select.scala fd_set declaration".

The presenting problem and its current state is described in Issue #1470.
The problem has a complicated history and has resulted in a number of now merged PRs.

I believe this PR is ready for merge and the issues below addressed.

I include these  sssues for discussion as an aid to informed review:

- Macro

  * This is a breaking change.  Then again, any code using the
    existing definitions is broken now.

    I think uses of the 0.3.8 idiom get by because two
    stackallocs are done one after the other.  When the first
    gets overwritten, it spills into the second, instead of
    random memory.  This is pretty fragile.  If something
    else gets allocated on the stack between the stackallocs,
    the an FD_ZERO will clobber the intervening variable.

  * The major issue for review is the declaration of fd_set type
    to use a fixed size static buffer.  The declaration in this
    PR closely follows the C declaration and brings with it the
    entire dependency on the buffer of fd_set being a fixed size
    buffer, almost always 1024 bits.

    I can dive down the rabbit hole of a long & tedious discussion
    about the sacredness of 1024 bits but I think that discussion
    now will only annoy non-network guru reviewers.

  * An example of a simple allocation of a fixed size buffer fd_set
    is provided.  An experienced programmer will notice immediately
    that there are ways to save memory by allocating so-called short
    buffers and avoiding calling FD_SET. There is an escape hatch.
    Then again, an experienced network programmer would probably not
    be willingly dealing with select() in the first place. poll()
    is the more efficient and contemporary idiom.

- Meso

  * This PR removes selectOps in favor of timeOps.  That change could
    be factored out into a separate PR if that would aid review or
    audit trail.

    I had to go one way or the other. Seemed to me like the
    FD_SET change would cause someone to edit a file, they probably
    want to make both sets of edits at the same time: sort by file, not
    commit.

  * I believe that it is early enough in SN development that removing
    selectOps is better than letting duplicate & stale code remain
    in place forever.

- Micro

  * There is a 32/64 bit issue on which I will have to check with
    @shadaj.  I have been advised to program to 64 bit machines and
    let the 32 bit port follow along.  select.scala follows the
    C implementation of the first element of an fd_set struct being
    an array of CLongint.

         type fd_set = CStruct1[CArray[CLongInt, _16]]

    On 32 bit machines this needs to be the mildly unexpected CLongLong.
    CLongLong works for both 32 & 64 bit machines but gives a slightly
    jarring implication on 64 bit (which is why I wrote it the way I did.)

  * To keep this PR focused on select related changes, I created issues
    for two small defects in SocketHelpers.scala. I have the fixes
    in my sandbox code, but kept them out of this PR.

Documentation:

   * A release note is needed which says something like
   ```
    The declaration of the type fd_set in ScalaNative 0.3.8 declared the wrong number of 
    bytes.  This defect revealed itself when using SCALANATIVE_MODE="release".

    This defect has now been corrected and is a breaking change.
    The type fd_set declares the the 1024 bit ==  16 long Int fixed size buffer documented for
    glibc FD_ZERO.

    Another breaking change is that object socketOps has been removed. posix.sys.timeOps
    provides the same conversions from a more logical  location.
   ```

Testing:

  * Built and tested ("test-all") with sbt 1.2.6 release modes on
    X86_64 only . All tests, other than the perennial malefactor link-order, pass.
  
    The scripted-tests java-net-socket IsReachableTest calls  SocketHelpers.isReachableByEcho
    which calls select() twice. So both SocketHelpers and select() are getting exercised at least once.

    To assure myself that the current edits would not make people in the
    wild unhappy after they had already been forced to make code changes
    to correct the allocation of fd_set, I created a private copy
    of PlainSocketImplementation.scala using a version of that file which
    still called select().  I then modified the file to use the new
    fd_set declaration & allocation.

    Using the private, modified copy of PlainSocketImpl.scala, I did
    a complete rebuild & test-all in the four square sbt version
    by release/debug mode matrix.  All tests, modulo know breakage
    elsewhere, passed as expected.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
@densh  I think the one has baked enough and is ready for merge as you are available.
There are other fish to fry, well broil.

The only thing hanging is the wording of a release note.  Let me know when the time approaches for that and I will write a draft.

**Comment by LeeTibbert** [comment]
In a conversation on gitter, @densh recommended Zone over stackalloc. This PR 
uses a stackalloc of 16 Longs (1024 bits) and documents stackalloc.

The other uses of stackalloc are all small & reasonable.

If recommended by review, I can rework the large allocation and the examples to use Zone.  As long
as I have a zone, I could do small (4 byte) allocations in the zone also or leave them alone.

Please advise.  Thank you It would be nice to get this one into 0.4.0-BL1.

**Comment by LeeTibbert** [comment]
If I go back to using Zone, I may rework this to be like my first attempt and provide
a few *Helper routines to get the size and allocation right once and for all.

**Comment by LeeTibbert** [comment]
Per recommendation of @densh on gitter, (my words, not his directly) I will re-work to use Zone
and, if reasonable, avoid FD_SETSIZE complexity.

It will take me two weeks or so until I can get to this, sorry.  I am still hoping for 0.4.0-BL1 though.

**Comment by LeeTibbert** [comment]
Continuous Improvement is indeed a bear, but, to my thinking, well worth the effort.

**Comment by LeeTibbert** [comment]
Once again, I believe this PR is ready for merge.  
Review & gitter comments & suggestions incorporated.

All tests green in Travis CI.

I believe it is asymptotically close the the best that can be done with current and longstanding
Linux glibc practice.  Flaws may remain, but they are vanishingly important compared to the
current dead wrong behavior.

**Comment by LeeTibbert** [comment]
All tests pass for sbt 0.13.7 Release mode. 0.13.7 was coverted by Travis CI, all green.

File: posixlib/src/main/scala/scala/scalanative/posix/sys/select.scala [hunk 1]
```diff
@@ -34,15 +70,17 @@ object select {
...
-    def tv_usec_=(v: suseconds_t): Unit = !ptr._2 = v
-  }
+  def createZeroed()(implicit z: Zone): Ptr[fd_set] = {
+    // Be type pure and return pointer to fixed size buffer fd_set.
+    // One _could_ detect FD_SETSIZE at runtime and adapt allocated size,
+    // but the method would then be lying about the return type.
 
+    // Zone.alloc is documented as returning zeroed memory.
+    z.alloc(sizeof[fd_set]).cast[Ptr[fd_set]]
+  }
```
Comment (densh) [inline posixlib/src/main/scala/scala/scalanative/posix/sys/select.scala]: What's the purpose of this method? It looks like exactly the same thing as just `alloc[fd_set]`.

File: posixlib/src/main/scala/scala/scalanative/runtime/SocketHelpers.scala [hunk 2]
```diff
@@ -46,7 +45,8 @@ object SocketHelpers {
 
         fcntl(sock, F_SETFL, O_NONBLOCK)
 
-        val fdsetPtr = selectFdSet.createZeroed
+        // Zone.alloc is documented as returning zeroed memory.
+        val fdsetPtr = alloc[fd_set].cast[Ptr[fd_set]]
```
Comment (densh) [inline posixlib/src/main/scala/scala/scalanative/runtime/SocketHelpers.scala]: `alloc[fd_set]` does return `Ptr[fd_set]`, no need to cast it after.

Comment (LeeTibbert) [reply posixlib/src/main/scala/scala/scalanative/runtime/SocketHelpers.scala]: `alloc[fd_set]` neat feature!  So that is at least part of what the macro is doing.

cast removed. comments tweaked. Thank you for the recommendation.  Travis CI 
shows all green.

**Comment by densh** [comment]
LGTM, thanks @LeeTibbert ! 👍
