### PR TITLE
Fix #1944: Compile error for non-public methods with JUnit annotations

### LINKED ISSUE #1944: Compiler crash on JUnit test
Not sure if this may help. https://gist.github.com/ekrich/c7d1bba6c9a469b5c21471477ff23547
```
sbt:scala-native> tests/testOnly java.util.jar.AttributesTest*
[info] Compiling 1 Scala source to /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes ...
[error] 
[error]   EmptyScope.enter
[error]      while compiling: /Users/eric/workspace/scala-native/unit-tests/src/test/scala/java/util/jar/AttributesTest.scala
[error]         during phase: junit-inject
[error]      library version: version 2.12.12
[error]     compiler version: version 2.12.12
[error]   reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.12/scala-library-2.12.12.jar -encoding utf8 -feature -unchecked -Ywarn-unused:imports -Ywarn-unused-import -classpath /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes:/Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/classes:/Users/eric/workspace/scala-native/scalalib/target/scala-2.12/scalalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/auxlib/target/scala-2.12/auxlib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/nativelib/target/scala-2.12/nativelib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/javalib/target/scala-2.12/javalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/posixlib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/clib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface-sbt-defs/target/scala-2.12/classes:/Users/eric/workspace/scala-native/junit-runtime/target/scala-2.12/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.12/scala-reflect-2.12.12.jar -Xplugin:/Users/eric/workspace/scala-native/nscplugin/target/scala-2.12/nscplugin_2.12.12-0.4.0-SNAPSHOT.jar -Xplugin:/Users/eric/workspace/scala-native/junit-plugin/target/scala-2.12/junit-plugin_2.12.12-0.4.0-SNAPSHOT.jar
[error] 
[error]   last tree to typer: TypeTree(class AttributesTest)
[error]        tree position: <unknown>
[error]             tree tpe: java.util.jar.AttributesTest
[error]               symbol: class AttributesTest in package jar
[error]    symbol definition: class AttributesTest extends Object (a ClassSymbol)
[error]       symbol package: java.util.jar
[error]        symbol owners: class AttributesTest
[error]            call site: package <root> in <none>
[error] 
[error] == Source file context for tree position ==
[error] 
[error] ## Exception when compiling 194 sources to /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes
[error] scala.reflect.internal.FatalError: 
[error]   EmptyScope.enter
[error]      while compiling: /Users/eric/workspace/scala-native/unit-tests/src/test/scala/java/util/jar/AttributesTest.scala
[error]         during phase: junit-inject
[error]      library version: version 2.12.12
[error]     compiler version: version 2.12.12
[error]   reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.12/scala-library-2.12.12.jar -encoding utf8 -feature -unchecked -Ywarn-unused:imports -Ywarn-unused-import -classpath /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes:/Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/classes:/Users/eric/workspace/scala-native/scalalib/target/scala-2.12/scalalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/auxlib/target/scala-2.12/auxlib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/nativelib/target/scala-2.12/nativelib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/javalib/target/scala-2.12/javalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/posixlib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/clib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface-sbt-defs/target/scala-2.12/classes:/Users/eric/workspace/scala-native/junit-runtime/target/scala-2.12/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.12/scala-reflect-2.12.12.jar -Xplugin:/Users/eric/workspace/scala-native/nscplugin/target/scala-2.12/nscplugin_2.12.12-0.4.0-SNAPSHOT.jar -Xplugin:/Users/eric/workspace/scala-native/junit-plugin/target/scala-2.12/junit-plugin_2.12.12-0.4.0-SNAPSHOT.jar
[error] 
[error]   last tree to typer: TypeTree(class AttributesTest)
[error]        tree position: <unknown>
[error]             tree tpe: java.util.jar.AttributesTest
[error]               symbol: class AttributesTest in package jar
[error]    symbol definition: class AttributesTest extends Object (a ClassSymbol)
[error]       symbol package: java.util.jar
[error]        symbol owners: class AttributesTest
[error]            call site: package <root> in <none>
[error] 
[error] == Source file context for tree position ==
[error] 
[error] 
[error] scala.reflect.internal.Reporting.abort(Reporting.scala:68)
[error] scala.reflect.internal.Reporting.abort$(Reporting.scala:64)
[error] scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
[error] scala.reflect.internal.Scopes$EmptyScope$.enterEntry(Scopes.scala:514)
[error] scala.reflect.internal.Scopes$Scope.enter(Scopes.scala:143)
[error] scala.reflect.internal.Symbols$Symbol.setInfoAndEnter(Symbols.scala:1586)
[error] scala.tools.nsc.typechecker.Implicits.memberWildcardType(Implicits.scala:334)
[error] scala.tools.nsc.typechecker.Implicits.memberWildcardType$(Implicits.scala:328)
[error] scala.tools.nsc.Global$$anon$5.memberWildcardType(Global.scala:483)
[error] scala.tools.nsc.typechecker.Implicits$HasMember$.$anonfun$apply$1(Implicits.scala:343)
[error] scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] scala.tools.nsc.typechecker.Implicits$HasMember$.apply(Implicits.scala:343)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adaptToMemberWithArgs$7(Typers.scala:1336)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:725)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:725)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1336)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5105)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5138)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5679)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$39(Typers.scala:4832)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:712)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4834)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4862)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5678)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5788)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3335)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3335)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2495)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$103(Typers.scala:5653)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:499)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5688)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5940)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer.genCallOnParam(ScalaNativeJUnitPlugin.scala:197)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer.genBootstrapper(ScalaNativeJUnitPlugin.scala:141)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer$$anonfun$1.applyOrElse(ScalaNativeJUnitPlugin.scala:104)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer$$anonfun$1.applyOrElse(ScalaNativeJUnitPlugin.scala:102)
[error] scala.collection.immutable.List.collect(List.scala:315)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer.transform(ScalaNativeJUnitPlugin.scala:102)
[error] scala.scalanative.junit.plugin.ScalaNativeJUnitPlugin$ScalaNativeJUnitPluginComponent$ScalaNativeJUnitPluginTransformer.transform(ScalaNativeJUnitPlugin.scala:84)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
[error] scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:37)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:402)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1511)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1495)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1488)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1614)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] stack trace is suppressed; run last tests / Test / compileIncremental for the full output
[error] (tests / Test / compileIncremental) scala.reflect.internal.FatalError: 
[error]   EmptyScope.enter
[error]      while compiling: /Users/eric/workspace/scala-native/unit-tests/src/test/scala/java/util/jar/AttributesTest.scala
[error]         during phase: junit-inject
[error]      library version: version 2.12.12
[error]     compiler version: version 2.12.12
[error]   reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.12/scala-library-2.12.12.jar -encoding utf8 -feature -unchecked -Ywarn-unused:imports -Ywarn-unused-import -classpath /Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/test-classes:/Users/eric/workspace/scala-native/unit-tests/target/scala-2.12/classes:/Users/eric/workspace/scala-native/scalalib/target/scala-2.12/scalalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/auxlib/target/scala-2.12/auxlib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/nativelib/target/scala-2.12/nativelib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/javalib/target/scala-2.12/javalib_native0.4.0-SNAPSHOT_2.12-0.4.0-SNAPSHOT.jar:/Users/eric/workspace/scala-native/posixlib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/clib/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface/target/scala-2.12/classes:/Users/eric/workspace/scala-native/test-interface-sbt-defs/target/scala-2.12/classes:/Users/eric/workspace/scala-native/junit-runtime/target/scala-2.12/classes:/Users/eric/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.12/scala-reflect-2.12.12.jar -Xplugin:/Users/eric/workspace/scala-native/nscplugin/target/scala-2.12/nscplugin_2.12.12-0.4.0-SNAPSHOT.jar -Xplugin:/Users/eric/workspace/scala-native/junit-plugin/target/scala-2.12/junit-plugin_2.12.12-0.4.0-SNAPSHOT.jar
[error] 
[error]   last tree to typer: TypeTree(class AttributesTest)
[error]        tree position: <unknown>
[error]             tree tpe: java.util.jar.AttributesTest
[error]               symbol: class AttributesTest in package jar
[error]    symbol definition: class AttributesTest extends Object (a ClassSymbol)
[error]       symbol package: java.util.jar
[error]        symbol owners: class AttributesTest
[error]            call site: package <root> in <none>
[error] 
[error] == Source file context for tree position ==
[error] 
[error] Total time: 2 s, completed Oct 12, 2020 8:58:16 AM
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Resolves #1944 

This PR fixes problem with compiler crashing in the `inject-junit` phase when the method annotated with `Before` is declared with a `private` modifier. The problem did not occur with other access modifiers.  

Although this change fixes the issue it also makes it less compatible with [JUnit API](https://junit.org/junit4/javadoc/latest/org/junit/Before.html) which states:
_Annotating a **public void** method with @Before causes that method to be run before the Test method_
Even though I would opt-in merging this PR as it's not breaking, but it's widening the JUnit features set.

### CODE REVIEW

**Comment by ekrich** [comment]
Yes, after looking at the JUnit API documentation it says that the `@Before` method should be public although I used protected and it worked - I was thinking in Java. Maybe a better idea is to produce a compile error if the method is not public. Is that possible?

https://junit.org/junit4/javadoc/4.12/org/junit/Before.html

I suppose this would apply to `@After`, `@BeforeClass` and `@AfterClass` as well. They all should be public.

**Comment by WojciechMazur** [comment]
> Maybe a better idea is to produce a compile error if the method is not public. Is that possible?

Yeah, that's possible, although the JUnit inject phase is quite generic in terms of annotated methods, and it would be applied to all of them, it might not be a problem since all of mentioned by you annotations should also be public

**Comment by WojciechMazur** [comment]
I've applied changes after @ekrich suggestion.
CI failed in source checks and in resolving dependency, rerunning these tests should give us green light.

**Comment by ekrich** [comment]
One of the last commit in the `java.io` tests included changing all the methods to public that had annotations in anticipation of this fix.

File: junit-plugin/src/main/scala/scala/scalanative/junit/plugin/ScalaNativeJUnitPlugin.scala [hunk 1]
```diff
@@ -174,6 +174,14 @@ class ScalaNativeJUnitPlugin(val global: Global) extends NscPlugin {
           .map(gen.mkMethodCall(Ident(module), _, Nil, Nil))
           .toList
 
+        val nonPublicCalls = calls.filterNot(_.symbol.isPublic)
```
Comment (sjrd) [inline junit-plugin/src/main/scala/scala/scalanative/junit/plugin/ScalaNativeJUnitPlugin.scala:177]: Doing this after having created all the `calls` means that we're still temporarily generating invalid code. I suggest `partition`ing the `annotatedMethods` according to whether they are public first. Then report errors on the non-public ones, and only generate `mkMethodCall`s for the public ones.

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]
