### PR TITLE
Optimize throwing exception to local handler as jump

### LINKED ISSUE #4190: New exceptions can skip finally block in LTO mode
Let's consider this snippet used when testing StackOverflowError correctness

```scala
package scala.scalanative.runtime

object Test {
  def main(args: scala.Array[String]): Unit = {
    val devNull = new java.io.PrintStream(
      new java.io.File("/dev/null")
    )

    @scala.noinline
    @scala.scalanative.annotation.nooptimize 
    def stackoverflow(): Int = {
      // for faster stack overlfow, 
      // with too big stack allocation devNull.println would not be entered before throwing StackOverflowError
      val buf = scala.scalanative.unsafe.stackalloc[Byte](512) 
      devNull.println(".")
      buf.toInt + stackoverflow()
    }
      try stackoverflow()
      catch { case ex: StackOverflowError => println(ex) }
      finally {
        println(scalanative.runtime.getMonitor(devNull.asInstanceOf[scalanative.runtime._Object]).show)
      }
      assert(!Thread.holdsLock(devNull))
  }
}
```
Inside the test we're mostly interested when `devNull.println()` triggers `StackOverflowError` - it's important becouse internally it enters `devNull` monitor twice: 
- in `PrintStream.println(String)` 
- in `PrintStream.printString(String)` - private method

During any normal executed the monitors are correctly closed.  
However, when LTO is enabled there is 1 non-released monitor at the end of execution. It does not happend when switching to C++ based exception handling

### LINKED ISSUE #4195: Throw to local catch handler might be skipped under LTO
> Self contained minimization: 
> 
> ```scala
> @main def Test() =  try {
>       println("in 1 try")
>       try {
>         println("in 2 try")
>         try {
>           println("in 3 try")
>           try throw new RuntimeException()
>           catch { case ex: java.io.IOException => println(ex) }
>         } finally {
>           println("finally 3")
>         }
>       } finally {
>         println("finally 2")
>       }
>     } catch {
>       case ex: java.lang.Throwable => println(s"catch 1: $ex")
>     } finally {
>       println("finally 1")
>     }
> ```
> 
> On JVM, in current SN without LTO, or with LTO using C++ exceptions: 
> ```scala
> in 1 try
> in 2 try
> in 3 try
> finally 3
> finally 2
> catch 1: java.lang.RuntimeException
> finally 1
> ```
> 
> With LTO either not cought at all (handled by top-level handled generated for `main`) or skips 2 finally blocks: 
> 
> ```scala
> in 1 try
> in 2 try
> in 3 try
> catch 1: java.lang.RuntimeException
> finally 1
> ``` 

 _Originally posted by @WojciechMazur in [#4190](https://github.com/scala-native/scala-native/issues/4190#issuecomment-2626968760)_

### PR DESCRIPTION
**Pull request by WojciechMazur**
Allows to skip unwinding process and jump directly to handler if it's defined in the same scope. 

Fixes #4195 on the CodeGen side by eliminating most of unwinding calls that were failing after LTO

### CODE REVIEW

File: unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala [hunk 1]
```diff
@@ -725,6 +725,35 @@ class IssuesTest {
     assertEquals(result, "b")
   }
 
+  @Test def issue4194(): Unit = {
+    var tryCounter = 0
+    var finallyCounter = 0
+    var cought = false
```
Comment (ekrich) [inline unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala:731]:
```suggestion
    var caught = false
```

File: unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala [hunk 2]
```diff
@@ -725,6 +725,35 @@ class IssuesTest {
...
+    try {
+      tryCounter += 1
+      try {
+        tryCounter += 1
+        try {
+          tryCounter += 1
+          try throw new RuntimeException()
+          catch {
+            case ex: java.io.IOException => // exception unrelated to throw one
+              fail("Should not be cought")
```
Comment (ekrich) [inline unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala:741]:
```suggestion
              fail("Should not be caught")
```

File: unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala [hunk 3]
```diff
@@ -725,6 +725,35 @@ class IssuesTest {
...
+          } finally {
+            finallyCounter += 1
+          }
+        } finally {
+          finallyCounter += 1
+        }
+      } catch { case ex: java.lang.Throwable => cought = true }
```
Comment (ekrich) [inline unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala:748]:
```suggestion
      } catch { case ex: java.lang.Throwable => caught = true }
```

File: unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala [hunk 4]
```diff
@@ -725,6 +725,35 @@ class IssuesTest {
...
+    } finally {
+      finallyCounter += 1
+    }
+    assertEquals("some finally block was skipped", 3, finallyCounter)
+    assertEquals(tryCounter, finallyCounter)
+    assertTrue("exception not cought", cought)
```
Comment (ekrich) [inline unit-tests/native/src/test/scala/scala/scalanative/IssuesTest.scala:754]:
```suggestion
    assertTrue("exception not caught", caught)
```

**Review by ekrich — COMMENTED** [review]
Change spelling - think I got them all.

**Comment by WojciechMazur** [comment]
In the future this backend optimization should be replaced with more general approach in #1513
