### PR TITLE
Fix #1683: Implement suppression and non-writable trace for Throwable

### LINKED ISSUE #1683: Implement suppression for Throwable
During the porting of https://zio.dev/ to Scala Native I [faced](https://github.com/zio/zio/blob/222999eaacb43630bf373d6e0225a3d444bd4ab0/core/shared/src/main/scala/zio/FiberFailure.scala#L27) the lack of:
```java
protected Throwable(String message,
                    Throwable cause,
                    boolean enableSuppression,
                    boolean writableStackTrace)

```
constructor with the `enableSuppression` flag.
https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This PR was motivated by Issue #1683 "Implement suppression for
    Throwable".

    That issue and several related others are now fixed.

  * Some of the implementation and testing code was ported, with gratitude,
    from Scala JS. Thank you, @sjrd & team.

  * The requested four argument constructor and associated methods
    were implemented.  The SN Throwables class should now follow
    the Java 8 specification.

    Argument checking was tightened up to match specification.
    Exceptions messages match Scala JVM practice.

    initCause() was changed to follow the "at-most-once" semantics
    described by Java 8.

  * Several methods are described by Java 8 as being thread-safe.
    SN is currently mono-threaded but it makes no sense to
    introduce hard to find technical debt by writing new code
    which is supposed to be thread-safe and is not.

    These routines currently use `this.synchronized` which
    synchronizes on the entire class. If the way they were implemented
    seems to not be idiomatic, that is to prevent the bug described
    in SN Issue #1091. The synchronization protects each `var`
    accessed outside constructors. The latter are defined as mono-threaded
    by the Java specification.

    The locking can be done at a finer granularity if experience shows that
    the execution time lost due to lock contention is unacceptable,
    Throwables handling is pretty slow to begin with, so I suspect that
    lock contention will be hard to identify.

  * Extensive unit tests were implemented in the new ThrowablesSuite.scala.
    Each of the constructors and almost all methods are exercised.
    Reasons are given to be confident in the two untested methods.

Documentation:

  * The standard changelog entry is requested.

Testing:

  * Built and tested ("test-all") in debug mode using sbt 1.2.8 & Java 8 on
    X86_64 only . All tests pass.

  * Built and tested ("test-all") in release-fast mode, LTO=thin using
    sbt 1.2.8 & Java 8 on X86_64 only . All tests pass.

### CODE REVIEW

**Comment by rwhaling** [comment]
lovely work @LeeTibbert  👏 👏 👏

**Comment by LeeTibbert** [comment]
@ekrich  Thank you for the review & comments.  

Such a timeley review before Travis completes is great.  It helps me consider & address 
comments whilst the base info is still swapped into my brain.

> Looks pretty darn good but a couple of comments. I compared with the Scala.js version.
>     1. Was expecting to see some checking of exception/messages in `initCause` tests as you did such a nice job looking at the JVM behavior.

Can you guess which test I wrote last?   

Can you describe what seems to be missing in the initCause() tests?  Probably the same
blind spot which kept me from writing the test keeps me from seeing what is missing.
Sorry. for the failure of my imagination.,

There is one test, of three parts, which tests "at-most-once" semantics.  There is a second
test which does a initCause() snd then a getCause, testing that that the two match.

What would make it more complete?  Thanks.

>     2. Perhaps `getStackTrace` should be more like the Scala.JS version where is tries to initialize the trace if it can?


```
 // We use an Array rather than, say, a List, so that Throwable does not       
  // depend on the Scala collections.                                           
  private[this] var suppressed: Array[Throwable] = _

  if (writableStackTrace)
    fillInStackTrace()

```
I think he code you suggest is there, taken directly from Scala.js, including lack of braces.
I believe that it is in approximately the same place as in the Scala.js code. 
Before the SN code did an  unconditional fillInStackTrace() in the same place.

I found the code hard to find when I started work. A bit of Constructor executable
code is buried  amongst the declarations.  I think I using a variant that line on a `var`
declaration instead of wildcard (_) and ran into some issue at unit-test time.

I could give that another run if it would make review of the code more evident.
Some poor soul in the future will probably get dropped into the midst of this code
and need to figure it out on-the-fly.

**Comment by LeeTibbert** [comment]
@ekrich Re: fillInStackTrace()  I think the best I can do is to improve locality of concept by
moving the fillinStackTrace() above the `var suppressed.`  I'll do another commit doing that.

I remain open to other ideas & possibilities.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 1]
```diff
@@ -49,49 +49,111 @@ private[lang] object StackTrace {
...
   def getStackTrace(): Array[StackTraceElement] = {
     if (stackTrace eq null) {
-      stackTrace = Array.empty
-    }
-    stackTrace
+      Array.empty[StackTraceElement]
+    } else
+      this.synchronized {
+        stackTrace.clone
+      }
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/Throwables.scala]: This part in Scala.js does esentially the code for `fillInStackTrace` if you compare the code. Here if it is empty you just return empty rather than trying to fill it.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 2]
```diff
@@ -49,49 +49,111 @@ private[lang] object StackTrace {
...
     }
 
-    this.stackTrace = stackTrace.clone()
+    this.synchronized {
+      if (e != null) {
+        // Yes, JVM uses contraction "Can't"
+        val msg = if (cause == null) "a null" else cause.toString
+        throw new java.lang.IllegalStateException(
+          s"Can't overwrite cause with ${msg}")
+      } else {
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/Throwables.scala]: I was thinking of checking the exception throwing paths and the messages.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 1 above)
Comment (ekrich) [reply javalib/src/main/scala/java/lang/Throwables.scala]: This didn't work how I wanted it to. It was suppose to point to the `getStackTrace` method.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala]: After off-line discussion, I believe that Eric and I agreed to leave the code as it is.  
The revised code specifies the type of the empty array and follows the JVM
spec more closely by cloning stackTrace rather than returning the writable original.

@ekrich If you agree, could you take a moment and resolve this conversation.  If 
I have mis-characterized or misundertood our discussion, please advise.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 2 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala]: Two tests in ThrowablesSuite.scala, below, test the paths which throw exceptions and that
the cause Throwable has object equality with the cause Throwable given as an argument
to initCause().  If there is no object equality, the messages within the result & expected cause
throwables are given by the assert().
```
test("initCause(cause) - cases which throw an Exception")
test("initCause(cause)")
```   

Does this resolve your concern?

The test suite code tests that the type of exception thrown is as expected. It does not check that the
text of the message is as expected.  There is code in other suites which does an exact message match,
but it is tedious to implement.

Comment (ekrich) [reply javalib/src/main/scala/java/lang/Throwables.scala]: That seems totally fine and would port back to Scala.js as well.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 1 above)
Comment (ekrich) [reply javalib/src/main/scala/java/lang/Throwables.scala]: I think that sounds good if that is how you interpret the documents as well. If people have performance or other concerns the original is fine with me with a simple comment.

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala]: Ah, a "simple comment" turned into a long tour through some tricky code!  

@ekrich If/when you have time, could you check the comment you recommended
and see if I described the situation so that another devo could follow it?  Thank you.

I can re-work it if it comes off as word salad....

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 3]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
+      }
+    }
+  }
 
   def fillInStackTrace(): Throwable = {
-    this.stackTrace = StackTrace.currentStackTrace()
+    // currentStackTrace should be handling exclusion in its own
+    // critical section, but does not. So do
+    if (writableStackTrace) this.synchronized {
+      this.stackTrace = StackTrace.currentStackTrace()
```
Comment (hepin1989) [inline javalib/src/main/scala/java/lang/Throwables.scala:107]: check `this.stackTrace ne null`?

Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:107]: @hepin1989 Thank you for the review & suggestion. Always good to have another
pair of eyes go over the code. 

I concur that `null.synchronized` and `null.stackTrace` would not be a good thing to happen.

I believe that if the code in lines 106 & 107 are executing then `this` is an
instantiated object and can not be null.  Am I missing something?

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 4]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
 
-  def getCause(): Throwable = e
+    if (exception == null) {
+      // Yes, JVM message uses 'cannot' (sic) & has terminal period/full_stop!
+      throw new java.lang.NullPointerException(
+        "Cannot suppress a null exception.")
+    }
 
-  def getLocalizedMessage(): String = getMessage()
+    if (exception == this) {
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:85]: This test should use `eq`. Otherwise you're going to call `equals` for every `addSuppressed`, and that does not match the behavior of the JVM.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 3 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:107]: The code is correct as is.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 5]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
+    // If scala code creates this situation, then by the Gell-Mann principle
+    // user code in the wild is bound to do so.
+    //
+    // If stackTrace is null, no profit to calling fillInStackTrace().
+    // If writableStackTrace is true, then fillInStackTrace has already
+    // been called in the constructor. If the stack is not writable, then
+    // it can not be filled in.
+
+    if (stackTrace == null) {
+      Array.empty[StackTraceElement] // as specified by Java 8.
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:135]: Prefer
```suggestion
      new Array[StackTraceElement](0) // as specified by Java 8.
```
which does not depend on Scala's `ClassTag`s. We should avoid to depend on anything Scala-specific in `Throwable`, which is a core class.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 1 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:139]: The strategy here is correct. Scala.js stores raw data in `fillInStackTrace()`, and only expands them into an `Array[StackTraceElement]` on first request. Scala Native eagerly creates the `StackTraceElement`s in `fillInStackTrace()`, so `getStackTrace()` doesn't have to do anything special.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 6]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
+    } else
+      this.synchronized {
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:137]: AFAICT, this `synchronized` is unnecessary.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 7]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
 
-  def setStackTrace(stackTrace: Array[StackTraceElement]): Unit = {
-    var i = 0
-    while (i < stackTrace.length) {
-      if (stackTrace(i) eq null)
-        throw new NullPointerException()
-      i += 1
+  final def getSuppressed(): Array[Throwable] = {
+    if (suppressed == null) {
+      Array.empty[Throwable]
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:144]: As above:
```suggestion
      new Array[Throwable](0)
```

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 8]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
+    } else
+      this.synchronized {
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:146]: The `synchronized` should also surround `if (suppressed == null)`, otherwise there can be an inconsistency.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 9]
```diff
@@ -163,6 +240,25 @@ class Throwable(s: String, private var e: Throwable)
     duplicates
   }
 
+  def setStackTrace(stackTrace: Array[StackTraceElement]): Unit = {
+
+    if (stackTrace eq null) {
+      throw new java.lang.NullPointerException()
+    }
+
+    for (i <- 0 until stackTrace.length) {
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:249]: Please keep the original loop with `while` and `var` here, once again so that `Throwable` does not rely on the Scala library.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 10]
```diff
@@ -163,6 +240,25 @@ class Throwable(s: String, private var e: Throwable)
     duplicates
   }
 
+  def setStackTrace(stackTrace: Array[StackTraceElement]): Unit = {
+
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:244]: The blank line here and at the end of the method are a tad too much, even for me who uses plenty of blank lines ;)

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 11]
```diff
@@ -163,6 +240,25 @@ class Throwable(s: String, private var e: Throwable)
...
+    if (stackTrace eq null) {
+      throw new java.lang.NullPointerException()
+    }
```
Comment (sjrd) [inline javalib/src/main/scala/java/lang/Throwables.scala:247]: This is redundant. Accessing `stackTrace.length` will itself throw an NPE if `stackTrace` is `null`.

File: unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala [hunk 12]
```diff
@@ -0,0 +1,356 @@
...
+  // the rightmost two arguments are true.
+
+  test("Throwable(message, cause, false, false)") {
+    val expectedMessage = "Athchomar chomakea"
+    val expectedCause   = new Throwable("Khal Drogo")
+
+    val throwable = new Throwable(expectedMessage, expectedCause, false, false)
+
+    checkConstructed(throwable, expectedMessage, expectedCause, 0)
+
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala:83]: These blank lines at the end of tests are unnecessary.

In general, avoid blank lines just after `{` and just before `}`, except in some cases of long `class`es and `object`s.

File: unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala [hunk 13]
```diff
@@ -0,0 +1,356 @@
...
+  }
+
+  // Thirteen public methods are documented for class Throwable.
+  //
+  // Five (5) methods: fillinStackTrace(), getCause(), getMessage(),
+  // getSuppressed(), printStackTrace(PrintWriter), have been exercised by
+  // constructor tests above and do not need separate tests. This is the
+  // Thetis problem.
```
Comment (sjrd) [inline unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala:123]: The "Thetis problem" does not ring any bell to me as a computer science thing. Perhaps this sentence can be removed?

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 3 above)
Comment (hepin1989) [reply javalib/src/main/scala/java/lang/Throwables.scala:107]: @LeeTibbert 
```scala
if(this.stackTrace ne null) this 
```
is not needed?

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 5 above)
Comment (hepin1989) [reply javalib/src/main/scala/java/lang/Throwables.scala:135]: Can `new Array[StackTraceElement](0) ` be shared?

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 3 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:107]: No, it isn't, and would even go against what the JVM does. If you first call `setStackTrace()` then `fillInStackTrace()`, the latter will overwrite the former.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 5 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:135]: I'm afraid not. On the JVM `getStackTrace()` always returns a new array, which is not `eq` to other 0-arg arrays (even coming from the same instance).

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 6 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:137]: I think an umpire's call is needed here.  I will follow your recommendation/requirement.

I believe that Array clone is not-thread-safe.  At the least, I can add a comment 
to the `suppressed` variable that it is not thread-safe and any given Throwable should
only be used by in a single thread.  If I were taking a Concurrency exam, that would
at least show that I had recognized the issue (and then punted it to future devos).

Scala Native currently follows the Scala.js  single threading model. 
I believe the synchronized is currently a call into a monitor method implemented as
a noop.  So, there is some execution cost and some review cognitive cost.

From my Operating System network kernel days, I tend to write thread-safe code
from the beginning because it is almost impossible to go back later and find the
non-thread-safe parts.   

It may be years in the future, but someday there will be customer pull for SN to
be multi-threaded.  I concur that currently SN has higher priority issues than
investing huge amount of time in thread safety.

I also believe that it would be a perverse & probably stupid multi-threaded
program which tried to write the same (eq) Throwable from two or more threads.


Large parts of the java.concurrent package are only EventLoop safe, and are 
documented in the code as such.  I do not remember if the ReadTheDocs documents
describe them as such.  I could check.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 14]
```diff
@@ -49,49 +49,126 @@ private[lang] object StackTrace {
...
+  // We use an Array rather than, say, a List, so that Throwable does not
+  // depend on the Scala collections.
+  private[this] var suppressed: Array[Throwable] = _
 
-  def getMessage(): String = s
+  final def addSuppressed(exception: Throwable): Unit = {
 
-  def getCause(): Throwable = e
+    if (exception == null) {
+      // Yes, JVM message uses 'cannot' (sic) & has terminal period/full_stop!
```
[the remark this answers is not in the document]
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:80]: Reference comment and one similar removed.

[the remark this answers is not in the document]
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:80]: Given review comment below, line 79 `if (exception == null) ` changed to use eq.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 4 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:85]: line #85 changed as recommended.

Based on this review comment, I swept through the code. In the places where the
js original (from a couple of days ago) used eq, I now use eq.   In places where I added code, I now use eq.

The java original had 12 instances of `== null` and 7 instances of `eq null`.
The former seemed like they all could/should have been `eq`.  From lack of
sufficient understanding, left those 12 as `==`  in this edit.

Please advise.  Thank you.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 5 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:135]: Changed as recommended.  I will use that practice in javalib code from now on, including responding to review.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 7 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:144]: Changed, thank you.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 8 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:146]: Changed as recommended. Thank you.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 10 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:244]: I swept through both files and removed blank lines after open-curly and before
close-curly.  There was one place in the Scala.js original which had a blank
line after the open-curly, so I did not change that.

I will use this style in code I am writing or changing from now on, including
reviewed files.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 11 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:247]: Removed, thank you.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 9 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:249]: `while` loop restored.    I understand now why that is needed.   

Guess that the Scala Coursera courses were pretty effective in discouraging use 
of `var` '-)  I understand this is a different context.

I probably have `for` loops and other Scala Libaryisms scattered over all the
javalib PRs I have open. I will keep my eye out for them (and try my best to not
write them in new code).

File: unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala (hunk 12 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala:83]: Thank you for the simple & clear decision rule.  I have made a local copy
and will use that practice going forward.

I swept through the file and deleted blank lines following that rule.  I think I got them
all.

File: unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala (hunk 13 above)
Comment (LeeTibbert) [reply unit-tests/src/test/scala/java/lang/ThrowablesSuite.scala:123]: Removed. Thank you.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 15]
```diff
@@ -10,15 +10,16 @@ private[lang] object StackTrace {
 
   private def makeStackTraceElement(
       cursor: Ptr[scala.Byte]): StackTraceElement = {
-    val name   = stackalloc[CChar](1024)
-    val offset = stackalloc[scala.Byte](8)
+    val nameMax = 1024
```
Comment (hepin1989) [inline javalib/src/main/scala/java/lang/Throwables.scala:13]: extract to a consntant?

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 16]
```diff
@@ -49,49 +50,123 @@ private[lang] object StackTrace {
...
+    this(message, cause, true, true)
+
   def this() = this(null, null)
+
   def this(s: String) = this(s, null)
+
   def this(e: Throwable) = this(if (e == null) null else e.toString, e)
 
-  private var stackTrace: Array[StackTraceElement] = _
+  private[this] var stackTrace: Array[StackTraceElement] = _
```
Comment (hepin1989) [inline javalib/src/main/scala/java/lang/Throwables.scala:69]: private[this] will be dropped in dotty 3.1

Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:69]: That's OK. We're a long way away from 3.1. In the meantime, `private[this]` produces less junk in the NIR than just `private`.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 6 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:136]: I don't mean to say it's not necessary because synchronization is not necessary in general (otherwise I'd have recommended to remove *all* `synchronized`). But in this case I'm pretty sure it's not necessary.

`clone()` is not thread-safe while mutating the original array. However, any array that is stored in the field `stackTrace` is never modified after it is stored there. Therefore, when you read an array from `stackTrace`, it is effectively immutable, and you can `clone()` it without synchronization.

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 17]
```diff
@@ -163,6 +237,18 @@ class Throwable(s: String, private var e: Throwable)
     duplicates
   }
 
+  def setStackTrace(stackTrace: Array[StackTraceElement]): Unit = {
+    if (writableStackTrace) this.synchronized {
```
Comment (hepin1989) [inline javalib/src/main/scala/java/lang/Throwables.scala:241]: when do `setStackTrace` should we take `writableStackTrace` into account?

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 18]
```diff
@@ -163,6 +237,18 @@ class Throwable(s: String, private var e: Throwable)
...
+      var i = 0
+      while (i < stackTrace.length) {
+        if (stackTrace(i) eq null)
+          throw new NullPointerException()
```
Comment (hepin1989) [inline javalib/src/main/scala/java/lang/Throwables.scala:245]: any error message?

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 4 above)
Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala]: If one of the sides is a *literal* `null`, `==` and `eq` are equivalent. So this is fine.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 18 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:245]: Sharp eyes,  I believe that NullPointerException supplies its own message. 

When I did the port, I tried to minimize changes the Scala.js original.  I am always
wary of breaking things.   To the best of my memory, that code is preserved from the original. 

Adding custom message text is always a tradeoff: information added vs. the conceptual cost to devos & end users of being non-standard. I usually like to do the best that I
can to describe where an error happened. Mostly because I am likely to hit that error
myself and call down bad thoughts on the devo/

 The standard NPE is pretty clear & explicit. The accompanying stack trace gives the location where it happened.  I do not see what a custom message might add, but my
vision may be limited.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 15 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:13]: It is used two places in the same method, none more generally. Original code had two literals. By training, I wanted to make sure both places used the same value.

File: javalib/src/main/scala/java/lang/Throwables.scala (hunk 6 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/lang/Throwables.scala:136]: Thank you for the patient explanation.  Changed as recommended.

**Comment by LeeTibbert** [comment]
And thank you for the detailed review & merge. 

Among other benefits this fix greatly simplifies adding (and re-adding, long story)
SN support in Zio.  That software is a pretty good load & correctness test of SN,
so the benefit loops back around.
