### PR TITLE
Fix #2024: Use a shared Scope in the sbt plugin for all parallel tasks

### LINKED ISSUE #2024: nativeLink is flaky with (error: java.nio.file.ClosedFileSystemException)
Let's set the scene:

Build: https://travis-ci.com/github/keynmol/repro-scala-native-1
Minimal(?) repro: https://github.com/keynmol/repro-scala-native-1

Both my machine and the travis I used are debian-based.

Worst thing is, sometimes it succeeds (at different rates):

```
// run nativeLink 20 times
➜  scala-native-closed-filesystem git:(master) ✗ repeat 20 sbtn ';clean;nativeLink' >> output
➜  scala-native-closed-filesystem git:(master) ✗ cat output | ack 'ClosedFileSystemException|success'
[success] Total time: 5 s, completed Nov 19, 2020 6:57:56 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[success] Total time: 4 s, completed Nov 19, 2020 6:58:26 PM
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
```

Error:

```
[error] java.nio.file.ClosedFileSystemException
[error]         at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1103)
[error]         at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:324)
[error]         at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
[error]         at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
```

<details><summary>Full stacktrace</summary>

```
➜  scala-native-closed-filesystem git:(master) ✗ sbtn 'last app / Compile / nativeLink'              
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> last app / Compile / nativeLink
[error] java.nio.file.ClosedFileSystemException
[error]         at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1103)
[error]         at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:324)
[error]         at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
[error]         at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
[error]         at java.nio.file.Files.readAttributes(Files.java:1737)
[error]         at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[error]         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[error]         at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
[error]         at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
[error]         at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
[error]         at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
[error]         at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
[error]         at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
[error]         at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:170)
[error]         at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
[error]         at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[error]         at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
[error]         at scala.collection.Iterator.toStream(Iterator.scala:1417)
[error]         at scala.collection.Iterator.toStream$(Iterator.scala:1416)
[error]         at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
[error]         at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream.$anonfun$append$1(Stream.scala:255)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error]         at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:583)
[error]         at scala.collection.immutable.Map$MapBuilderImpl.$plus$plus$eq(Map.scala:533)
[error]         at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:354)
[error]         at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:352)
[error]         at scala.collection.AbstractTraversable.toMap(Traversable.scala:108)
[error]         at scala.scalanative.linker.ClassPath$Impl.<init>(ClassPath.scala:39)
[error]         at scala.scalanative.linker.ClassPath$.apply(ClassPath.scala:28)
[error]         at scala.scalanative.linker.ClassLoader$.$anonfun$fromDisk$1(ClassLoader.scala:17)
[error]         at scala.collection.immutable.List.map(List.scala:297)
[error]         at scala.scalanative.linker.ClassLoader$.fromDisk(ClassLoader.scala:16)
[error]         at scala.scalanative.linker.Link$.$anonfun$apply$1(Link.scala:12)
[error]         at scala.scalanative.util.Scope$.apply(Scope.scala:30)
[error]         at scala.scalanative.linker.Link$.apply(Link.scala:11)
[error]         at scala.scalanative.build.ScalaNative$.$anonfun$link$1(ScalaNative.scala:34)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:32)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error]         at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error]         at scala.scalanative.build.ScalaNative$.link(ScalaNative.scala:34)
[error]         at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:55)
[error]         at scala.scalanative.build.Logger.time(Logger.scala:32)
[error]         at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error]         at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error]         at scala.scalanative.build.Build$.build(Build.scala:53)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$11(ScalaNativePluginInternal.scala:145)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:220)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:145)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (app / Compile / nativeLink) java.nio.file.ClosedFileSystemException
[info] last app / Compile / nativeLink completed
```
</details>

### PR DESCRIPTION
**Pull request by WojciechMazur**
This PR resolves #2024 
When creating `JarDirectory` it creates a new `FileSystem` with URI based on jar path. It's acquired into `Scope`, registered global filesystems register, and closed after exiting it. In normal conditions when we're building only a single `App` it does not yield any problems. However, when there are multiple modules linked into executables in parallel exiting `Scope` may close FileSystem that is still used in other threads. It may result in `ClosedFileSystemException`

<del>This PR removes acquiring the mentioned FieleSystem. It means also means it would not be closed as before. 
JarDirectory currently is the only place using `Scope`, so we may try to remove it entirely from the codebase. </del>

This PR introduces shared scope used in multiple builds and closed on `onComplete` sbt event. It also changes implementation of `Scope` to `AtomicReference` instead of `var`

### CODE REVIEW

**Comment by sjrd** [comment]
Shouldn't we instead pass down a more appropriate `Scope`, which would be shared by parallel linking operations? Not closing the file systems can leave the .jar's locked, which can cause issues for projects with `exportJars` for example.

We can use sbt's `onComplete` as a hook of when to appropriate close down a `Scope` shared by concurrent tasks.

**Comment by WojciechMazur** [comment]
@sjrd  I've changed the implementation to use shared scope instead as you hinted.

File: util/src/main/scala/scala/scalanative/util/SharedScopeProvider.scala [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  private[this] val scope: Scope = Scope.unsafe
+
+  private def tryClose(usageId: Key): Unit = {
+    usages.getAndUpdate {
+      new UnaryOperator[Set[Key]] {
+        override def apply(s: Set[Key]): Set[Key] = {
+          val updated = s - usageId
+          if (updated.isEmpty) {
+            scope.close()
+          }
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/SharedScopeProvider.scala:27]: We cannot put that inside the `UnaryOperator`. The documentation of `getAndUpdate` specifically says that

> The function should be side-effect-free, since it may be re-applied when attempted updates fail due to contention among threads.

Instead, I think we should use `updateAndGet`, and perform this test on the *result* of `updateAndGet` instead of inside the lambda.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 2]
```diff
@@ -131,7 +132,9 @@ object ScalaNativePluginInternal {
           .withCompilerConfig(nativeConfig.value)
       }
 
-      interceptBuildException(Build.build(config, outpath.toPath))
+      sharedScope.identifiedBy(config) { implicit scope =>
```
Comment (sjrd) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:135]: Different projects can different `config`s and yet access the same jars. Identifying the scope by config is not going to solve the issue in all cases.

Why did you want an identifying key? Can't we simply use a single slot? (like we have a single slot for the allocated test adapters)

**Review by sjrd — CHANGES_REQUESTED** [review]

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala (hunk 2 above)
Comment (WojciechMazur) [reply sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:135]: > Why did you want an identifying key? Can't we simply use a single slot? (like we have a single slot for the allocated test adapters)

I thought that when uses `sbt nativeLink` and has multiple native subprojects it would call  `onComplete` for each of them, but apparently it would be called only once. It was only used in order to mark usages coming for different threads. I'll fix that as it is redundant.

File: util/src/main/scala/scala/scalanative/util/Scope.scala [hunk 3]
```diff
@@ -39,21 +41,34 @@ object Scope {
       throw new UnsupportedOperationException("Can't close forever Scope.")
   }
 
+  /** Unsafe manually managed scope.*/
+  def unsafe: Scope = new Impl {}
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/Scope.scala:45]: This should have `()` because it creates a different one each time:
```suggestion
  /** Unsafe manually managed scope.*/
  def unsafe(): Scope = new Impl {}
```

File: util/src/main/scala/scala/scalanative/util/Scope.scala [hunk 4]
```diff
@@ -39,21 +41,34 @@ object Scope {
...
       case Nil =>
         ()
 
-      case first :: rest =>
-        resources = rest
+      case _ =>
+        val first :: _ = set(_.tail)
         try first.close()
         finally close()
     }
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/Scope.scala:71]: This could be more thread-safe by taking a snapshot of `resources` only once:
```scala
def close(): Unit = {
  def loop(resources: Resources): Unit = resources match {
    case Nil =>
      ()
    case first :: rest =>
      try first.close()
      finally loop(rest)
  }
  loop(resources.getAndSet(Nil))
}

File: util/src/main/scala/scala/scalanative/util/Scope.scala [hunk 5]
```diff
@@ -39,21 +41,34 @@ object Scope {
...
+  /** Unsafe manually managed scope.*/
+  def unsafe: Scope = new Impl {}
+
   private sealed class Impl extends Scope {
-    private[this] var resources: List[Resource] = Nil
+    type Resources = List[Resource]
+
+    private[this] val resources = new AtomicReference[Resources](Nil)
+
+    private def set(fn: Resources => Resources): Resources =
```
Comment (sjrd) [inline util/src/main/scala/scala/scalanative/util/Scope.scala:52]: With the suggested implementation of `close()`, this will only be used in `acquire`. I suggest to inline it there, as it will be clearer that it's correct in the context of `acquire` than in a generic context where we don't know what `fn` does.

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 6]
```diff
@@ -77,6 +77,7 @@ object ScalaNativePluginInternal {
       val prev: () => Unit = onComplete.value
       () => {
         prev()
+        sharedScope.close()
```
Comment (sjrd) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:80]: This assumes that we can keep reusing a `sharedScope` after it has been closed. That's typically not a guarantee that `close()`-able things give, so I don't think we should rely on it.

Consider using a `var` to store `sharedScope`, and reset it to a new `Scope.unsafe()` after this `close()`.

**Review by sjrd — CHANGES_REQUESTED** [review]

**Review by sjrd — APPROVED** [review]
