### PR TITLE
Fix conflicting cross version suffixes when using `Cross.for3Use_2.13`

### LINKED ISSUE #2538: doc building failed for scala-2.13.8
command:
```
sbt ++2.13.8 tools2_13/doc
```

result:
```
 scala-native % sbt ++2.13.8 tools2_13/doc 
[info] welcome to sbt 1.6.1 (Homebrew Java 17)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading settings for project scala-native-build from build.sbt ...
[info] loading project definition from /Users/rssh/packages/scala-native/scala-native/project
[info] loading settings for project scala-native from build.sbt ...
[info] resolving key references (108218 settings) ...
[info] Detected JDK version 17
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Setting Scala version to 2.13.8 on 33 projects.
[info] Excluded 97 projects, run ++ 2.13.8 -v for more details.
[info] Reapplying settings...
[info] Detected JDK version 17
[info] set current project to scala-native (in build file:/Users/rssh/packages/scala-native/scala-native/)
[info] Main Scala API documentation to /Users/rssh/packages/scala-native/scala-native/tools/.2.13/target/scala-2.13/api...
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:74:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, build.LTO.None) => single()
[error]                             ^
[error] /Users/rssh/packages/scala-native/scala-native/tools/src/main/scala/scala/scalanative/codegen/CodeGen.scala:75:29: fruitless type test: a value of type scala.scalanative.build.Mode cannot also be a scala.scalanative.build.Mode.Release
[error]         case (_: build.Mode.Release, _)              => separate()
[error]                             ^
[error] two errors found
[error] Scaladoc generation failed
[error] 	at xsbt.Runner.run(ScaladocBridge.scala:50)
[error] 	at xsbt.ScaladocBridge.run(ScaladocBridge.scala:21)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:154)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2159)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (tools2_13 / Compile / doc) Scaladoc generation failed
[error] Total time: 6 s, completed 22 Jan 2022, 09:04:35

```

### LINKED ISSUE #2546: Libraries built with Scala Native (0.4.3) can't be used via `for3Use2_13`
If I build a library for Scala Native 2.13, it has these as dependencies:
```
org.scala-native:windowslib_native0.4_2.13
org.scala-native:nativelib_native0.4_2.13
org.scala-native:javalib_native0.4_2.13
org.scala-native:clib_native0.4_2.13
org.scala-native:posixlib_native0.4_2.13
org.scala-native:auxlib_native0.4_2.13
```
For example [`portable-scala-reflect`](https://search.maven.org/artifact/org.portable-scala/portable-scala-reflect_native0.4_2.13/1.1.1/jar)

If then somebody tries to use my library in a Scala Native _3_ project via `.cross(CrossVersion.for3Use2_13)`, Scala is confused
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/ondra/Projects/sbt-locales/"), "apiNative"):
[error]    org.scala-native:windowslib_native0.4 _3, _2.13
[error]    org.scala-native:nativelib_native0.4 _3, _2.13
[error]    org.scala-native:javalib_native0.4 _3, _2.13
[error]    org.scala-native:clib_native0.4 _3, _2.13
[error]    org.scala-native:posixlib_native0.4 _3, _2.13
[error]    org.scala-native:auxlib_native0.4 _3, _2.13
[error] stack trace is suppressed; run last apiNative / update for the full output
[error] (apiNative / update) Conflicting cross-version suffixes in: org.scala-native:windowslib_native0.4, org.scala-native:nativelib_native0.4, org.scala-native:javalib_native0.4, org.scala-native:clib_native0.4, org.scala-native:posixlib_native0.4, org.scala-native:auxlib_native0.4
```

Related:
https://github.com/portable-scala/portable-scala-reflect/issues/23#issuecomment-1021617780
https://github.com/cquiroz/sbt-locales/pull/190
https://github.com/scalameta/munit/pull/477

### PR DESCRIPTION
**Pull request by WojciechMazur**
This PR fixes #2546 

The problem exists because we do publish standard native libraries for both Scala 2.13 and Scala 3. Scala.js does not have this problem, because it does only use Scala 2.13 js library. In the case of Scala Native, using the same solution would not as easy:
* `nativelib` uses macros for multiple common operations, eg. `stackalloc[T]()`, `alloc[T]()`, we cannot use Scala 2 macros in Scala 3. We can make alloc implemented as a normal function, but stackalloc needs to be implemented as a macro (needs to be inlined) **< blocker >**
* Scala 3 Compiler Plugin needs `scala.scalanative.runtime.LazyVals` implementation at compile-time, we would need to ship it with both Scala 2.13 and Scala3 nativelib

The proposed solution is based using sbt `excludeDependencies`, we would use it to exclude Scala 3 native stdlib when using Scala 2.13, or to exclude 2.13 artifacts when using Scala 3. It works fine with sbt, but it's not an universal solution - similar changes would need to be applied in other build tools

Changes:
* Added scripted tests to reproduce conflicting cross-version suffixes in Scala 3 and 2.13 artifacts
* Fixed `currentBinaryVersion` in ScalaNativeCrossVersion, now it delegates to correct `nir.Versions` implementation 
* Added exclusion rules for project settings in ScalaNativePlugin
* Removed redundant explicit library dependencies for Scala Native standard library, they would be pulled tranistivelly from scalalib. 
* Fixed pattern match failing in Scala 2.13 - resolves #2538

### CODE REVIEW

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala [hunk 1]
```diff
@@ -26,19 +26,36 @@ object ScalaNativePluginInternal {
...
+        val scalaBinVersion =
+          if (scalaVersion.value.startsWith("3.")) "2.13"
+          else "3"
+        ExclusionRule()
+          .withOrganization("org.scala-native")
+          .withName(
+            s"${lib}_native${ScalaNativeCrossVersion.currentBinaryVersion}_${scalaBinVersion}"
+          )
+      }
+    },
```
Comment (WojciechMazur) [inline sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:58]: @lolgab You're way more experienced with mill build tool, do you think we would be able to apply this solution in mill?

@jchyb You worked with scala-cli, do you think it would possible to apply this fix there as well?

Comment (lolgab) [reply sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:58]: @WojciechMazur Yes, I think it is possible. I'll try to make a PR to implement this logic and let you know :)

Comment (jchyb) [reply sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:58]: @WojciechMazur it should be possible in scala-cli as well, I'll try making a PR next week (hopefully before scala-cli's next release)

Comment (WojciechMazur) [reply sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:58]: Thank you! According to the PR's let's keep them as the drafts until this we would be sure that we can use this workaround everywhere

**Comment by WojciechMazur** [comment]
@sjrd You have the most experience according to publishing libraries and making Scala.js frictionless, do you think this solution would work in the long period? 

There are 2 alternatives I can think of at this moment: 
* moving out `stackalloc` macros outside `nativelib` to a separate project that would have different implementation for scala 2 and 3 (but we would probably get to the same point)
* replacing `stackalloc` macros with another intrinsic operation that we would rewrite in compiler plugin - we have already `runtime.Intrinsics.stackalloc` which is used to allocate `RawPtr`

File: sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala (hunk 1 above)
Comment (lolgab) [reply sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala:58]: @WojciechMazur This should be it :)
https://github.com/com-lihaoyi/mill/pull/1738

**Comment by sjrd** [comment]
This is tricky. I had forgotten that the `alloc` methods were macros. I thought they were already compiler intrinsics.

I am pretty sure that this PR correctly works around the current situation, *provided that* the Scala 2 and Scala 3 artifacts for native-library are 100% binary-compatible with each other. This is probably the case, but it is almost impossible to validate that with full certainty.

I would say that this PR is at least better than the status quo. I  think it's OK to merge and release it.

In the long term, I believe a better solution is needed. I would recommend the alternative where `alloc` and `stackalloc` become compiler intrinsics. The compiler plugins should be able to recognize them in a pre-erasure phase, such as `PrepNativeInterop`, and replace them with their implementations. It might be a bit tedious to write, but it would be the most robust solution.
