### PR TITLE
Fix: #2187 Match with guards does not compile

### LINKED ISSUE #2187: [Scala 2.13.5] Match clause with guards fails to compile
When adding support for Scala Native to Scalameta we bumped into a compilation issue related to:

```scala
      def isEscapableSoftKeyword(t: Name, parent: Tree): Boolean = {
        t.value match {
          case "extension" if dialect.allowExtensionMethods =>
            parent.is[Term.Apply] || parent.is[Term.ApplyUsing]
          case "inline" if dialect.allowInlineMods =>
            parent.is[Term.Apply] || parent.is[Term.ApplyUsing] || parent.is[Term.ApplyInfix]
          case "*" if dialect.allowStarWildcardImport =>
            parent.is[Importee]
          case _ =>
            false
        }
      }
```

<details><summary>log</summary>

```
[error] ## Exception when compiling 88 sources to /home/tgodzik/Documents/scalameta/scalameta/trees/native/target/scala-2.13/classes
[error] java.util.NoSuchElementException: key not found: method default5
[error] scala.collection.MapOps.default(Map.scala:241)
[error] scala.collection.MapOps.default$(Map.scala:240)
[error] scala.collection.AbstractMap.default(Map.scala:372)
[error] scala.collection.mutable.HashMap.apply(HashMap.scala:425)
[error] scala.scalanative.nscplugin.NirGenStat$MethodEnv.resolve(NirGenStat.scala:43)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApplyLabel(NirGenExpr.scala:1012)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genApply(NirGenExpr.scala:995)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:100)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genIf(NirGenExpr.scala:203)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genIf(NirGenExpr.scala:186)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:72)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.$anonfun$genMatch$7(NirGenExpr.scala:279)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:64)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genIf(NirGenExpr.scala:198)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.loop$1(NirGenExpr.scala:277)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genIfsChain$1(NirGenExpr.scala:285)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genMatch(NirGenExpr.scala:294)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:74)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genBlock(NirGenExpr.scala:129)
[error] scala.scalanative.nscplugin.NirGenExpr$ExprBuffer.genExpr(NirGenExpr.scala:66)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethodBody$9(NirGenStat.scala:778)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.withOptSynchronized$1(NirGenStat.scala:731)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethodBody$8(NirGenStat.scala:778)
[error] scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genBody$1(NirGenStat.scala:777)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethodBody(NirGenStat.scala:785)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethod$3(NirGenStat.scala:613)
[error] scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethod$1(NirGenStat.scala:612)
[error] scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethod(NirGenStat.scala:569)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethods$1(NirGenStat.scala:515)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genMethods$1$adapted(NirGenStat.scala:513)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genMethods(NirGenStat.scala:513)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genNormalClass(NirGenStat.scala:118)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.$anonfun$genClass$1(NirGenStat.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
[error] scala.scalanative.nscplugin.NirGenStat$StatBuffer.genClass(NirGenStat.scala:90)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$3(NirGenPhase.scala:87)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$3$adapted(NirGenPhase.scala:87)
[error] scala.collection.mutable.UnrolledBuffer$Unrolled.foreach(UnrolledBuffer.scala:283)
[error] scala.collection.mutable.UnrolledBuffer.foreach(UnrolledBuffer.scala:151)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.$anonfun$apply$2(NirGenPhase.scala:87)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] scala.scalanative.util.ScopedVar$.scoped(ScopedVar.scala:41)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.apply(NirGenPhase.scala:87)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
[error] scala.scalanative.nscplugin.NirGenPhase$NirCodePhase.run(NirGenPhase.scala:60)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
[error] scala.tools.nsc.Global$Run.compileFiles(Global.scala:1614)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2177)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2134)
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2130)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]      
```
</details>

Minimized example:

```scala
object Test {
  def main(args: Array[String]): Unit = {
    "Hello, World!" match{
      case "Hello" if args.isEmpty => println("would fail")
      case _ => println("works!")
    }
  }
}
```

Connected to https://github.com/scalameta/scalameta/pull/2261

### PR DESCRIPTION
**Pull request by WojciechMazur**
This PR fixes #2187. Due to the optimizations done in Scala compiler to pattern matches if the case was successfully matched but non of its guard conditions were fulfilled it would jump to default case without checking for any other intermediate cases.  
When generating such a condition we have not yet generated the default case label, and though not registered it as a local method in `MethodEnv`. Trying to reference the default label in such a case would cause it to fail the whole compilation process.

Fix includes generating default expression before proceeding to generate any of match cases.

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

File: nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenExpr.scala [hunk 1]
```diff
@@ -264,11 +264,32 @@ trait NirGenExpr[G <: nsc.Global with Singleton] { self: NirGenPhase[G] =>
       }
 
       def genIfsChain(): Val = {
+        /* Default needs to be generated before any others and though added to
```
Comment (ekrich) [inline nscplugin/src/main/scala/scala/scalanative/nscplugin/NirGenExpr.scala:267]: I am having a hard time reading this sentence. Should it be "and then added"?
