### PR TITLE
 A few java.net.Inet*Address fixes

### LINKED ISSUE #2311: Opportunities for improvement in javalib SocketHelpers.scala
Another forget-me-not.  In the spirit of continuous improvement

1) A sweep though SocketHelpers should probably be done to ensure
    that failure conditions are detected/tested and appropriate
    translated errno reported (which may or may not mean
    zeroing errno before calls).  A careful reading of the
    Posix routines is needed.

2) The implementation of `def ipToHost(ip: String, isV6: Boolean): Option[String]` 
    can be _vastly_ simplified. That would make it easier to trace for correctness.
    `man getnameinfo` on Ubuntu 21.04, and possibly others, gives a good
     example.

    One should also take advantage in `ipToHost` that the `service` argument to 
    `getnameinfo()` call is never used in `ipToHost`.  
    
    `ipToHost() itself is used by javalib InetAddr, but only the host name is 
     returned` if (status == 0) Some(fromCString(host)) else None`.

    The service argument to `getnameinfo()` should be specified with (probably a null) 
    pointer and a 0 size. `man getnameinfo()` says that this will indicate to the called routine
    that argument is of no interest (and should not be written).

    No sense at all in asking for bytes to be written that are never read, even if we
    are talking of only 20 bytes or so.  Care in the small leads to care in the large.

This is just my grump list for this hour.  The keen eyes of a first year Introduction to 
Programming student could probably find more.

### LINKED ISSUE #2767: j.n.SocketHelpers#isReachableByEcho leaks memory on socket failure
Whilst reviewing a PR, I had the misfortune to be tracing code in `j.n.SocketHelpers`.
I noticed that method #isReachableByEcho will, on `socket` error,  leak the memory contained in
a potentially long chain of addrinfo structures.

```
 if (getaddrinfo(cIP, toCString(port.toString), hints, ret) != 0) {
        return false
      }

      val ai = !ret  // LeeT - have addrinfo chain here

      val sock = socket(ai.ai_family, SOCK_STREAM, ai.ai_protocol)

      try {
         if (sock < 0) {
             return false // addrinfo chain stranded here.
        }
```
Out of respect for the original author and their invested time,
I will try to mute my snark.

In any case, the block below should move before the `try` 
```
         if (sock < 0) {
             return false // addrinfo chain stranded here.
        }
``` 
Some coding styles recommend `return` from the middle of a method.
My University training to eschew such sticks with me to this day.

I have not crafted a solution, but I my thinking goes to adding a `try`
block after the `getaddrinfo` calls, and adjusting the `finally` at the
bottom of the method.

Of course, where there is one bug, there may be more.
On a quick scan, there is two (2) more  uses of `addrinfo` in that 
file, and both look like they have either the same bug, or its
close cousin.

### LINKED ISSUE #2842: javalib InetAddress.getByName() does not detect some invalid addresses
Discovered whilst trying to have epollcat have the same message on both JVM & Scala Native.

Both the JVM and  SN posixlib `InetAddress.getByName()` correctly report the invalid IPv4 
(and IPv6) name "10%en0" as invalid.

JVM reports the invalid IPv4 address "240.0.0." as invalid.  

Scala Native does not.  I suspect that SN will proceed to 
try to connect to whatever address `getByName` returned, which
is probably total garbage.  Eventually the TCP SYN 3-way handshake
should timeout and report that error.  javalib does not currently support
UDP. If it did, then UDP packets would probably be sent to Mars or Venus
or wherever spam goes.

### LINKED ISSUE #2847: javalib InetAddress needs simplification.
javalib InetAddress has served its purpose well. I believe that it was
a port from Harmony Java.

I suspect/believe that Scala Native's ability to call C code can lead
to simplifications and corrections in that code.

### LINKED ISSUE #2849: Javalib should honor 'java.net.preferIPv6Addresses' system property.
Handling the referenced system property did not make the first tranche of SN 0.5.0 javalib
IPv6 changes.  It's proper handling  is conspicuous, to some.

### PR DESCRIPTION
**Pull request by LeeTibbert**
This PR is intended for the Scala Native 0.5.0 branch.   I know of no limitations
which preclude it from the 0.4.n branch. Because of the large number of changes,
I would like to see this code prove itself in 0.5.0 before being backported to 0.4.n.

###### Authorship
This PR has been influenced by Arman Blige. This is not to imply that Arman
has seen, reviewed, or approved this code.  Thank you, Arman.

Snippets have been copied, under license, from [epollcat] (https://github.com/armanbilge/epollcat). 

All merit to Arman, all bugs to me.

##### Fixes:

* Fix #2849 

* Fix #2847

* Fix #2842
 
* Fix #2767 

* Fix #2311

##### Partial Fixes:

* Partial fix: #2808
  
  Added code in several places to try to detect incorrect conditions.
  This Issue becomes: "WWW - Watchful Waiting on Windows"

* Partial fix: #2863 

  The InetAddress & Inet6Address classes now handle entering (getByName())
  and displaying (toString(), getHostName(), etc.) IPv6 addresses which
  have scope_id/zone_id/interface_id (RFCs conflate the three) identifiers,
  Per the RFCs, the address part must be numeric. Both numeric (FE80::1%99)
  and non-numeric (FF80::1%en0) work.

  The success cases work as expected. No attempt was made to match the
  timing or message of a vast number of failure cases. Java detects some
  errors (invalid non-numeric interface_id) early and some late (attempting
  to use an invalid numeric interface_id). This code attempts to detect
  and report all invalid cases early.

  The change of this PR are a necessary but not sufficient condition to
  fixing issue #2863.

##### Concern

This work was done on a Little Endian machine. I believe all the CI machines are
also Little Endian.  I believe the code also works for Big Endian machines but
have not exercised it on such.

### CODE REVIEW

File: javalib/src/main/scala/java/net/InetAddress.scala [hunk 1]
```diff
@@ -592,105 +204,562 @@ object InetAddress extends InetAddressBase {
...
+        v6addr.sin6_family = AF_INET6.toUShort
+        // because the FQDN scope is Global, no need to set sin6_scope_id
+        val dst = v6addr.sin6_addr.at1.at(0).asInstanceOf[Ptr[Byte]]
+        memcpy(dst, from, 16.toUInt)
+      } else if (ipBA.length == 4) {
+        val v4addr = addr.asInstanceOf[Ptr[sockaddr_in]]
+        v4addr.sin_family = AF_INET.toUShort
+        v4addr.sin_addr = !(from.asInstanceOf[Ptr[in_addr]]) // Structure copy
+      } else {
+        throw new IOException("Invalid ipAddress length: ${ipBa.length}")
```
Comment (armanbilge) [inline javalib/src/main/scala/java/net/InetAddress.scala:506]:
```suggestion
        throw new IOException(s"Invalid ipAddress length: ${ipBa.length}")
```

Comment (LeeTibbert) [reply javalib/src/main/scala/java/net/InetAddress.scala:506]: Arman, thank you for the catch!  I will implement your suggestion.

File: javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala [hunk 2]
```diff
@@ -122,7 +124,9 @@ private[net] abstract class AbstractPlainSocketImpl extends SocketImpl {
     val src = inetAddress.getAddress()
 
     if (inetAddress.isInstanceOf[Inet6Address]) {
-      sa6.sin6_addr = src.asInstanceOf[in.in6_addr]
+      val from = src.asInstanceOf[scala.scalanative.runtime.Array[Byte]].at(0)
+      val dst = sa6.sin6_addr.at1.at(0).asInstanceOf[Ptr[Byte]]
+      memcpy(dst, from, 16.toUInt)
```
Comment (WojciechMazur) [inline javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala:129]: Would you mind adapting these lines to the Unsafe Arrays Ops and it's new `at` method before the merge? It should make these lines a bit cleaner

Comment (LeeTibbert) [reply javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala:129]: Using the new `at` method is my plan.  I have been checking the merge stream.  PR #2888 hit the 0.4.5
but has not yet been rolled forward to the 0.5.0 stream.  I do not want to rush the maintainer, who is
busy merging.

I think there are also a couple of other places I can use `at`, when it gets merged into 0.5.0 in the 
fullness of time.

This PR contains a number of changes. I am confident in it, but would like to see it exercised on 0.5.0
for awhile before being backported.   This is especially true hours before a/an 0.4.n release.
Yes, this is an exceedingly conservative approach.   

I know of nothing which precludes backporting, but have never tried this PR on 0.4.n.

Comment (WojciechMazur) [reply javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala:129]: Oh, sorry, I forget it was targeting the 0.4.x branch. In such a case, I don't want you to block until we would sync 0.4.x and the main branches again. Instead, let's merge it now and apply a fix when changes would be backported.

**Review by WojciechMazur — APPROVED** [review]

File: javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala (hunk 2 above)
Comment (LeeTibbert) [reply javalib/src/main/scala/java/net/AbstractPlainSocketImpl.scala:129]: Thank you for the merge.

| Oh, sorry, I forget it was targeting the 0.4.x branch.

It is the other way around.  This is 0.5.0 until it earns its keep.
I do not envy you sorting through the complexity.

I will keep my eyes peeled for when #2888 merges and apply
the fix.  I would much rather that @Arman be blamed for 
spraying memory than I ;-)
